### ISSUE TITLE
wizzard/setup not found

### ISSUE THREAD

**Issue by buckr** [ridwanskaterock/cicool#1]
I purchased your product from code canyon, downloaded it and put it under my server.  When I type "localhost/cicool", it attempts to load "localhost/cicool/wizzard/setup" and it kicks off a 404 "Object not found".

There is no 'wizzard' directory that came with the product I downloaded from code canyon so that is definitely the problem. It appears I did not get the entire product.  Please help.

Thanks,

-buckr

purchased on: 28 Dec 2016

**Comment by ridwanskaterock** [comment]
hello thanks buckr have previously purchased our items,
 be sure you've got a whole file, if there is an application/controllers/Wizzard.php in your web application?
If I may know what server you're using, what os?

**Comment by buckr** [comment]
I had in under a subdirectory (localhost/sitename/cicool) and it didn't like that.  I moved it up a level  (localhost/cicool) and it works fine now.  I didn't realize you had to put it at the top level.

Might want to update the install.txt.

thanks for the quick response!

**Comment by ridwanskaterock** [comment]
okay buckr nice if it works well, 
I will be described in more detail in a future update, 
if you like this, please rate this item the best for our, thank you
