### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by Vertexadm** [ridwanskaterock/cicool#10]
How to update my old version of Cicool ?

Best Regards

**Comment by ridwanskaterock** [comment]
following this step

https://github.com/ridwanskaterock/cicool/wiki/Upgrade-Guides-to-Version-1.9.5

hopefully can help

thanks

**Comment by Vertexadm** [comment]
Thanks you for the help,

**Comment by porcorreo** [comment]
Hello,
The update/upgrade process version information/wiki still missing .  The documentation is just until 2.3 version but rest of versions dont have it.  The files seems to be the same folders but, problem is que table changes.   Please it is very important to complete this kind of documentation.
Greetings
