### ISSUE TITLE
Auto join table input select type - wrong id in list

### ISSUE THREAD

**Issue by akuljana** [ridwanskaterock/cicool#100]
There is an error in list when select table with new join option.

If both tables have columns id, in view it takes id of joined table, not main table.

Example: if your **blog** table have column id, and your **blog category** table have column id, it will take blog category id but it suppose to take blog id.

**Comment by nurzaly** [comment]
got same problem..

**Comment by ridwanskaterock** [comment]
closed this issue has been fixed in version 2.3

thanks for waiting

good job
