### ISSUE TITLE
About Upgrade to 2.30 from 2.1

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#101]
Hello,

I want info on howto update to 2.30 from 2.1 version.

I want more info about new feature, I don't see that feature or I can't know use it. ??? 

Maybe is a stupid question, but I really don't found new relational feature for explode it. Sorry.

Thank you,

**Comment by ridwanskaterock** [comment]
hiii you can follow this guide https://github.com/ridwanskaterock/cicool/wiki/Upgrade-guide-to-version-2.3.0 .

relation daabase is query join for input type select on CRUD builder 

thanks
