### ISSUE TITLE
Forms Inputs not allowing entry

### ISSUE THREAD

**Issue by sottey** [ridwanskaterock/cicool#103]
I am seeing (in the newest version and the older version as well) that if I put a form that has text input onto a page, and that page is backend and has menus, it is impossible to enter text in the text box.

If I make it front end, it works.

If I make it backend, but use the empty template, it also works.

Any ideas on what that can be?

**Comment by ridwanskaterock** [comment]
For that you can use embed form on page or use shortcode on your custom page https://www.youtube.com/watch?v=OoK8XeHcErc

thanks

**Comment by sottey** [comment]
Thanks for the reply. That is how I am doing it. Another strange thing is that it works on the android browser but not my desktop browser.

I will research further. Thanks.
