### ISSUE TITLE
Problems with crud generator in tables with more than 80 fields

### ISSUE THREAD

**Issue by eduardopinheirors** [ridwanskaterock/cicool#105]
Hi. I'm interested in buying cicool. But before I tested version 2.0 to develop my application, and one of the tables has about 200 fields. Crud generated interface for approximately 80 fields only. Is there any limitation to this in the maximum number of fields a table can have? If this works, I'll buy the license. Thank you.

**Comment by ridwanskaterock** [comment]
For cicool there is no limit to create field, you can make a lot and unlimited input

thanks
