### ISSUE TITLE
A Database Error Occurred after create new CRUD

### ISSUE THREAD

**Issue by nurzaly** [ridwanskaterock/cicool#106]
![capture2](https://user-images.githubusercontent.com/11963465/29503283-e96ff39e-8668-11e7-8cbd-60b86b48a832.PNG)
Hi please help about this errors.. Thanks

![capture](https://user-images.githubusercontent.com/11963465/29503281-e5fa551a-8668-11e7-81f6-0bd73f2af97c.PNG)

**Comment by ridwanskaterock** [comment]
because this query there are two join aauth_user can you edit model and make 1 join for that 

thanks for it
