### ISSUE TITLE
Cant Create/Add Anything

### ISSUE THREAD

**Issue by hunterhn** [ridwanskaterock/cicool#107]
Until Here Everything is fine :
![image](https://user-images.githubusercontent.com/6807127/29582697-4d3fff92-8743-11e7-8dad-a9415b83d771.png)

But then when i Click on "Add new Crud"
![image](https://user-images.githubusercontent.com/6807127/29582730-65e869f8-8743-11e7-82ae-a76e64a8ca57.png)

Everything goes to hell, lol 
The same issue is Happening in API builder, form builder, what this can be ?

**Comment by ridwanskaterock** [comment]
You can follow this issue https://github.com/ridwanskaterock/cicool/issues/49

This issue has been resolved and in active because user installed on public hosting problem permission 

Thanks

Thanks

**Comment by hunterhn** [comment]
It's resolved But not because a public hosting, as you can see in the screen captures is local install.
As @graufb mentioned before, its about MySql Version and default permissions on Group By's 

Please update the querys,

Thank you
