### ISSUE TITLE
Select multiple - join not working

### ISSUE THREAD

**Issue by akuljana** [ridwanskaterock/cicool#108]
There is an error with join in list view when there are **Select multiple**, it show only first element in list view.

![capture1](https://user-images.githubusercontent.com/2221952/29710727-d57734fc-8991-11e7-96c5-ac0c51bfea97.JPG)

![capture2](https://user-images.githubusercontent.com/2221952/29710732-dce7f42e-8991-11e7-9160-465d66929c89.JPG)

![capture3](https://user-images.githubusercontent.com/2221952/29710735-dff170e6-8991-11e7-9baa-929931165926.JPG)

![capture4](https://user-images.githubusercontent.com/2221952/29710736-e1be9214-8991-11e7-8ff3-da1e59cc8524.JPG)

And could you please answer #100

**Comment by ridwanskaterock** [comment]
Yes since version 2.3 select multiple does not work, i will fix it in upcoming version thanks

Does not work because there is an auto join in use on the input type select

**Comment by ridwanskaterock** [comment]
and you can show multi category by writing this code on view or controller 

$categories = $this->db->get('categories')->where_in('categori.id', explode(',', $blog->category))->result();

thanks

**Comment by akuljana** [comment]
Please be precise and use correct atribute names, you created that blog and blog_category table.
Show where exactly to put this code.

**Comment by akuljana** [comment]
This is not fixed in new version, why?

**Comment by ridwanskaterock** [comment]
sorry i found the problem to select multiple display data because there is clashing with input type select,

are you able to save data?

I will evaluate to make improvements so that other types are not disturbed

yes for code you can place this 

`$categories = $this->db->get('blog_category')->where_in('blog_category.id', explode(',', $blog->category))->result(); `on view 

thanks

**Comment by ridwanskaterock** [comment]
sorry for the delay I hope I can finish it as soon as possible
