### ISSUE TITLE
 how you can integrate multiple file uploads

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#11]
hello, it is possible to enable multiple files uploads in the form builder? how can I include this feature?
Thanks

**Comment by ridwanskaterock** [comment]
hello currently do not support multiple file upload, but you can change several parts of code to create multiple upload,

cicool here using fine uploader, to make multiple uploads, you can read the documentation http://fineuploader.com/demos.html

thanks

**Comment by ridwanskaterock** [comment]
hiii good news for you,

for the next version I create multiple file upload feature

wait for the next version

thanks

**Comment by vin111** [comment]
Hello, I'm happy of the new function, When is the next release?

**Comment by ridwanskaterock** [comment]
as soon as this month will be my release, and pending review by the envanto,
i will create migration documentation from old version to new version

thanks

**Comment by ridwanskaterock** [comment]
hiii multiple upload ready in version 2.0.0

upgrade your app by following this wiki https://github.com/ridwanskaterock/cicool/wiki/Upgrade-guides-Version-1.9.5-to-version-2.0.0

**Comment by ridwanskaterock** [comment]
i will close this issue
