### ISSUE TITLE
Hampir semua menu di akses error gan

### ISSUE THREAD

**Issue by tri82wiyono** [ridwanskaterock/cicool#111]
selamat sore gan, saya har ini baru order aplikasi cicool agan, sudah berhasil diinstall, tapi ketika saya menjalankan shampir semua menu saya dapatkan error gan, mohon bantuannya gan : 

halaman crud builder : 
Fatal error: Cannot use lexical variable $crud as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\crud\crud_list.php on line 94
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $crud as a parameter name
Filename: crud/crud_list.php
Line Number: 94
Backtrace:

Halaman API Builder 
Fatal error: Cannot use lexical variable $rest as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\rest\rest_list.php on line 93
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $rest as a parameter name
Filename: rest/rest_list.php
Line Number: 93
Backtrace:

Halaman Page Builder : 

Fatal error: Cannot use lexical variable $page as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\page\page_list.php on line 107
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $page as a parameter name
Filename: page/page_list.php
Line Number: 107
Backtrace:

halaman form builder : 

Fatal error: Cannot use lexical variable $form as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\form\form_list.php on line 94
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $form as a parameter name
Filename: form/form_list.php
Line Number: 94
Backtrace:

halaman user : 

Fatal error: Cannot use lexical variable $user as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\user\user_list.php on line 115
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $user as a parameter name
Filename:user/user_list.php
Line Number: 115
Backtrace:

halaman group : 

Fatal error: Cannot use lexical variable $group as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\group\group_list.php on line 99
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $group as a parameter name
Filename: group/group_list.php
Line umber: 99
Backtrace:

halaman permission : 

Fatal error: Cannot use lexical variable $permission as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\permission\permission_list.php on line 95
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $permission as a parameter name
Filename: permission/permission_list.php
Line Number: 95
Backtrace:

halaman API Key : 

Fatal error: Cannot use lexical variable $keys as a parameter name in E:\XAMPP\htdocs\cicool\application\views\backend\standart\administrator\keys\keys_list.php on line 99
A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $keys as a parameter name
Filename: keys/keys_list.php
Line Number: 99
Backtrace:

tolong mhon bantuannya ya gan

**Comment by ridwanskaterock** [comment]
ini udah solve ya gan gunakan php versi 7.0 atau di bawahnya

**Comment by tri82wiyono** [comment]
belum saya coba, nanti saya coba kalo ada problem akan saya beri tahu
terima kasih gan :)

**Comment by ridwanskaterock** [comment]
ok gan sipp, kalo ada problem bisa di share thanks

**Comment by tri82wiyono** [comment]
oke gan

**Comment by munggaran** [comment]
harusnya dicari solusi untuk php yang baru, sebab versi lama-lama pasti akan ditinggalkan

**Comment by munggaran** [comment]
app-nya harus diupdate, fix:
<?php is_allowed('user_update_profile', function($user) use ($user){?>
diubah jadi sbb:
<?php is_allowed('user_update_profile', function($u) use ($user){?>

**Comment by munggaran** [comment]
`<?php is_allowed('user_update_profile', function($user) use ($user){?>
diubah jadi sbb:
<?php is_allowed('user_update_profile', function($u) use ($user){?>`

**Comment by tri82wiyono** [comment]
@munggaran agan mengalami hal yang sama ya, mau saya coba masukkan dari agan, semoga bisa

**Comment by ridwanskaterock** [comment]
fixed on version 2.5.8 

thanks
