### ISSUE TITLE
inject database aauth

### ISSUE THREAD

**Issue by ibnufajar727** [ridwanskaterock/cicool#112]
slamat sore masgan, saya mau nanya, apakah memungkinkan database aauth untuk dilakukan inject/insert user secara masal , baik itu lewat excel, maupun database, kalau ada kasih gambaran dikit kodingnya, maklum newbi, terimakasih

**Comment by ridwanskaterock** [comment]
ya mas bisa melakukan insert bulk pada aauth 

bisa mempelajari fungsi ini 

`
<?php

$users = $this->db->get('table_user_lama')->result();

foreach ($users as $row) {
 	$this->aauth->create_user($row->email, $row->password, $row->username);}
}

`

**Comment by ibnufajar727** [comment]
trimakasih, atas bantuannya
