### ISSUE TITLE
Any PHP Version above 5.5 cause many errors and blank pages with version 2.3.0 (sept 26 version)

### ISSUE THREAD

**Issue by sottey** [ridwanskaterock/cicool#113]
I see that PHP 7.1 is listed as supported. When I tried, the majority of edit and see pages were blank and the user, group and permissions pages gave a 500 with the error (differnet pages listed different vars $user, $permissions, $group, etc.): 

-Sep-2017 04:34:11 asia/jakarta] PHP Fatal error:  Cannot use lexical variable $crud as a parameter name in .../application/views/backend/standart/administrator/crud/crud_list.php on line 100

Changing the site's PHP version to 5.5 works to address all the issues, but anything above 5.5 causes these errors.

NOTE: changing the using() statement to something other than the var (i.e., change using($user) to $userfoo and then changing the references) fixes the listing problem.

Thanks for great software. I still love CICool!
Sean

**Comment by ridwanskaterock** [comment]
yes for that can you use PHP version 

5.6 or php 7.0 not 7.1

i am not yet testing on php 7.1 

because in php 7.1 there is a problem with lexical variable

thanks for it
