### ISSUE TITLE
Different User Records?

### ISSUE THREAD

**Issue by bizimicat** [ridwanskaterock/cicool#115]
Hello ridwans?
I bought it on September 19, 2017 and congratulate it very well. But I need my; you can see that each member / user has his or her own attached pages. you can not see the others. How can I do this? Can you help with this? 

hi, is there a picture sample on this?

**Comment by ridwanskaterock** [comment]
hiii thanks for buy my item, 
and apologize for this delay for a lot of support coming into my email and tickets


for page on page builder you can custom code like 

example you create page "testing" on page builder
![image](https://user-images.githubusercontent.com/9270445/31327930-72a04736-acfc-11e7-9032-edb96d61c1ac.png)

in your application you have 3 group level 

1. sales
2. supervisor
3. manager 

and you need page testing can be accessed by manager 

you can custom it 

file : `./application/controllers/Page.php`

you can add this code on function detail()
`$this->is_allowed('page_'.$slug);`

like this 
![image](https://user-images.githubusercontent.com/9270445/31327894-3d9e4740-acfc-11e7-89d9-469bbec4941c.png)


and for setup permission you can set like by access administrator/permission

you can create new permission 
![image](https://user-images.githubusercontent.com/9270445/31328074-3deabec6-acfd-11e7-9c88-dcb3f87a3e29.png)

![image](https://user-images.githubusercontent.com/9270445/31328087-5178ee4a-acfd-11e7-928b-ecda50adc2ea.png)

and you can check permission like this image and save 
![image](https://user-images.githubusercontent.com/9270445/31328125-8f824506-acfd-11e7-806e-30c592361c1d.png)

and now only manager can accessed page **page/testing** 

thanks

**Comment by bizimicat** [comment]
ridwans hi; Thank you very much. I wanted to send it as a picture. I wanted to tell you exactly. user1 (User Id 1) only user id 1 user2 (user id 2) only user id 2. Change ownership, read update. superadmin can read, delete, update or view all of your files.
![picture 1 - user and admin](https://user-images.githubusercontent.com/26839775/31403766-d07a069c-ae02-11e7-9792-aa43d85242c0.PNG)
![picture 2 add new crud](https://user-images.githubusercontent.com/26839775/31403767-d08141f0-ae02-11e7-9d5f-96f9d0ae4fa2.PNG)
![picture 3 ads list and user id](https://user-images.githubusercontent.com/26839775/31403771-d15cbb18-ae02-11e7-87e9-a6c69f53b2b1.PNG)
![picture 3 or contact list and user id](https://user-images.githubusercontent.com/26839775/31403770-d0f9416e-ae02-11e7-95ac-b9ba16a81be9.PNG)
![picture 4 user list](https://user-images.githubusercontent.com/26839775/31403768-d0e8369e-ae02-11e7-9b7c-91fee5ac009f.PNG)
![picture 5 group list](https://user-images.githubusercontent.com/26839775/31403769-d0e984ea-ae02-11e7-9969-6649f0c9eab0.PNG)

**Comment by ridwanskaterock** [comment]
you can add data filter and condition on model like this 

in function count_all() and get()
```
if (!$this->aauth->is_admin()) {
    $this->db->where('user_id', get_user_data('id');
}

```
and on controller edit_save and edit you can add same like this 

```
if (!$this->aauth->is_admin()) {
   $user = $this->model_user->find($id);
   if (get_user_data('id') != $user->id) {
      redirect_back();
   }
}
```

**Comment by bizimicat** [comment]
hi, thank you. I will have one more request from you. on which page we add these codes. can you send samples? unfortunately I'm not as professional as you.

**Comment by ridwanskaterock** [comment]
you can implement like this 

`php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');


/**
*| --------------------------------------------------------------------------
*| Blog Controller
*| --------------------------------------------------------------------------
*| Blog site
*|
*/
class Blog extends Admin	
{
	
	public function __construct()
	{
		parent::__construct();

		$this->load->model('model_blog');
	}

	/**
	* show all Blogs
	*
	* @var $offset String
	*/
	public function index($offset = 0)
	{
		$this->is_allowed('blog_list');

		$filter = $this->input->get('q');
		$field 	= $this->input->get('f');

		$this->data['blogs'] = $this->model_blog->get($filter, $field, $this->limit_page, $offset);
		$this->data['blog_counts'] = $this->model_blog->count_all($filter, $field);

		$config = [
			'base_url'     => 'administrator/blog/index/',
			'total_rows'   => $this->model_blog->count_all($filter, $field),
			'per_page'     => $this->limit_page,
			'uri_segment'  => 4,
		];

		$this->data['pagination'] = $this->pagination($config);

		$this->template->title('Blog List');
		$this->render('backend/standart/administrator/blog/blog_list', $this->data);
	}
	
	/**
	* Add new blogs
	*
	*/
	public function add()
	{
		$this->is_allowed('blog_add');

		$this->template->title('Blog New');
		$this->render('backend/standart/administrator/blog/blog_add', $this->data);
	}

	/**
	* Add New Blogs
	*
	* @return JSON
	*/
	public function add_save()
	{
		if (!$this->is_allowed('blog_add', false)) {
			echo json_encode([
				'success' => false,
				'message' => cclang('sorry_you_do_not_have_permission_to_access')
				]);
			exit;
		}

		$this->form_validation->set_rules('judul', 'Judul', 'trim|required|max_length[200]');
		$this->form_validation->set_rules('content', 'Content', 'trim|required');
		$this->form_validation->set_rules('blog_image_name', 'Image', 'trim|required');
		$this->form_validation->set_rules('category', 'Category', 'trim|required|max_length[200]');
		$this->form_validation->set_rules('created_at', 'Created At', 'trim|required');
		$this->form_validation->set_rules('tags', 'Tags', 'trim|required|max_length[200]');
		

		if ($this->form_validation->run()) {
			$blog_image_uuid = $this->input->post('blog_image_uuid');
			$blog_image_name = $this->input->post('blog_image_name');
		
			$save_data = [
				'judul' => $this->input->post('judul'),
				'content' => $this->input->post('content'),
				'category' => $this->input->post('category'),
				'created_at' => $this->input->post('created_at'),
				'tags' => $this->input->post('tags'),
			];

			if (!is_dir(FCPATH . '/uploads/blog/')) {
				mkdir(FCPATH . '/uploads/blog/');
			}

			if (!empty($blog_image_name)) {
				$blog_image_name_copy = date('YmdHis') . '-' . $blog_image_name;

				rename(FCPATH . 'uploads/tmp/' . $blog_image_uuid . '/' . $blog_image_name, 
						FCPATH . 'uploads/blog/' . $blog_image_name_copy);

				if (!is_file(FCPATH . '/uploads/blog/' . $blog_image_name_copy)) {
					echo json_encode([
						'success' => false,
						'message' => 'Error uploading file'
						]);
					exit;
				}

				$save_data['image'] = $blog_image_name_copy;
			}
		
			
			$save_blog = $this->model_blog->store($save_data);

			if ($save_blog) {
				if ($this->input->post('save_type') == 'stay') {
					$this->data['success'] = true;
					$this->data['id'] 	   = $save_blog;
					$this->data['message'] = cclang('success_save_data_stay', [
						anchor('administrator/blog/edit/' . $save_blog, 'Edit Blog'),
						anchor('administrator/blog', ' Go back to list')
					]);
				} else {
					set_message(
						cclang('success_save_data_redirect', [
						anchor('administrator/blog/edit/' . $save_blog, 'Edit Blog')
					]), 'success');

            		$this->data['success'] = true;
					$this->data['redirect'] = base_url('administrator/blog');
				}
			} else {
				if ($this->input->post('save_type') == 'stay') {
					$this->data['success'] = false;
					$this->data['message'] = cclang('data_not_change');
				} else {
            		$this->data['success'] = false;
            		$this->data['message'] = cclang('data_not_change');
					$this->data['redirect'] = base_url('administrator/blog');
				}
			}

		} else {
			$this->data['success'] = false;
			$this->data['message'] = validation_errors();
		}

		echo json_encode($this->data);
	}
	
		/**
	* Update view Blogs
	*
	* @var $id String
	*/
	public function edit($id)
	{
		$this->is_allowed('blog_update');

		if (!$this->aauth->is_admin()) {
		   $blog = $this->model_blog->find($id);
		   if (get_user_data('id') != $blog->id) {
		      redirect_back();
		   }
		}

		$this->data['blog'] = $this->model_blog->find($id);

		$this->template->title('Blog Update');
		$this->render('backend/standart/administrator/blog/blog_update', $this->data);
	}

	/**
	* Update Blogs
	*
	* @var $id String
	*/
	public function edit_save($id)
	{
		if (!$this->is_allowed('blog_update', false)) {
			echo json_encode([
				'success' => false,
				'message' => cclang('sorry_you_do_not_have_permission_to_access')
				]);
			exit;
		}

		if (!$this->aauth->is_admin()) {
		   $blog = $this->model_blog->find($id);
		   if (get_user_data('id') != $blog->id) {
		      echo json_encode([
					'success' => false,
					'message' => cclang('sorry_you_do_not_have_permission_to_access')
					]);
				exit;
		   }
		}
		
		$this->form_validation->set_rules('judul', 'Judul', 'trim|required|max_length[200]');
		$this->form_validation->set_rules('content', 'Content', 'trim|required');
		$this->form_validation->set_rules('blog_image_name', 'Image', 'trim|required');
		$this->form_validation->set_rules('category', 'Category', 'trim|required|max_length[200]');
		$this->form_validation->set_rules('created_at', 'Created At', 'trim|required');
		$this->form_validation->set_rules('tags', 'Tags', 'trim|required|max_length[200]');
		
		if ($this->form_validation->run()) {
			$blog_image_uuid = $this->input->post('blog_image_uuid');
			$blog_image_name = $this->input->post('blog_image_name');
		
			$save_data = [
				'judul' => $this->input->post('judul'),
				'content' => $this->input->post('content'),
				'category' => $this->input->post('category'),
				'created_at' => $this->input->post('created_at'),
				'tags' => $this->input->post('tags'),
			];

			if (!is_dir(FCPATH . '/uploads/blog/')) {
				mkdir(FCPATH . '/uploads/blog/');
			}

			if (!empty($blog_image_uuid)) {
				$blog_image_name_copy = date('YmdHis') . '-' . $blog_image_name;

				rename(FCPATH . 'uploads/tmp/' . $blog_image_uuid . '/' . $blog_image_name, 
						FCPATH . 'uploads/blog/' . $blog_image_name_copy);

				if (!is_file(FCPATH . '/uploads/blog/' . $blog_image_name_copy)) {
					echo json_encode([
						'success' => false,
						'message' => 'Error uploading file'
						]);
					exit;
				}

				$save_data['image'] = $blog_image_name_copy;
			}
		
			
			$save_blog = $this->model_blog->change($id, $save_data);

			if ($save_blog) {
				if ($this->input->post('save_type') == 'stay') {
					$this->data['success'] = true;
					$this->data['id'] 	   = $id;
					$this->data['message'] = cclang('success_update_data_stay', [
						anchor('administrator/blog', ' Go back to list')
					]);
				} else {
					set_message(
						cclang('success_update_data_redirect', [
					]), 'success');

            		$this->data['success'] = true;
					$this->data['redirect'] = base_url('administrator/blog');
				}
			} else {
				if ($this->input->post('save_type') == 'stay') {
					$this->data['success'] = false;
					$this->data['message'] = cclang('data_not_change');
				} else {
            		$this->data['success'] = false;
            		$this->data['message'] = cclang('data_not_change');
					$this->data['redirect'] = base_url('administrator/blog');
				}
			}
		} else {
			$this->data['success'] = false;
			$this->data['message'] = validation_errors();
		}

		echo json_encode($this->data);
	}
	
	/**
	* delete Blogs
	*
	* @var $id String
	*/
	public function delete($id)
	{
		$this->is_allowed('blog_delete');

		$this->load->helper('file');

		$arr_id = $this->input->get('id');
		$remove = false;

		if (!empty($id)) {
			$remove = $this->_remove($id);
		} elseif (count($arr_id) >0) {
			foreach ($arr_id as $id) {
				$remove = $this->_remove($id);
			}
		}

		if ($remove) {
            set_message(cclang('has_been_deleted', 'blog'), 'success');
        } else {
            set_message(cclang('error_delete', 'blog'), 'error');
        }

		redirect_back();
	}

		/**
	* View view Blogs
	*
	* @var $id String
	*/
	public function view($id)
	{
		$this->is_allowed('blog_view');

		$this->data['blog'] = $this->model_blog->join_avaiable()->find($id);

		$this->template->title('Blog Detail');
		$this->render('backend/standart/administrator/blog/blog_view', $this->data);
	}
	
	/**
	* delete Blogs
	*
	* @var $id String
	*/
	private function _remove($id)
	{
		$blog = $this->model_blog->find($id);

		if (!empty($blog->image)) {
			$path = FCPATH . '/uploads/blog/' . $blog->image;

			if (is_file($path)) {
				$delete_file = unlink($path);
			}
		}
		
		
		return $this->model_blog->remove($id);
	}
	
	/**
	* Upload Image Blog	* 
	* @return JSON
	*/
	public function upload_image_file()
	{
		if (!$this->is_allowed('blog_add', false)) {
			echo json_encode([
				'success' => false,
				'message' => cclang('sorry_you_do_not_have_permission_to_access')
				]);
			exit;
		}

		$uuid = $this->input->post('qquuid');

		echo $this->upload_file([
			'uuid' 		 	=> $uuid,
			'table_name' 	=> 'blog',
		]);
	}

	/**
	* Delete Image Blog	* 
	* @return JSON
	*/
	public function delete_image_file($uuid)
	{
		if (!$this->is_allowed('blog_delete', false)) {
			echo json_encode([
				'success' => false,
				'error' => cclang('sorry_you_do_not_have_permission_to_access')
				]);
			exit;
		}

		echo $this->delete_file([
            'uuid'              => $uuid, 
            'delete_by'         => $this->input->get('by'), 
            'field_name'        => 'image', 
            'upload_path_tmp'   => './uploads/tmp/',
            'table_name'        => 'blog',
            'primary_key'       => 'id',
            'upload_path'       => 'uploads/blog/'
        ]);
	}

	/**
	* Get Image Blog	* 
	* @return JSON
	*/
	public function get_image_file($id)
	{
		if (!$this->is_allowed('blog_update', false)) {
			echo json_encode([
				'success' => false,
				'message' => 'Image not loaded, you do not have permission to access'
				]);
			exit;
		}

		$blog = $this->model_blog->find($id);

		echo $this->get_file([
            'uuid'              => $id, 
            'delete_by'         => 'id', 
            'field_name'        => 'image', 
            'table_name'        => 'blog',
            'primary_key'       => 'id',
            'upload_path'       => 'uploads/blog/',
            'delete_endpoint'   => 'administrator/blog/delete_image_file'
        ]);
	}
	
	
	/**
	* Export to excel
	*
	* @return Files Excel .xls
	*/
	public function export()
	{
		$this->is_allowed('blog_export');

		$this->model_blog->export('blog', 'blog');
	}

	/**
	* Export to PDF
	*
	* @return Files PDF .pdf
	*/
	public function export_pdf()
	{
		$this->is_allowed('blog_export');

		$this->model_blog->pdf('blog', 'blog');
	}
}


/* End of file blog.php */
/* Location: ./application/controllers/administrator/Blog.php */
`

`php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Model_blog extends MY_Model {

	private $primary_key 	= 'id';
	private $table_name 	= 'blog';
	private $field_search 	= ['judul', 'content', 'image', 'category', 'created_at', 'tags'];

	public function __construct()
	{
		$config = array(
			'primary_key' 	=> $this->primary_key,
		 	'table_name' 	=> $this->table_name,
		 	'field_search' 	=> $this->field_search,
		 );

		parent::__construct($config);
	}

	public function count_all($q = null, $field = null)
	{
		$iterasi = 1;
        $num = count($this->field_search);
        $where = NULL;
        $q = $this->scurity($q);
		$field = $this->scurity($field);

        if (empty($field)) {
	        foreach ($this->field_search as $field) {
	            if ($iterasi == 1) {
	                $where .= "blog.".$field . " LIKE '%" . $q . "%' ";
	            } else {
	                $where .= "OR " . "blog.".$field . " LIKE '%" . $q . "%' ";
	            }
	            $iterasi++;
	        }

	        $where = '('.$where.')';
        } else {
        	$where .= "(" . "blog.".$field . " LIKE '%" . $q . "%' )";
        }

        if (!$this->aauth->is_admin()) {
		    $this->db->where('user_id', get_user_data('id');
		}

		$this->join_avaiable();
        $this->db->where($where);
		$query = $this->db->get($this->table_name);

		return $query->num_rows();
	}

	public function get($q = null, $field = null, $limit = 0, $offset = 0, $select_field = [])
	{
		$iterasi = 1;
        $num = count($this->field_search);
        $where = NULL;
        $q = $this->scurity($q);
		$field = $this->scurity($field);

        if (empty($field)) {
	        foreach ($this->field_search as $field) {
	            if ($iterasi == 1) {
	                $where .= "blog.".$field . " LIKE '%" . $q . "%' ";
	            } else {
	                $where .= "OR " . "blog.".$field . " LIKE '%" . $q . "%' ";
	            }
	            $iterasi++;
	        }

	        $where = '('.$where.')';
        } else {
        	$where .= "(" . "blog.".$field . " LIKE '%" . $q . "%' )";
        }
        if (!$this->aauth->is_admin()) {
		    $this->db->where('user_id', get_user_data('id');
		}

        if (is_array($select_field) AND count($select_field)) {
        	$this->db->select($select_field);
        }
		
		$this->join_avaiable();
        $this->db->where($where);
        $this->db->limit($limit, $offset);
        $this->db->order_by('blog.'.$this->primary_key, "DESC");
		$query = $this->db->get($this->table_name);

		return $query->result();
	}

	public function join_avaiable() {

		
    	return $this;
	}

}

/* End of file Model_blog.php */
/* Location: ./application/models/Model_blog.php */
`
