### ISSUE TITLE
Sorting on View Screen

### ISSUE THREAD

**Issue by rumytaulu** [ridwanskaterock/cicool#116]
Hi Ridwan,
Nice product BTW, help me a lot especially the CRUD feature.
I have a question, is there any way I can sort the Crud View Output?, for example : by number, it is descending by default.

![screenshot from 2017-10-04 02-18-24](https://user-images.githubusercontent.com/14027018/31141572-5c0dd840-a8aa-11e7-97ca-49cae36df969.png)

**Comment by ridwanskaterock** [comment]
hii thanks for it

for current version sort by user not avaiable on view crud, 
for customize you can edit model 
on application/models/model_blog.php for example 

and you can get this 
![image](https://user-images.githubusercontent.com/9270445/31159115-e47c99be-a8f0-11e7-9528-c4e709e67e88.png)

and you can change to 
`
$this->db->order_by($this->primary_key, "DESC");`

thanks

**Comment by rumytaulu** [comment]
Thanks for the suggestion.
It works.
