### ISSUE TITLE
Editable select option

### ISSUE THREAD

**Issue by ramzi76** [ridwanskaterock/cicool#117]
Hello ridwans,

How to modify Select option to Editable select option (I would like to append the select option when the input text not in options list) ?

Thanks

**Comment by ridwanskaterock** [comment]
for example you can see this https://stackoverflow.com/questions/12199330/jquery-chosen-plugin-for-select-dropdown-get-id

https://github.com/koenpunt/chosen/issues/56

https://jsfiddle.net/espusntj/#run

https://stackoverflow.com/questions/11352207/jquery-chosen-plugin-add-options-dynamically

simple usage ```javascript

var value = $('.custom-input').val();
$('.youselect').append("<option value='"+key+"'>"+value+"</option>");
$('.youselect').trigger("chosen:updated");
```

thanks

**Comment by ramzi76** [comment]
Thank you ;)

**Comment by ridwanskaterock** [comment]
nice, yu're wellcome ;)
