### ISSUE TITLE
ganti/buat baru theme front page

### ISSUE THREAD

**Issue by ibnufajar727** [ridwanskaterock/cicool#118]
slamat pagi mas ridwan, saya ingin membuat theme untuk halaman depan cicool, saya sudah kopi smua folder di cc-content dan di tabel cc-option sudah saya rubah juga. pertanyaannya kenapa them saya tidak berubah ya. masih ikut bawaan cicool. trimakasih

**Comment by ridwanskaterock** [comment]
apa sudah di rubah mas pada opsi ini mas ? 

![image](https://user-images.githubusercontent.com/9270445/31497508-89635852-af89-11e7-9463-cb5c3f3003bd.png)

jika masih blm bisa bisa di lihat struktur folder di cc-content/page-template

**Comment by ibnufajar727** [comment]
sudah saya rubah mas, saya copy satu folder kemudian rename jadi cicool1(halaman home saya edit juga untuk pembeda), di database juga suda saya rename, tapi konten yang di load tetap mengacu ke theme yg cicool

**Comment by ridwanskaterock** [comment]
bisa di coba mas buka 
`Location: ./application/core/My_Controller.php`
![image](https://user-images.githubusercontent.com/9270445/31645816-50448c06-b328-11e7-8807-adf2217be132.png)

dan rubah pada box merah
