### ISSUE TITLE
Clarification for update from 1.9.5 to the latest version

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#119]
Hi, I have a project on version 1.9.5 in production, how do I upgrade to the latest version? Just copy the files, but the db should not be updated?

Can you explain the step-by-step procedure?

Do I need to update my project with the new files? Without installing it again?
and how do I get the db variations?

Thank you

**Comment by ridwanskaterock** [comment]
yes you just update file like instruction https://github.com/ridwanskaterock/cicool/wiki thanks
