### ISSUE TITLE
API's accept JSON instead of FORM URL ENCODED

### ISSUE THREAD

**Issue by plaviano** [ridwanskaterock/cicool#12]
There is something that we can do to the API controller's start accepting requests (POST, PUT, DELETE, GET, etc) with JSON body?

I tried adding 'Content-Type: application/json' header and forcing on the controller itself, without success.

Thanks in advance.

**Comment by ridwanskaterock** [comment]
This current response to API already supports JSON format whether there suatau constraints on the format that is given?

for more detail you can send a screenshot to us

**Comment by plaviano** [comment]
Thanks for your reply.

Note that my problem is with the REQUEST format, not the RESPONSE format.

If I send a FORM ENCODED REQUEST, works fine. But if I send a JSON REQUEST, controller do not recognize the parameters sent:

![image](https://cloud.githubusercontent.com/assets/13699695/22005358/9fe2b7d0-dc49-11e6-869f-10c6e5a61010.png)

**Comment by ridwanskaterock** [comment]
if you have tried to add the following code



```

$this->output
            ->set_content_type('application/json');
```

or 

`header('Content-Type: application/json');`


I quote from

http://stackoverflow.com/questions/18821492/code-igniter-how-to-return-json-response-from-controller

**Comment by ridwanskaterock** [comment]
this issue has been resolved ? 

i will close this issue 
thanks

**Comment by carlosanpardo** [comment]
Hello. To accept a JSON values into the REQUEST you need add:

`$this->form_validation->set_data($this->post());`

Example API->Request_Token:
