### ISSUE TITLE
Keep Loading Page Builder

### ISSUE THREAD

**Issue by nitishatmumbaionweb** [ridwanskaterock/cicool#123]
Hello!

I have an issue with the "Page Buillder": when I click on preview tab, then its keep loading and loading. And I am not able to see the added content in the "Page Builder".

Please check the next screenshoots that's keep loading: 
image_1 : https://drive.google.com/open?id=1KXAcixJlyRjykGNRbtH_77kb3BeaVRWC
image_2 : https://drive.google.com/open?id=12pMkXQLCfJWoMO7rBAmho-DcSYg9c3iO

Thank You in advance :)

**Comment by ridwanskaterock** [comment]
Hello..
What your browser on this case ? 

Can you use firefox browser ? 
.and you can see the console of browser 

Thanks :)

**Comment by nitishatmumbaionweb** [comment]
Hi,
Thank you so much for the response.

Well actually in this situation I am using Google Chrome and as you said to see the console, so in google chrome when I inspect the page (f12) I can see the errors in the console. Here is screenshot for those errors.

1 Screenshot:  This page is having some contents,
https://drive.google.com/open?id=1hC-n5dORpf99D_Mp0u6G2YkBOl43PzYr

2 Screenshot: This page with the errors in the console
https://drive.google.com/open?id=1I4lZFm59kApaoxO9OuO-1Qse0crnvv9x

I hope you will get my query here, now I am looking forward for your response with the best solution :)

Thank You

**Comment by ridwanskaterock** [comment]
hello sorry there seems to be a library that does not work maximally on the chroome browser, i have been trying to preview and preview appear in a long time, i will find a solution for it and fix the upcoming,

thank you for the results that have been submitted :-)

regards

**Comment by jerfran** [comment]
Hi my friend, i have the same issue on

 /administrator/crud/add 
/administrator/rest/add
/administrator/form/add 

Just shows a message: Loading, Getting Data

**Comment by ridwanskaterock** [comment]
can you see console of your browser ? 
i will find solution for that

**Comment by ridwanskaterock** [comment]
or you can read this issue https://github.com/ridwanskaterock/cicool/issues/49 thanks
