### ISSUE TITLE
d.m.Y

### ISSUE THREAD

**Issue by iny** [ridwanskaterock/cicool#124]
Hello there,

I want the date to look like this when I add the date to the Crud list "d.m.y". How can I do that?

**Comment by ridwanskaterock** [comment]
for this sample i user blog for that 

you can see file `application/backend/views/standart/blog/blog_list.php`

you can see type datetime field 
![image](https://user-images.githubusercontent.com/9270445/32587807-12fc2a30-c53d-11e7-883e-07b97a71b946.png)


and change this code `<?= _ent($blog->created_at); ?>`

to `<?=date('Y.m.d', strtotime($blog->created_at)); ?>`


thanks

**Comment by ilkiny** [comment]
Thank you in advance for your response. @ridwanskaterock 

Having a problem with Crud viewing, "Mustafa%20Kemal%20Atatürk" Url has both empty and turkish characters. This is a problem, how can I solve it?
`Severity: Notice

Message: Trying to get property of non-object

Filename: people/people_view.php

Line Number: 63

Backtrace:`

**Comment by ridwanskaterock** [comment]
can you chenck your code  people/people_view.php

on line 63 ? 

you can check for variable name

**Comment by ilkiny** [comment]
I checked, but there's no problem.

I get an error in the url section, I use something else instead of id, which is causing this problem.

Url has no Turkish character support and can not translate spaces. How can I solve the problem. This article may be as if "ş" translates to "s" in the following way. @ridwanskaterock

**Comment by ilkiny** [comment]
We can solve the problem in this way;

We need to edit and display the part as an id. But the API needs to have the Parameter title value. not id

**Comment by ilkiny** [comment]
Like this;

```
URLs
test/view/1
test/edit/1
```
**Json output**

```
{
"status": true,
"message": "Detail Test",
-"data": {
-"test": {
"id": "1", > Change ""title": "test 1"
"title": "test 1",
"content": "test",
"image": "test.jpg",
"category": "test",
"created_at": "2031-12-18 17:01:00"
}
}
}
```

**Comment by ridwanskaterock** [comment]
owh yes but for now update data must be from the id on the API
as params for update should do it with POST method to standardize

and for GET it could be but the param in the write is not like that

but


`test/view/?id=1`


thanks
