### ISSUE TITLE
Set realtion NtoN.

### ISSUE THREAD

**Issue by aleduran1** [ridwanskaterock/cicool#125]
Hi there, 

Could you please explain or created a guide, how to set with the CRUD a realtionNtoN, and then shows the models builded by CRUD as one module on the SideMenu, ex: Page, Blog, Media, Mycustom, etc,

**Comment by ridwanskaterock** [comment]
in this case i use blog module for it 

you can find model on `./application/models/Model_blog.php`

and see this function 

![image](https://user-images.githubusercontent.com/9270445/32587969-36e90fe8-c53e-11e7-91f9-24016c0ba769.png)


you can add your code manualy like this 


	`php
       public function join_avaiable() {

		$this->db->join('blog_category', 'blog_category.id = blog.category', 'LEFT');
    	return $this;
	}`

thanks

**Comment by ridwanskaterock** [comment]
`php public function join_avaiable() {

	$this->db->join('blog_category', 'blog_category.id = blog.category', 'LEFT');
	return $this;
}`
