### ISSUE TITLE
wrong link id on action

### ISSUE THREAD

**Issue by eduardopinheirors** [ridwanskaterock/cicool#126]
Hi. I am using the crud generator, in a table imo_cidades with 3 fields:
 id : int(10) - pk, not null, autoincrement
id_estado : int(10) fk, not null
cidade : varchar(80)

the PK of this table is the field id. 

when the crud is generated with the id_estado without relationships, as a input text filed, all works fine. 

but, when the id_estado is setted to be a select field, to display data from other related table, all records listed in the generated crud link to the same id = 1

[video-sábado,11-novembro-2017,02.08.mp4.zip](https://github.com/ridwanskaterock/cicool/files/1463434/video-sabado.11-novembro-2017.02.08.mp4.zip)

**Comment by ridwanskaterock** [comment]
yes for relation  will be display table reff for label for display id you can change select field reff and value to id 

thanks

**Comment by eduardopinheirors** [comment]
Sorry but I do not think you understand. is not working. I am correctly selecting the id for the value and the UF for the select label, but in doing so the links listed are no longer 1,2,3 but rather they are all 1,1,1

I need this corrected. If you want I'll provide you with a login.

**Comment by ridwanskaterock** [comment]
do you use select multiple? or single select?

can be

**Comment by eduardopinheirors** [comment]
Hello. see that in my first message I made up a video to demonstrate. a single select was used. it seems to me that it is a system bug. while the id field is an input text, it works, but when changing to select fetching the data from the other table, it does not work.

**Comment by eduardopinheirors** [comment]
hi. what´s happening? do you want to see my aplication with user and password?
