### ISSUE TITLE
error on upload multiple images

### ISSUE THREAD

**Issue by Geisyh** [ridwanskaterock/cicool#128]
Dear admin,

I have a problem, when creating CRUD with the field type file_multiple, there is a problem, I upload some pictures, on the finish, in preview it is perfect, when performing the Action to record, when accessing the recorded, there are several photos cloned.

Reason: 
When loading photos by selecting multiple photos at the same time, the problem occurs. however, if I manually load photo by photo (one photo at a time), the problem does not occur.

Screens:
1 - Database table
![01 - database table](https://user-images.githubusercontent.com/33624480/32723639-60370d72-c855-11e7-8a03-59b03a98ba1e.jpg)

2 - wizzard ok
![02 - setup wizzard requires](https://user-images.githubusercontent.com/33624480/32723651-6be46a7a-c855-11e7-83f2-42567222cecd.jpg)

3 - Create crud
![03 - create crud](https://user-images.githubusercontent.com/33624480/32723662-74543cb2-c855-11e7-9694-171f31e9a314.jpg)

4 - image selection mode
![04 - select mode](https://user-images.githubusercontent.com/33624480/32723785-f185febe-c855-11e7-84e7-d34e65ddcb6e.jpg)

5 - uploads - ok - perfect previews
![05 - uploading files - ok](https://user-images.githubusercontent.com/33624480/32723789-f5203044-c855-11e7-8890-b56f074fd967.jpg)

6 - on save
![06 - on save](https://user-images.githubusercontent.com/33624480/32723812-01ff06f0-c856-11e7-98d2-98a6b3b71aa8.jpg)

7 - on save - view
![07 - on save - view](https://user-images.githubusercontent.com/33624480/32723824-07038c66-c856-11e7-8c9e-9190482b86bb.jpg)

8 - on save - edit view
![08 - on save - edit view](https://user-images.githubusercontent.com/33624480/32723837-13107c3a-c856-11e7-8bce-4f7b1b96972a.jpg)

My version is: Version 2.5.0 (Sept 26, 2017)

Thank you!

**Comment by ridwanskaterock** [comment]
thank you for testing i will reproduce  same error and fixing on next updates thanks

**Comment by vin111** [comment]
Hello, when will the next version be released?

**Comment by ridwanskaterock** [comment]
maybe this month some improvements and features already there are done thnks

**Comment by kiwkiwrobotz** [comment]
Sundul gaaaan... 
![screenshot_63](https://user-images.githubusercontent.com/5318742/39666642-11d0568e-50d1-11e8-87d9-a3f5f132a522.png)

**Comment by kiwkiwrobotz** [comment]
i got the tricks,

before 2nd paramter put to save_data parameter 
remove the same string on the array,
using array dif 
https://www.w3schools.com/php/func_array_diff.asp

example : 
$upload1= implode($listed_image, ',');
$tmpDif1 = explode(',', $upload1);

=======================================================
example:
$upload1 = 'a,b'
$upload2 = 'a,b,c,d'
$upload3 = 'a,b,c,d,e,f'

tmpDif1 = array_diff($upload1, $upload2); --> will produce c,d
tmpDif2 = array_diff($upload1, $upload2, $upload3) -->will produce e,f

**Comment by ridwanskaterock** [comment]
thanks for help

**Comment by madasatya6** [comment]
Saya telah membeli cicool dan web nya sudah jadi. Ketika di localhost upload image bisa dijalankan. ketika sudah sampai hosting vps, upload image nya tidak bisa "**upload failed**", padahal sudah aku chmod -R 777 lokasi_folder. padahal juga upload foto menggunakan libraries bawaan codeigniter bisa kok di administrator cicool gak bisa???
