### ISSUE TITLE
error on multiples select multiple from same table

### ISSUE THREAD

**Issue by Geisyh** [ridwanskaterock/cicool#129]
Hello dear Admin, i again, LOL
This error occur when select two or more select fields referred with database table,

Example:
1 - My Tables:
![table_products](https://user-images.githubusercontent.com/33624480/33033612-2695a774-ce0c-11e7-99c0-fbf2486e8b74.png)

![table_list_products](https://user-images.githubusercontent.com/33624480/33033618-2d864cfa-ce0c-11e7-8f13-55b84e8a6099.png)

2 - Create CRUD
![model_save_list_products](https://user-images.githubusercontent.com/33624480/33033813-ee1650d2-ce0c-11e7-9465-111f9b4d6de9.png)

Table Products: I created the table and populate the same.
id => id primary key auto_increment
name => varchar(100)

Save and When I am accessing the CRUD, error occur, due to the join_avaiable () function in the model, check:

`
	public function join_avaiable() {

			$this->db->join('product', 'product.id = list_products.products_one', 'LEFT');
			$this->db->join('product', 'product.id = list_products.products_two', 'LEFT');
			$this->db->join('product', 'product.id = list_products.products_three', 'LEFT');
	    	
    	return $this;
	}
`

The Crud generates three Joins the same table.

Version: 2.5.0 (Sept 26, 2017)

This cicool is awesome!
Thank you!
o/

**Comment by ridwanskaterock** [comment]
what the error message you get ? 

why you join with same 3 table ?

seems it's will get error but bad for logic 

can you try join on mysql command / phpmyadmin with 3 table ? you will getting error 

thanks

**Comment by ridwanskaterock** [comment]
with alternative you can write this on view 
````php
$product1 = $this->model_product->find($list_product->product1);
$product2 = $this->model_product->find($list_product->product2);

````

etc

**Comment by negulescus** [comment]
I have the solution to your problem and it involves changing some code in multiple files in the CRUD generator. I will try to send it somehow to @ridwanskaterock to include it in the next release since I am not allowed to upload it on github.

**Comment by ridwanskaterock** [comment]
yes this problem because for table not use alias name i will make improvement for that

**Comment by pascal-linux** [comment]
I just bought cicool and I like it!
But I got the same error for crud generation with multiple tables.
Does someone already have the fix - or better: will the "next version" be released shortly?

Thanks,
Pascal

**Comment by isuwancita** [comment]
Hi Ridwan, I would like to ask whether CICOOL can use two databases (one for cicool, another database for other sources). I tried several time with Codeigniter method but no luck.
