### ISSUE TITLE
The requested URL /cicool/wizzard/setup was not found on this server.

### ISSUE THREAD

**Issue by h3ri** [ridwanskaterock/cicool#13]
saat ini sudah sy copy ke subdomain.domain/cicool namun saat redirect ke wizzard/setup, munculnya "The requested URL /cicool/wizzard/setup was not found on this server" sy coba lihat folder wizzard tapi g ketemu apalagi setupnya. tlg bantu mas ya. thanks.

**Comment by ridwanskaterock** [comment]
apa issue yang di alami sama seperti ini mas https://github.com/ridwanskaterock/cicool/issues/1 ?

**Comment by ridwanskaterock** [comment]
pastiin juga ada file ini di servernya ya ./application/controllers/Wizzard.php

**Comment by h3ri** [comment]
wizzard.php ternyata ada di foldernya. dan posisi diserver, subdomain.domain/cicool kayak yang mas referensikan. Sy coba localhost/cicool tulisannya "laman localhost tidak bekerja HTTP ERROR 500"

**Comment by h3ri** [comment]
kalo ini chat ini g terbuka untuk umum sy bisa bagi user n password cpanelnya

**Comment by h3ri** [comment]
sudah oke mas yg diserver, ternyata folder documentation g tercopy, tinggal utuk localhost, sy udah coba cara yg sama tapi belum berhasil. saat ini sy coba kedua folder sy letakkan di xampp g jalan, kemudian sy coba folder documentation digabungkan dengan cicool jg blm jalan

**Comment by ridwanskaterock** [comment]
ini issue visibilitynya publick mas , jadi bisa di lihat siapa saja, 
kalo untuk yang di local gimana mas ? notfound juga kah ?

**Comment by ridwanskaterock** [comment]
Owh iya mas untuk versi PHP juga harus > 5.4

**Comment by h3ri** [comment]
Oke. bener mas, ternyata karena PHPnya g sesuai. Trims mas Ridwan.

**Comment by omdiky** [comment]
Selamat malam pak, dapatkah cicool di pasarkannya di shopee atau bukalapak? Soalnya saya tidak punya kartu kredit kalau beli di envato...
Terus adakah vidio tutorial cara install yang di hosting? 
Saya beberapa kali beli tema web tapi gagal pas instal ke hostingnya...

**Comment by omdiky** [comment]
WA : 081296782131
