### ISSUE TITLE
Restful API & Database

### ISSUE THREAD

**Issue by sunil1707** [ridwanskaterock/cicool#130]
Hi,
My name is Sunil. Last month I have purchased your package to migrate my existing application (in CI3 ) for using the restful api feature of CICOOL. In my existing application most of the controllers output is in json format and thus it will be easy for me to use it. I have the following queries.  My purchase license is 1b54f8e4-aadc-4038-959e-d5fce84d4e62. I am using codeigniter since last 5 years.

1. My controllers have lot of object and array manupulation codes doue to hierarical nature of data and simple end point generation using your application is not possible. How can I use CICOOL to manually make api end points. ALSO all end points must be accessible to the authenticated users only.

2. I want to seperate the CICOOL database and my application database for clarity. I have the knowledge of how to use two database in codeigniter application but i need the specific solution in my case. I want to use default (i.e. db object) database object for my application and another database object say (db1) for CICOOL user management.

3. Also in my existing application I am using Laravel Eloquent ORM (I have integrated it with CI3). Will I need to take care anything to continue using it for my application.

**Comment by ridwanskaterock** [comment]
hi greetings

to use API only user registered in cicool has X-Token and user must login first to get the token you can get token by looking at documentation


maybe after the installation you can add the 2nd database config and you can load it on the controller is not it?

yes for the laravel package is easy to actually in the fox and integrate save data cicool is located on each model and my_model.php maybe you can put it in situ ketikasave data takes place
