### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by anco68** [ridwanskaterock/cicool#131]
I have a regular license 

No way to install the script in any browser including Chrome and Icognito window in Chrome

If I select "Italian"... everything apparently works fine... but at the last step... an error occur something like no language file find

If I select english... everything apparently works fine... but at the last step... 

An Error Was Encountered

The action you have requested is not allowed

please expalin me what going on... because I followed exctaly every single step of your TXT install file... and the server is ok on any requirements

thanks

**Comment by anco68** [comment]
I've separately trying to upload the folder (zipped) apidoc: and cpnael filemanager uploader give me this error:
The file you uploaded, apidoc.zip, contains a virus so the upload was canceled: Sanesecurity.Foxhole.JS_Zip_1.UNOFFICIAL FOUND

**Comment by ridwanskaterock** [comment]
For request not allowed can you set session save path to directory tmp on your system ? What your os ? 

You can also change environtment mode development on index.php for debugging

**Comment by ridwanskaterock** [comment]
Please for viruses can you check computer because this zip have been test on qc and internal

**Comment by anco68** [comment]
The virus issue I thik is related to some cPanel problem... because I've scanned with 3 antivirus the PC and no virus found on it.

The other issue I solved in a simle way: not using wizard... and manually install the site.php page (the DB was already created by the wizard)

thanks bye

**Comment by cnngraphics** [comment]
Thanks for that idea of manual installation and not the wizard
