### ISSUE TITLE
Please help.. ADD into REST API

### ISSUE THREAD

**Issue by douglasapuc** [ridwanskaterock/cicool#132]
Hi there, please help me with a piece of code to add entries on the rest api. I've tried the code bellow without avail, I get error 406.

I've tried your rest tools without success to.. can you please help me out? Is very urgent.

Thank you

```$.ajax({ url: “http://xxxxxxxx:80/api/form_banners_home/add”, data: { username: ‘douglasapuc’}, method: “POST”, beforeSend: function(xhr){xhr.setRequestHeader(‘X-Api-Key’, ‘MY_KEY’);}, success: function(json) ```

**Comment by ridwanskaterock** [comment]
can you send me response message or data 

or you can check it on https://github.com/ridwanskaterock/cicool/issues/3

for API using X-Token you must get token first and place in header X-Token 

get token you can read API or web documentation thanks

**Comment by fazilahasnida** [comment]
Hi there, please help me with a piece of code to add entries on the rest api. It got problem when i try to test the rest tool and got error. I can get the data when i key in token and api key.. but when i try using rest tool it is error..
{
"status": false,
"message": "Invalid API key "
}

why this happen?it need to copy or write any code if want to call it??sorry i'm still new..hope u can help me
thanks

**Comment by ridwanskaterock** [comment]
for this message APi key is not valid
