### ISSUE TITLE
Modification USER API

### ISSUE THREAD

**Issue by bartollo** [ridwanskaterock/cicool#133]
Hello, I need to include fields for the USER, but I can not add them in the POST and PUT method, I could not find them in the files. Could you tell me where I can make this modification? Would it be in the USER Controller / API add_post method? Please help me.

**Comment by ridwanskaterock** [comment]
yes for change method you can change method on controllers like 

update_post change to update_put 

i use this library for rest service https://github.com/chriskacerguis/codeigniter-restserver

you can read more and learn about this library

thanks
