### ISSUE TITLE
How to upload cicool project on servers (Live Server)

### ISSUE THREAD

**Issue by nitishatmumbaionweb** [ridwanskaterock/cicool#134]
Hi,
I have been working on project on my local XAMPP server since I purchased cicool, there was as I told you that I am facing one issue https://github.com/ridwanskaterock/cicool/issues/123  that is still not solved. Now apart from that issue I got new challenge, I uploaded my cicool project on live Server but the project is not working, or you can say the cicool is not responding on Live Server.
Will you please help me to upload my cicool project on Live Sever. If you have any kind of steps to upload projects on Live Server so please share with me.

Note: I want to upload my project on live server with working functionality, as at least it's working on local XAMPP server.

Thank You So Much in advance.

**Comment by ridwanskaterock** [comment]
Actually you don't have to other action to make cicool on live server.

You can change environtment to development for debugging on index.php




Pada tanggal 4 Des 2017 14:59, "nitishatmumbaionweb" <
notifications@github.com> menulis:
