### ISSUE TITLE
Install Back to Wizzard

### ISSUE THREAD

**Issue by zmutclik** [ridwanskaterock/cicool#135]
saya install masalah, pertanyanya ketika page 3 post data tidak mau "**An Error Was Encountered**" trus saya ganti ke index.php?/ database mau kesimpan, tp ketika finish kembali lagi ke Wizzard

**Comment by ridwanskaterock** [comment]
sebelumnya pakai os apa mas ? 

coba rubah environtment ke development dulu di index.php
