### ISSUE TITLE
crud error warning with saved data

### ISSUE THREAD

**Issue by r3ndyipb** [ridwanskaterock/cicool#138]
in the crud form i create in 1 form that some of its field relates to 1 table, then when I push the save button that happens its error warning appears, but the data is stored

**Comment by Blackquan** [comment]
same issue here. Pls support

**Comment by ridwanskaterock** [comment]
can you see XHR response for it ? @Blackquan

**Comment by Blackquan** [comment]
A Database Error Occurred Error Number: 1054

Unknown column ‘field_label’ in ‘field list’

INSERT INTO `crud_field` (`crud_id`, `field_name`, `field_label`, `input_type`, `show_column`, `show_add_form`, `show_update_form`, `show_detail_page`, `sort`, `relation_table`, `relation_value`, `relation_label`) VALUES (7, ‘id’, ‘id’, ‘number’, ’’, ’’, ’’, ‘yes’, ‘1’, ’’, ’’, ’’)

Filename: controllers/administrator/Crud.php

Line Number: 275

**Comment by Blackquan** [comment]
@ridwanskaterock

**Comment by ridwanskaterock** [comment]
can you check in table crud_field, the table have field_label field ? @Blackquan

**Comment by Blackquan** [comment]
@ridwanskaterock 
i don't, i did manual setup, use this file to insert your data sample 
https://www.dropbox.com/s/7smeevucaruie0e/cicool.zip?dl=0
from this link
https://github.com/ridwanskaterock/cicool/issues/61

**Comment by Blackquan** [comment]
@ridwanskaterock just check database, table crub_filed is empty. Pls guide me to fix

**Comment by ridwanskaterock** [comment]
You can create table structure like


Pada tanggal 19 Jan 2018 21:08, "Black Quan" <notifications@github.com>
menulis:

**Comment by carlosanpardo** [comment]
Hello! I obtain the same error with the last update: Check my XHR response:

`{"success":true,"redirect":"http:\/\/90grados.com.co\/facebook\/administrator\/crud"}
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/gradiente/public_html/facebook/application/controllers/administrator/Crud.php:92)</p>
<p>Filename: DebugBar/PhpHttpDriver.php</p>
<p>Line Number: 24</p>
	<p>Backtrace:</p>
	
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php<br />
			Line: 24<br />
			Function: header			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php<br />
			Line: 327<br />
			Function: setHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 386<br />
			Function: sendDataInHeaders			</p>
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/application/libraries/Profiler.php<br />
			Line: 374<br />
			Function: _render			</p>
		
	
		
	
		
	
		
			<p style="margin-left:10px">
			File: /home/gradiente/public_html/facebook/index.php<br />
			Line: 315<br />
			Function: require_once			</p>
		
	
</div>`

**Comment by r3ndyipb** [comment]
in case u can comment the header function, you can find in this file : 
/home/gradiente/public_html/facebook/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php

case close :/
