### ISSUE TITLE
apakah folder cicool bisa di rename?

### ISSUE THREAD

**Issue by h3ri** [ridwanskaterock/cicool#14]
mas mau nanya, apakah setiap pengunjung website harus diarahkan ke domain/cicool atau bisa direname. maaf kalo pertanyaanya awam banget. trims ya :)

**Comment by ridwanskaterock** [comment]
bisa mas folder cicool itu bisa di rename atau isinya bisa di taruh di folder root 
misal public_html / htdocs / www 

sama sama mas

di tunggu reviewnya ya hehe

**Comment by h3ri** [comment]
oke udah bisa mas, tapi foler documentation nya musti digabungkan ke dalam folder cicool (atau nama folder after rename). trims..
