### ISSUE TITLE
Error - Add crud/Rest

### ISSUE THREAD

**Issue by kumarkreative** [ridwanskaterock/cicool#140]
Hi,

When i click on Add CRUD and REST button to create, the page is not loading in a proper design format.

Please check this link : https://snag.gy/GXtbRa.jpg

**Comment by ridwanskaterock** [comment]
you can check it for related issue 

https://github.com/ridwanskaterock/cicool/issues/49

thanks

**Comment by kumarkreative** [comment]
I have "solved" it by changing msql setting sql_mode to ''
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

It´s a test server so I don't care.

But you should update your code on next release.

**Comment by ridwanskaterock** [comment]
time some versions ago I made it that way but there are some users who
complain when error runs that code, i will identify this problem thanks

2018-04-18 17:14 GMT+07:00 kumarkreative <notifications@github.com>:
