### ISSUE TITLE
Language Parameter

### ISSUE THREAD

**Issue by ilkiny** [ridwanskaterock/cicool#141]
Hello there,

Can we use a value to distinguish different languages of the same content? @ridwanskaterock 

Like this;

language=tr-TR
language=en_US

**Comment by ridwanskaterock** [comment]
hii for that mayhis wiki can help you 
https://github.com/ridwanskaterock/cicool/wiki/How-to-add-new-language

thanks

**Comment by ilkiny** [comment]
I am not looking for site translation.

For the json output, the Language Parameter

Like this;

example.com/api/blog/detail?X-Api-Key=xxx&id=5&language=tr-TR or language=en_US

**Comment by ridwanskaterock** [comment]
sorry for long response i just working today

for this feature is not avaiable 

i just make it for next version thanks

**Comment by ilkiny** [comment]
When will the new version be released? @ridwanskaterock By the way, what is your email address? I have a few questions to ask.

**Comment by ridwanskaterock** [comment]
On current veraion this feature not avaiable.

But you can change language by vositing this url

Example.com/web/switch_lang/english

My email is ridwanskaterocks@gmail.com

Thanks

Pada tanggal 4 Jan 2018 22:14, "ilkiny" <notifications@github.com> menulis:

**Comment by iny** [comment]
Any improvement?

**Comment by ridwanskaterock** [comment]
i just update it on version 2.5.8 please wait for review by QC, 
on API you can fill param

?lang=french

thanks
