### ISSUE TITLE
Polish language

### ISSUE THREAD

**Issue by adixoncode** [ridwanskaterock/cicool#143]
Hi,

In code i saw polish language file, how can I use this? Is available or not?

Regards,
Adrian

**Comment by ridwanskaterock** [comment]
yes for it you can change language on top menu ?

for admin you can change general language on module settings

2018-01-08 18:53 GMT+07:00 Adrian <notifications@github.com>:

**Comment by adixoncode** [comment]
No, I dont have polish language on front and admin too...

**Comment by ridwanskaterock** [comment]
maybe this wiki can help you for make new polish lang 

https://github.com/ridwanskaterock/cicool/wiki/How-to-add-new-language

thanks
