### ISSUE TITLE
Install issue with ubuntu server

### ISSUE THREAD

**Issue by Blackquan** [ridwanskaterock/cicool#144]
Hi, i have a problem when i try to install script

Not Found
The requested URL /wizzard/language was not found on this server.
Apache/2.4.18 (Ubuntu) Server at api.halodigital.net Port 80

my vps is apache here is php info http://128.199.82.253/info.php

Please support

**Comment by ridwanskaterock** [comment]
hii @Blackquan  before install 
please activate mod_rewrite on your server configuration thanks

**Comment by Blackquan** [comment]
yes, i did it. but still the same error :(

**Comment by Blackquan** [comment]
hi, it's running
Thank you

**Comment by ridwanskaterock** [comment]
sound goods, great job :)
