### ISSUE TITLE
Dashboard is visible even if the user shouldn't have access to it

### ISSUE THREAD

**Issue by negulescus** [ridwanskaterock/cicool#145]
Hello,

The dashboard is visible for all users which are logged in.
The index function in the controller dashboard.php shall probably do the following:
`$this->is_allowed('dashboard');`
also, it shall render the first page to which the user has access to in the backend.

**Comment by ridwanskaterock** [comment]
yes for it you can give member for access permission 
on url/administrator/access
thanks

**Comment by negulescus** [comment]
Sorry, I wasn't clear:  all users can access it even if they don't have the rights.

**Comment by ridwanskaterock** [comment]
oh okay for spesific user / group can assing dashboard 

you can change 

![image](https://user-images.githubusercontent.com/9270445/34931047-2ad70962-f9ff-11e7-9dfd-273d8fe99e69.png)


to 
`$this->is_allowed('dashboard');`

and you can make new permission 

on administrator/permission

and you can manage access on administrator/access

**Comment by negulescus** [comment]
Cool. Iknow that. I thought that maybe you can include it so it is available by default for the next release. :)

**Comment by ridwanskaterock** [comment]
okay thanks for it i will do it for next release 

thanks :)

**Comment by ridwanskaterock** [comment]
fixed on version 2.5.6 thanks
