### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by Blackquan** [ridwanskaterock/cicool#146]
I got issue, pls support

```
A Database Error Occurred
Error Number: 1054
Unknown column 'field_label' in 'field list'

INSERT INTO `crud_field` (`crud_id`, `field_name`, `field_label`, `input_type`, `show_column`, `show_add_form`, `show_update_form`, `show_detail_page`, `sort`, `relation_table`, `relation_value`, `relation_label`) VALUES (20, 'id', 'id', 'number', '', '', '', 'yes', '1', '', '', '')

Filename: controllers/administrator/Crud.php
Line Number: 275
```

**Comment by ridwanskaterock** [comment]
what your cicool version ? 
check on you r database table  crud_field have a field field_label
in latest version cicool added field_label to table crud_field 

thanks

**Comment by Blackquan** [comment]
@ridwanskaterock 
i passed this step. 
Now i can create CRUD, but when i click on action see on crud list, it show an other issues:

An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Model_halo_app

Filename: /var/www/api/public_html/system/core/Loader.php

Line Number: 344

Backtrace:

File: /var/www/api/public_html/application/core/My_Loader.php
Line: 150
Function: model

File: /var/www/api/public_html/application/controllers/administrator/Halo_app.php
Line: 19
Function: model

File: /var/www/api/public_html/index.php
Line: 315
Function: require_once

Please support

**Comment by ridwanskaterock** [comment]
can you check file exist ? on application/model/Model_halo_app.php 

thanks

**Comment by Blackquan** [comment]
so have to add write permission for that folder to create file. Pls note to document for next update. thank
