### ISSUE TITLE
used a web dynamic created or  a rest API created.

### ISSUE THREAD

**Issue by bounaf** [ridwanskaterock/cicool#147]
Dear,
I am a beginner web developer.
I find your tools powerful and complete and I would like to know how to use it thoroughly.
I could redo all your example and I find it great.
1- But problem is how can I use web pages, forms create with ciccool on an online server?
2- How did the APIs rest on an existing application?
3- How to make the link between the backend and the frontend of an application to create on a server in production?
I know it's a lot of questions, I think if everyone had these answers, you could sell your product better.
I bought your software, I can provide the purshased code for proof
I am looking forward to your answer.

**Comment by ridwanskaterock** [comment]
hii

1. for onnline server you can do sam local action, for use local code and you have use on server you can upload an files and export and import local db to server

2. for use result of generator you can copying files api of generates, 
core/My_controller.php and you can 
copy all libraries and 
use composer.json or copying vendor/. to your application 

3. do you mean to make a link for what?
for that you can use the repository with various branches


thanks
