### ISSUE TITLE
Disable API/POST Delect and api document can not create

### ISSUE THREAD

**Issue by Blackquan** [ridwanskaterock/cicool#148]
Hi, @ridwanskaterock 
1. How to disable API/Post Delect . i only want to get for some api, and make sure they can not delect by user
2. After create API, API document will auto create right? I do not see it, maybe need add 777 to some folder? Please guide
3. I found issue when go to administrator/access page
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/api/public_html/application/controllers/administrator/Access.php:134)

Filename: DebugBar/PhpHttpDriver.php

Line Number: 24

Backtrace:

File: /var/www/api/public_html/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php
Line: 24
Function: header

File: /var/www/api/public_html/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php
Line: 327
Function: setHeaders

File: /var/www/api/public_html/application/libraries/Profiler.php
Line: 386
Function: sendDataInHeaders

File: /var/www/api/public_html/application/libraries/Profiler.php
Line: 374
Function: _render

File: /var/www/api/public_html/index.php
Line: 315
Function: require_once

**Comment by ridwanskaterock** [comment]
hii @Blackquan 

1. How to disable API/Post Delect . i only want to get for some api, and make sure they can not delect by user

--> you can disable X-Token before generate API 

2. After create API, API document will auto create right? I do not see it, maybe need add 777 to some folder? Please guide

--> you can try change permission to write mode for folder apidoc/ and apidoc/module


3. I found issue when go to administrator/access page
A PHP Error was encountered
Severity: Warning

--> for it you can uncomment code on line 24 
/vendor/maximebf/debugbar/src/DebugBar/PhpHttpDriver.php
![image](https://user-images.githubusercontent.com/9270445/35334961-b068f128-0146-11e8-8379-95f68b8ee925.png)

**Comment by Blackquan** [comment]
@ridwanskaterock 
1-3 is ok now
for 2: API document still not auto create after have folder permission. i also want to remove group and blog. pls guide

**Comment by ridwanskaterock** [comment]
for permission apidoc can you set permission to 7777 on folder apidoc/module ?

**Comment by Blackquan** [comment]
@ridwanskaterock 
It worked. have to set permission for api_data.js to work
but new document have issue about link, they still keep link blog/update , blog delete, blog delete in document. Pls fix in next update. Thank you
