### ISSUE TITLE
Pegunjung bisa langsung masuk ke login dashboard tanpa melalui halaman muka

### ISSUE THREAD

**Issue by h3ri** [ridwanskaterock/cicool#15]
mas Ridwan, sy mau tanya apakah memungkinkan bagi pegunjung bisa langsung masuk ke login dashboard tanpa melalui halaman muka "GET YOUR SYSTEM, CMS, E-COMERCE IN ONE TIME!"
Tr ksh,

**Comment by ridwanskaterock** [comment]
bisa mas masuk langsung ke link administrator/login

dan pada baris 33 

`di file application/controllers/Auth.php `

![image](https://cloud.githubusercontent.com/assets/9270445/22493897/9efeffe0-e865-11e6-9206-befe4c8d547d.png)

di rubah menjadi 

`redirect('administrator/dashboard', 'refresh');`

thanks

**Comment by h3ri** [comment]
blm bisa, masih refresh ke halaman muka

**Comment by ridwanskaterock** [comment]
ini udah saya coba mas 

untuk merubah code menjadi seperti ini 

`redirect('administrator/dashboard', 'refresh');
`
dan berhasil
