### ISSUE TITLE
Set up API based on the query from a few data tables with relationships

### ISSUE THREAD

**Issue by vrusua** [ridwanskaterock/cicool#153]
Hi there,

can you please let me know how can I set up API based on the complex query from a few related data tables? 

Thank you.

Cheers,
Ruslan

**Comment by ridwanskaterock** [comment]
you can create join data on the model API and controller like CRUD builder, 

you can generate CRUD and see example you will easy to implement to API file

**Comment by vrusua** [comment]
Thanks for the info, @ridwanskaterock, will try to implement by a such way. 

Cheers.
