### ISSUE TITLE
Message: Cannot modify header information - headers already sent by (output started at ......

### ISSUE THREAD

**Issue by nurzaly** [ridwanskaterock/cicool#154]
Need help about this... 
![capture](https://user-images.githubusercontent.com/11963465/35837201-6b1eff44-0b1f-11e8-8c72-730381141015.PNG)

**Comment by ridwanskaterock** [comment]
you can try comment this code (disable)

![image](https://user-images.githubusercontent.com/9270445/35843912-632f5572-0b3d-11e8-8854-21691f45f15a.png)

on debugBar/PhpHttpDriver.php

**Comment by nurzaly** [comment]
thanks
