### ISSUE TITLE
Blocking bug, add new crud AND add new rest

### ISSUE THREAD

**Issue by fliot** [ridwanskaterock/cicool#156]
Not working at all with php7.1 and php7.2 (can you confirm it's by design, and if yes, have you planned some correction)
Working with 7.0, but, I got a blocking bug,
Clicking on "CRUD Builder" > "Add new Crud" or clicking "API Builder" > "Add new REST" I have some dead unworking screens.
https://ibb.co/k2T2ax
https://ibb.co/fzqR2c
As a result, it's completelly impossible to use...
Please help.

**Comment by ridwanskaterock** [comment]
Hii.

Yes for curren this cide not working on php version >=7.1

But this code working on PHP version 7.0

I will do the update plan to fix this thanks

Pada tanggal 23 Feb 2018 01:13, "Francois Liot" <notifications@github.com>
menulis:
