### ISSUE TITLE
What is the next step after use API method "/user/login" ?

### ISSUE THREAD

**Issue by carlosanpardo** [ridwanskaterock/cicool#158]
Hello! Im using the API with the Method "/user/login". The process is working for me but what is the next step after receive the data of the API? How can I redirect the user inside the APP now that I have the token and the another variables that this method return?

Thank you for your help.

**Comment by ridwanskaterock** [comment]
you can access all API with the token, you can define token on HEADERS request.
you can read documentation for it thanks

**Comment by carlosanpardo** [comment]
Hello. Yes I understand the API functionality but I need redirect the user to a private section inside the software. I use the API "/user/login" to receive the data but How can send the user to this private section?

I tried with a redirect but the user really is not logged.

Can you give me a cue please? Thank you.

**Comment by ridwanskaterock** [comment]
can you get token and user personal data on your local application db?

**Comment by carlosanpardo** [comment]
Yes, I receive the data using the API. Im using the API with the another functions too but in the case of function "/user/api/" was very hard for me understand how can login the user directly into CICOOL.

My interest is redirect an user from another Website to CICOOL in a private section.

How can login the user automatically? Im try with the API but maybe you know a way to make a login by URL or another way. Take in mind that I have the token of the user.

Thank you

**Comment by ridwanskaterock** [comment]
oh so you want to create a token with the API then go to redirect the site?

for token only in use on API to login to cicool dashboard you need to call this function

`administrator/auth/login`

with body

username and password

administrator/auth/login

but you must change config 
![image](https://user-images.githubusercontent.com/9270445/37580770-0b8630b0-2b78-11e8-9334-f0dae7d33430.png)

`$config['csrf_protection'] = FALSE;`

thanks
