### ISSUE TITLE
Installation keep returning me to wizzard

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#159]
Installation keep returning me to wizzard in localhost and on my VPS
any help?

**Comment by ridwanskaterock** [comment]
for it you can see error log by change application/config/config.php 

error_threshold to 1

![image](https://user-images.githubusercontent.com/9270445/37749587-2f191534-2dbb-11e8-82a0-b1a1c1c01455.png)


thanks

**Comment by dali44** [comment]
Hi, i think its a permission problem,i had the same problem and its resolved just by re-uploading fresh copy with Filezilla

**Comment by cnngraphics** [comment]
Resolved by doing what @dali44 said. New version has the fix.
