### ISSUE TITLE
cara mengedit tampilan content dashboard

### ISSUE THREAD

**Issue by h3ri** [ridwanskaterock/cicool#16]
mas mohon bantuan cara mengubah tampilan content dashboard (ex: gambar icon setting/text crud builder) Trims mas atas petunjuknya.

**Comment by ridwanskaterock** [comment]
untuk asset img bisa di replace di sini mas `asset\img`

kalo untuk halaman landing bisa di rubah di sini 
`
cc-content/themes/cicool/views/home.php`

**Comment by h3ri** [comment]
benar mas, melalui cc-content/themes/cicool/views/home.php kita bisa merubah tampilan muka, nah untuk menyesuaikan content dashboard bisa melalui aplication/views/backend/standar/dashboard.php
Tr ksh mas Ridwan untuk supportnya.
