### ISSUE TITLE
Installation error - Message: Call to undefined function app()

### ISSUE THREAD

**Issue by paulchicago74** [ridwanskaterock/cicool#160]
I am getting the following error during wizard install. How do I install it manually? I tried already to change the $config['log_threshold'] = 1; and it didnt work at all!!
n uncaught Exception was encountered
Type: Error

Message: Call to undefined function app()

Filename: /home/webteste/public_html/crud/cicool/application/views/errors/html/error_general.php

Line Number: 1

Backtrace:

File: /home/webteste/public_html/crud/cicool/application/core/My_Security.php
Line: 14
Function: csrf_verify

File: /home/webteste/public_html/crud/cicool/index.php
Line: 315
Function: require_once

**Comment by ridwanskaterock** [comment]
it happens because there is an error in your application and the error does not display as it should,
to see the error you can send the last log file application/logs/.

and you can following this wiki for see your error message 

https://github.com/ridwanskaterock/cicool/wiki/Change-error-general-issue-on-other-server-autoloading


thanks

**Comment by paulf123b** [comment]
I have the same problem. Fresh installation attempt :(

There is nothing in application/logs other than index.html

There is nothing thrown in httpd error_log.

Not sure what the wiki you mentioned... all that seems to do is make the error appear friendlier? "The action you have requested is not allowed."

Product looks great hope don't have to return :(

**Comment by ridwanskaterock** [comment]
what user do you mean, you can check the user on aauth_users can i see / do remote to your server? :) @paulf123b thanks

**Comment by ridwanskaterock** [comment]
still wait for update i just update to version 2.6.3 
![image](https://user-images.githubusercontent.com/9270445/38199939-aca2af38-36bc-11e8-9948-d9568f7b54bc.png)

this update will approved 1 - 2 days

thanks

**Comment by paulf123b** [comment]
Thanks for the update. The only difference is I get a friendlier "The action you have requested is not allowed." at the end of Wizard. Note that page is not even performing validation... it is like csrf is completely broken somehow. If I force disable it I can complete wizard, site allows login but I can do nothing other than change language and it still shows login button instead of actually logged in.

Server is internal only so we would have to arrange remote session if you would be so kind. I am in UTC-5.

Thanks!

**Comment by paulf123b** [comment]
OK more notes.... I setup XAMPP on Windows to test instead. PHP Version 7.2.3. Now there is a separate issue here... mcrypt is now deprecated (apparently codeignitor can fallback to openssl?) so I disabled mcrypt checks in the wizard, don't know if this will break anything else but at least I can see what cicool is awesome!

But now to deal with what the problem could be on production box :(  I thought maybe there was a problem with sessions path but I tested and sessions = OK. Hope we can remote session soon!

thanks

**Comment by paulf123b** [comment]
I got it working now but I don't know how. What I did is run wizard, get to end with error then disable write permission to config.php then wizard again and it works !?! I repeated several times. What's the deal?

Also the minor thing I mentioned.... for email address/username it is not accepting "_" character in email which should be allowed... nothing wrong with foo_bar@test.com but it will not take that = invalid username.

**Comment by ridwanskaterock** [comment]
for invalid username issue it seems the issue karna aauth can not accept characters other than alphanumeric for username trimakasih for your input.

for wizzard do you see application/config/site.php file? and the database is well made?

**Comment by paulf123b** [comment]
Hi. Wizard completes yes and site.php is created + database. Very strange. Like I said to get this to work the solution is to disable write to config.php?

But now I have an even bigger problem. I have tried this on same server as above, XAMPP with PHP 5.x, XAMPP with PHP 7.x and the same problem. Maybe I should make a different topic for this issue? The problem now is page builder is does not work.... pages are blank, preview stalls... basically nothing works. Again this is 3 different environments I confirm this in. Your online demo works though.

When can we do a remote session? 

Thanks so much!

**Comment by ridwanskaterock** [comment]
can you try first page builder by disabling xss_global_filtering to false
on config/config.php

Thanks

Pada tanggal Sel, 3 Apr 2018 21:35, paulf123b <notifications@github.com>
menulis:

**Comment by paulf123b** [comment]
Yes now it works thanks! I believe now also CI current version recommendation is that this is OFF anyway correct?

But now another bug for you lol... bulk delete pages does not work... unhandled exception. This happens even on your own demo site.

OK so do you want to troubleshoot why Wizard has a problem requiring write disabling config.php to finish?

**Comment by paulf123b** [comment]
Also do you prefer that I make a separate post for each problem?

Next problem is this: Page Builder >  Page Designer > Component = EMPTY 

Also a question... how do you place a form in page builder not just contact form?

thx

**Comment by paulf123b** [comment]
RE: Next problem is this: Page Builder > Page Designer > Component = EMPTY >>> I think it is just that an element is required first.

Bug = you cannot change any forms once created! This is even on your DEMO site a problem. Errors.

**Comment by paulf123b** [comment]
Your product has great potential and you have put a huge amount of work into this. However due to show-stopping bugs the product can only be considered in Alpha status. If you make direct contact with me I will help work with you but if not I have to request a refund. Thx

**Comment by ridwanskaterock** [comment]
Yes for form component i just inactive since old version.
For embed form on page builder you can see documentation or see my youtube
channel search cicool.



Pada tanggal Rab, 4 Apr 2018 22:37, paulf123b <notifications@github.com>
menulis:

**Comment by ridwanskaterock** [comment]
If you have an question or have discuss with me you can send me an email
ridwanskaterocks@gmail.com

Thanks

Pada tanggal Rab, 4 Apr 2018 23:12, Muhamad Ridwan <
ridwanskaterocks@gmail.com> menulis:

**Comment by paulchicago74** [comment]
Regarding to my error. I have changed folder permission to write and worked fine, I havent tested the other functionalities.
