### ISSUE TITLE
Hasil CRUD, upload berhasil, download/view selalu 102 bytes

### ISSUE THREAD

**Issue by rumytaulu** [ridwanskaterock/cicool#161]
Saya membuat CRUD dengan fitur upload file, tidak ada masalah dengan upload, file yang ter-upload selalu benar sizenya, sudah dicek di upload directory. Tapi saat download file selalu terpotong menjadi 102 bytes (bahkan saat hendak download sizenya sudah di-announce/diberitahukan sebesar 102 bytes). Ada setting yang mungkin saya lupakan dan perlu diubah? Mohon sarannya.

**Comment by ridwanskaterock** [comment]
saat download 102 bytes itu saat mendownload file apa ya ? 

kalau langsung mengakses file dengan url misal uploads/blog/namafile.jpg bisa kah ? 
thanks

**Comment by rumytaulu** [comment]
Berikut screenshot file saat akan di download dari CRUD view, dan file aslinya di upload directory :

![screenshot from 2018-03-26 11-44-48](https://user-images.githubusercontent.com/14027018/37886128-980c99fc-30eb-11e8-801c-b27ea1e5fb29.png)
![screenshot from 2018-03-26 11-47-04](https://user-images.githubusercontent.com/14027018/37886135-a2bfb0be-30eb-11e8-9f3c-8b96debff8b1.png)

**Comment by rumytaulu** [comment]
FYI ... mengakses langsung dari URL bisa.
Ada saran apa yang harus saya ubah atau ganti?

![screenshot from 2018-03-26 11-52-31](https://user-images.githubusercontent.com/14027018/37886224-48191758-30ec-11e8-9b9d-7c177e71e434.png)

**Comment by ridwanskaterock** [comment]
di  hasil crud list  misal blog_list.php rubah url link seperti yang di lampirkan di atas 

trimakasih

**Comment by rumytaulu** [comment]
Yup. bisa diatasi dengan mengganti "administrator/file/download" dengan "upload"
Terima kasih.
