### ISSUE TITLE
session

### ISSUE THREAD

**Issue by ibnufajar727** [ridwanskaterock/cicool#165]
slamat siang mas, saya inngin buat  data di dashboard itu tampil sesuai session pengguna, tetapi kenapa selalu gagal ya, saya sudah coba gunakan if allowed, dan get user group / get user data juga gak bisa, mohon petunjuk untuk mengatasi masalah ini, terimakasih

**Comment by ridwanskaterock** [comment]
maksudnya dashboard yang di tampil spesifik user mas @ibnufajar727 ?

**Comment by ibnufajar727** [comment]
Ya

Pada tanggal Sab, 21 Apr 2018 09.05, Muhamad Ridwan <
notifications@github.com> menulis:

**Comment by ridwanskaterock** [comment]
Untuk menampilkan data spesifik user versi terakhir sudah bisa menggunakan type current user id
