### ISSUE TITLE
Disable primary key - problem with view

### ISSUE THREAD

**Issue by akuljana** [ridwanskaterock/cicool#166]
I'm trying to add view in crud but can't do because **The Primary Key of Table field is required.**
How to disable or add table/view without primary key?

**Comment by ridwanskaterock** [comment]
you can remove it on crud controller.

![image](https://user-images.githubusercontent.com/9270445/38737410-4c77d80e-3f59-11e8-93d6-3b7107947733.png)

but you will get some error or you must customize some code, and uncheck feature delete on crud 

thanks
