### ISSUE TITLE
Filter in search 

### ISSUE THREAD

**Issue by alejf** [ridwanskaterock/cicool#169]
Hello, when i have others fields for join, how can i get this filter?, because only show te fields of the table of the query but i need to search with other fields when i add the join

**Comment by ridwanskaterock** [comment]
for example i have blog module join with category 

on model_blog.php you can fill in array other field 

![gambar](https://user-images.githubusercontent.com/9270445/39799254-d4c867a8-538d-11e8-9da6-e0aae52ca002.png)


if you need to add field on dropdown you can add on blog_list.php 

![gambar](https://user-images.githubusercontent.com/9270445/39799294-f35a8c1e-538d-11e8-9fcc-c18f3d09f30f.png)
