### ISSUE TITLE
Warning about mcrypt

### ISSUE THREAD

**Issue by jay1davis** [ridwanskaterock/cicool#17]
I'm getting a warning about mcrypt on the first setup page and I can't go any further. Is there a specific version I need?

Thanks!
I have it installed:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
php5-mcrypt is already the newest version.
The following packages were automatically installed and are no longer required:
  g++-4.7 gcj-4.7-base gcj-4.7-jre-lib libantlr-java
  libbackport-util-concurrent-java libcommons-collections-java
  libcommons-jexl-java libcommons-validator-java libdoxia-sitetools-java
  libev4 libgcj13 libgd2-xpm libgoogle-collections-java libhdb9-heimdal
  libjaxme-java libjtidy-java libkdc2-heimdal libllvm3.1:i386
  libmaven-plugin-tools-java libmaven-reporting-impl-java libmpc2
  libnekohtml-java libneon27-gnutls libntdb1 libpango1.0-0
  libplexus-velocity-java libpthread-stubs0 libserf1 libstdc++6-4.7-dev
  libv8-3.8.9.20 libwerken.xpath-java python-ntdb sgml-base velocity
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.

![screen shot 2017-02-01 at 9 55 24 pm](https://cloud.githubusercontent.com/assets/2054415/22535526/b1ffd290-e8c9-11e6-9849-c4f3c84a9490.png)

**Comment by jay1davis** [comment]
In case anyone else runs into this problem, I was able to solve it by adding **extension=mcrypt.so** to my /etc/php5/apache2/php.ini file.

**Comment by ridwanskaterock** [comment]
Okay

I'm glad you could finish well

I wait for the best reviews of your

thanks

**Comment by cnngraphics** [comment]
What is the solution for PHP 7?
This ectension is deprectaed in PHP 7... NAy help?

**Comment by ridwanskaterock** [comment]
for PHP 7.1 is ok i have tested on php 7.1

**Comment by cnngraphics** [comment]
Here http://www.ksldemo.com/wizzard/setup/1
I have both PHP 5.6 and PHP 7x
Still having installation issues

**Comment by cnngraphics** [comment]
I fixed using this info
https://github.com/ridwanskaterock/cicool/issues/202#issuecomment-403188513
Continuing with installation

**Comment by cnngraphics** [comment]
New Issue Now:
![image](https://user-images.githubusercontent.com/1514378/45276973-50960000-b493-11e8-928d-a31853e8aed1.png)
