### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by yothin** [ridwanskaterock/cicool#170]
I was successfully login to dashboard but when click any menus away return to login page.

I've config
- $config['log_threshold'] = 4;
- define('ENVIRONMENT', 'development');

And this is log message
`INFO - 2018-05-13 03:36:43 --> Config Class Initialized
INFO - 2018-05-13 03:36:43 --> Hooks Class Initialized
DEBUG - 2018-05-13 03:36:43 --> UTF-8 Support Enabled
INFO - 2018-05-13 03:36:43 --> Utf8 Class Initialized
INFO - 2018-05-13 03:36:43 --> URI Class Initialized
INFO - 2018-05-13 03:36:43 --> Router Class Initialized
INFO - 2018-05-13 03:36:43 --> Output Class Initialized
INFO - 2018-05-13 03:36:43 --> Security Class Initialized
DEBUG - 2018-05-13 03:36:43 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-05-13 03:36:43 --> CSRF cookie sent
INFO - 2018-05-13 03:36:43 --> Input Class Initialized
INFO - 2018-05-13 03:36:43 --> Language Class Initialized
INFO - 2018-05-13 03:36:43 --> Loader Class Initialized
INFO - 2018-05-13 03:36:43 --> Helper loaded: url_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: app_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: form_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: security_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: download_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: captcha_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: language_helper
INFO - 2018-05-13 03:36:43 --> Language file loaded: language/english/web_lang.php
INFO - 2018-05-13 03:36:43 --> Parser Class Initialized
INFO - 2018-05-13 03:36:43 --> User Agent Class Initialized
DEBUG - 2018-05-13 03:36:43 --> Template Class Initialized
INFO - 2018-05-13 03:36:43 --> Form Validation Class Initialized
INFO - 2018-05-13 03:36:43 --> Controller Class Initialized
INFO - 2018-05-13 03:36:43 --> Helper loaded: cookie_helper
INFO - 2018-05-13 03:36:43 --> Database Driver Class Initialized
INFO - 2018-05-13 10:36:43 --> Helper loaded: directory_helper
INFO - 2018-05-13 10:36:43 --> Session: Class initialized using 'database' driver.
INFO - 2018-05-13 10:36:43 --> Language file loaded: language/english/aauth_lang.php
DEBUG - 2018-05-13 10:36:43 --> Config file loaded: /xxx/application/config/aauth.php
INFO - 2018-05-13 10:36:43 --> Database Driver Class Initialized
DEBUG - 2018-05-13 10:36:43 --> Cc_app class already loaded. Second attempt ignored.
INFO - 2018-05-13 10:36:43 --> Model Class Initialized
INFO - 2018-05-13 03:36:43 --> Config Class Initialized
INFO - 2018-05-13 03:36:43 --> Hooks Class Initialized
DEBUG - 2018-05-13 03:36:43 --> UTF-8 Support Enabled
INFO - 2018-05-13 03:36:43 --> Utf8 Class Initialized
INFO - 2018-05-13 03:36:43 --> URI Class Initialized
INFO - 2018-05-13 03:36:43 --> Router Class Initialized
INFO - 2018-05-13 03:36:43 --> Output Class Initialized
INFO - 2018-05-13 03:36:43 --> Security Class Initialized
DEBUG - 2018-05-13 03:36:43 --> Global POST, GET and COOKIE data sanitized
INFO - 2018-05-13 03:36:43 --> CSRF cookie sent
INFO - 2018-05-13 03:36:43 --> Input Class Initialized
INFO - 2018-05-13 03:36:43 --> Language Class Initialized
INFO - 2018-05-13 03:36:43 --> Loader Class Initialized
INFO - 2018-05-13 03:36:43 --> Helper loaded: url_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: app_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: form_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: security_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: download_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: captcha_helper
INFO - 2018-05-13 03:36:43 --> Helper loaded: language_helper
INFO - 2018-05-13 03:36:43 --> Language file loaded: language/english/web_lang.php
INFO - 2018-05-13 03:36:43 --> Parser Class Initialized
INFO - 2018-05-13 03:36:43 --> User Agent Class Initialized
DEBUG - 2018-05-13 03:36:43 --> Template Class Initialized
INFO - 2018-05-13 03:36:43 --> Form Validation Class Initialized
INFO - 2018-05-13 03:36:43 --> Controller Class Initialized
INFO - 2018-05-13 03:36:43 --> Helper loaded: cookie_helper
INFO - 2018-05-13 03:36:43 --> Database Driver Class Initialized
INFO - 2018-05-13 10:36:43 --> Helper loaded: directory_helper
INFO - 2018-05-13 10:36:43 --> Session: Class initialized using 'database' driver.
INFO - 2018-05-13 10:36:43 --> Language file loaded: language/english/aauth_lang.php
DEBUG - 2018-05-13 10:36:43 --> Config file loaded: /xxx/application/config/aauth.php
INFO - 2018-05-13 10:36:43 --> Database Driver Class Initialized
DEBUG - 2018-05-13 10:36:43 --> Cc_app class already loaded. Second attempt ignored.
DEBUG - 2018-05-13 10:36:43 --> Config file loaded: /xxx/app/application/config/site.php
INFO - 2018-05-13 10:36:43 --> Helper loaded: inflector_helper
DEBUG - 2018-05-13 10:36:43 --> Cc_app class already loaded. Second attempt ignored.
INFO - 2018-05-13 10:36:43 --> File loaded: /xxxl/app/application/views/backend/standart/administrator/login.php
INFO - 2018-05-13 10:36:43 --> Final output sent to browser
DEBUG - 2018-05-13 10:36:43 --> Total execution time: 0.0054`

Please help me to resolve this issue.

**Comment by ridwanskaterock** [comment]
i see no error log for that, 

can you explain, what you use anothor group / user roles ?

**Comment by scaleto** [comment]
I have the same problem but only with Google Chrome. I think the problem is a server configuration problem, because im using CloudWays with host from DigitalOcean and the error is present. But i upload the files to GoDaddy and CiCool works with no problem.
But the truth is that I would like to know how to solve the problem.
Thanks.

**Comment by scaleto** [comment]
I think i found the problem. Just disable HTTP/2 on your web server, and its done.

**Comment by ridwanskaterock** [comment]
Thanks good work, nice, i'll close this issue

**Comment by scaleto** [comment]
Sorry but the fix did not work.

**Comment by scaleto** [comment]
I cant fix the problem and change to GoDaddy. CiCool works very good.
