### ISSUE TITLE
Language parameter

### ISSUE THREAD

**Issue by wancode** [ridwanskaterock/cicool#171]
As you can see, I can access the link.

![screenshot](https://user-images.githubusercontent.com/38166045/39981909-4330f0a4-575b-11e8-8360-0fcfa383cc3e.PNG)

But, why does not it come up with different content, how can I adjust it?

**Comment by ridwanskaterock** [comment]
Oh for different content by lang can't avaiable for current version, 

lang only for system language

why you not add field lang on table blog ? 

and add filter for API 

$this->db->where('lang', $this->input->get('lang'));

**Comment by wancode** [comment]
I think we can do this if we can select the language with selectbox even if we create the kernel.

**Comment by ridwanskaterock** [comment]
yes you can do it by clue from me, 

and you can make select input by foreach this function get_langs() and create filter on db

**Comment by wancode** [comment]
I guess this is going to be a little difficult, do you have a sample?

**Comment by wancode** [comment]
Any progress?

**Comment by wancode** [comment]
Any progress?

**Comment by wancode** [comment]
>$this->db->where('lang', $this->input->get('lang')); 

Where should I add this?

**Comment by ridwanskaterock** [comment]
you can add this code on model 

example application/models/Model_blog.php

**Comment by wancode** [comment]
I added but it is not.

![qq](https://user-images.githubusercontent.com/38166045/42096456-0c93fde8-7bbe-11e8-99af-7907aa66db5a.PNG)

That's the URL
>api/blog/detail?X-Api-Key=api&id=title&lang=se


This is the error I get

`{"status":false,"message":"
Unable to load the requested language file: language\/se\/web_lang.php<\/p>"}`


What I want to do is to call different content with the tag "lang", even if "title" or "id"

**Comment by ridwanskaterock** [comment]
for that you must create language on folder 
application/language_name/all filtes language see other folder
example application/language/se/

**Comment by wancode** [comment]
Same again [file](https://gist.github.com/wancode/6f5429f1a790a77364863b0cc54f3d52)
