### ISSUE TITLE
Captcha and User Profile Icon/Image

### ISSUE THREAD

**Issue by rumytaulu** [ridwanskaterock/cicool#174]
Two question/problem

1. Captcha for user registration doesn't view image or whatever it is
2. Can't upload user profile image, what's the limit size for the image?

BTW ... I am using the latest version of Cicool

[Indonesian]
Dua pertanyaan/masalah

1. Captcha untuk pendaftaran user baru tidak jadi.
2. Tidak bisa upload foto/image untuk user profile, berapa ukuran besar file yang diperkenankan?

Saya menggunakan versi Cicool yang terakhir

![screenshot from 2018-05-19 09-21-12](https://user-images.githubusercontent.com/14027018/40263571-0153e458-5b47-11e8-95c1-43320271427c.png)

![screenshot from 2018-05-19 09-23-09](https://user-images.githubusercontent.com/14027018/40263573-0e3a94a0-5b47-11e8-9929-35b89ba871c2.png)

**Comment by ridwanskaterock** [comment]
Hi.
1. Make sure the captcha folder has permissions that can be written,
2. to upload image can you see XHR response in browser.
and make sure also the uploads folder is in writeable mode

**Comment by rumytaulu** [comment]
It worked.

Giving 777 permission to captcha and uploads folder solved the issue.
Thanks for the fast respond Ridwan.
