### ISSUE TITLE
BUG: Cannot create and edit new page in localhost

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#176]
When I try to create a page in localhot, the edit page does not work. Pages is not saved. When it fi ally saves, the cursor or mouse pointer keeps shaking, trembling ... looks like there is an infinite loop. Lots or error in dev console... nonstop errors

**Comment by ridwanskaterock** [comment]
can you send me and screenshoot or screencam ? 
i will checking for that, if you use firefox that's is work ? 

you can also give me console screen or XHR response 

Thanks

**Comment by cnngraphics** [comment]
I tried to install on my LAMP system an All works fine. But in localhost (on my local pc) running XAMP), same issue. I will send screencast later today and console log. Thanks

**Comment by cnngraphics** [comment]
Here is a recorded video of the issue with creating page. This time there is no console error, but you can see the mouse pointer keep vibrating and the drag and drop feature is not working to allow me to create a page.
If you want I can send you a login and password so you can test on my server.

<iframe title="YouTube video player" class="youtube-player" type="text/html" width="640" height="385" src="http://www.youtube.com/embed/3fl15OWVYuU?autoplay=1" frameborder="0" allowFullScreen></iframe>

**Comment by cnngraphics** [comment]
I found that the edit page ONLY work if you click on save, not "save and go to list"
This is definitely a bug to be fixed.

**Comment by ridwanskaterock** [comment]
you use latest code of cicool ? 

what you have an error when try it on cicool demo ? 

i will check again 

Thanks
