### ISSUE TITLE
ACF integration

### ISSUE THREAD

**Issue by juanrgrajales** [ridwanskaterock/cicool#178]
Hi Ridwand can you point me in the right direction, I need to create a dashboard to be able to remotely modify ACF fields in a WordPress installation. Do I need to create a CRUD and then use the Wordpress REST API to integrate each endpoint from the ACF fieds to the ciccol. 

Thank you so much Ridwand. I purchased your product through my wifes email hannahl...@gmail in codecayon.

**Comment by ridwanskaterock** [comment]
yes for that you can manage data with CRUD and integrate it with API,
for data that can be insert to cicool system you can make REST API,
and to access ACF you can use PHP curl

if you have problem you can place your code on this issue 

Thanks
