### ISSUE TITLE
User detail API

### ISSUE THREAD

**Issue by safalshrestha** [ridwanskaterock/cicool#179]
Hi, I am trying to get the user details after login for all the users. Currently only admin's profile is available with API. Would you be able to tell me which permission do I need to enable to allow different user groups(Members on my case) to be accessible via the API.

Current Error:
{
"status": false,
"message": "You are not allowed to access."
}

**Comment by safalshrestha** [comment]
Hi, 
I got that to work. I had edited the question for another issue.

Is it possible to allow other user groups to access API and limit only certain API, for example only give access get and update but not delete?

Thanks.

**Comment by ridwanskaterock** [comment]
yes you can manage access on example.com/administrator/access

**Comment by safalshrestha** [comment]
I just encountered another issue if you can help me with.

I changed the registration form to suit my app. However I am having problem with [Agree] checkbox. 

If I create two boxes like the image attached:
<img width="475" alt="screen shot 2018-05-28 at 14 32 08" src="https://user-images.githubusercontent.com/1096260/40616725-f661d0d4-6283-11e8-9d66-c06d3133c834.png">

by breaking and creating a same div:
`<div class="form-group has-feedback">
        <label>Category <span class="required">*</span> </label>
        <select  class="form-control chosen chosen-select-deselect" name="category" id="category" data-placeholder="Select Category" >
            <option value=""></option>
            <?php foreach (db_get_all_data('business_categories') as $row): ?>
            <option value="<?= $row->id ?>"><?= $row->name; ?></option>
            <?php endforeach; ?>
        </select>
      </div>
    </div>
    

    <br> <br>
    <div class="login-box-body">
      <p class="login-box-msg"> Your Details: </p>
      <div class="form-group has-feedback <?= form_error('full_name') ? 'has-error' :''; ?>">
        <label>Full Name </label>
        <input class="form-control" placeholder="Full Name" name="full_name" value="<?= set_value('full_name'); ?>">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>`

The agree checkbox doesn't seem to work. Even if I click on agree, I get form validation error saying agree hasn't been clicked.
<img width="255" alt="screen shot 2018-05-28 at 14 34 32" src="https://user-images.githubusercontent.com/1096260/40616829-42d7fc72-6284-11e8-8a86-1b7e17e2d5b6.png">

Thanks.

**Comment by cnngraphics** [comment]
Hi @safalshrestha 
Did you manage to add a database field for the checkbox and update your user model to check this checkbox validation rules?

See this URL regarding form validaiton:
https://codeigniter.com/user_guide/libraries/form_validation.html?highlight=form%20validation#form-validation-tutorial

Basically you need three or four steps to validate a field:

1. the field name in your HTML
2. the controller with 
`$this->form_validation->set_rules('agree', 'I agree with terms', 'required');`
3- The model that will take care of updating database

To me it looks like your form has the checkbox, but you do not take care of it in your controller and your model

**Comment by ridwanskaterock** [comment]
Thanks for help answered some question Great! @cnngraphics
