### ISSUE TITLE
The requested URL /wizzard/setup was not found on this server.

### ISSUE THREAD

**Issue by lidernemo** [ridwanskaterock/cicool#18]
i install cicool on http://176.112.211.170/bs

on lamp stack
https://bitnami.com/stack/lamp/installer
https://bitnami.com/redirect/to/141354/bitnami-lampstack-5.6.30-0-linux-x64-installer.run

and have error "The requested URL /wizzard/setup was not found on this server."

my phpinfo http://176.112.211.170/phpinfo.php

**Comment by ridwanskaterock** [comment]
hii, 

please check your installation folder

maybe this issue some like this https://github.com/ridwanskaterock/cicool/issues/1

thanks

**Comment by lidernemo** [comment]
my install folder ok
#1 not worked

**Comment by ridwanskaterock** [comment]
please send us a screenshot,

because our application we've tried on multiple OS,

such as Windows, Linux and OS X, and it goes well

on nginx and apache

showing a structure can be in the installation folder that you created?

and do you also enable rewrite module?

thanks

**Comment by ridwanskaterock** [comment]
i will close this issue thanks
