### ISSUE TITLE
Select2 doesnt work on mobile

### ISSUE THREAD

**Issue by axixu** [ridwanskaterock/cicool#180]
auto complete select2 doesnt work on mobile, please help..

**on mobile:**
![photo6071111344809158817 1](https://user-images.githubusercontent.com/28151183/40530400-d4c35a82-6022-11e8-85d9-f3e8fe97af42.jpg)

**on web:**
![onmobile](https://user-images.githubusercontent.com/28151183/40530439-02ca1560-6023-11e8-9100-56729b8e53fc.png)

**Comment by ridwanskaterock** [comment]
yes because this library doesnot support for phone and tablet 

https://stackoverflow.com/questions/22016578/chosen-plugin-doesnt-seem-to-work-on-mobile-browsers
https://github.com/harvesthq/chosen/pull/1388

Thanks

**Comment by axixu** [comment]
OMG that was 2014!

Please update it to other working library, such as select2, etc..  Thanks.

**Comment by ridwanskaterock** [comment]
Yes actually I've talked about this a long time if viewed from the discussion indeed they do not want the look of mobile and tablet
I will look for the solution whether there is another way now or change the last option library

Thanks

**Comment by axixu** [comment]
I've found a quick fix solution.

https://realize.be/blog/mobile-support-chosen

Thank you for good respon.
