### ISSUE TITLE
Api Access's methods, And other features.

### ISSUE THREAD

**Issue by wancode** [ridwanskaterock/cicool#181]
Hello, 

Please add next update "Access's methods. (GET,POST,DELETE)" 

And please add log information. Example

Host | Url | Params | UserAgent | Datetime
-- | -- | -- | -- | --
::1 | /api/blog | id=5; | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 | 2018-05-26 23:41:27

Create a special API key for the created API, And manage features. (GET,POST,DELETE)

**Comment by ridwanskaterock** [comment]
Thank i will make it for next features, 

for now that's possible, for change METHOD on API by change function name ex : 

delete_get to delete_delete 

Thanks
