### ISSUE TITLE
Cannot install Cicool

### ISSUE THREAD

**Issue by kj79** [ridwanskaterock/cicool#182]
Hi I just purchased Cicool and followed the instruction to unzip and upload Cicool folder but when I try to install I cannot do this as it cannot find the wizzard/language folder. Do I need to download this folder from somewhere? My URL is
www.factory2010.co.uk/ciccol

**Comment by ridwanskaterock** [comment]
if you can access this URL http://factory2010.co.uk/cicool/index.php/wizzard/language 

you can enable mod_rewrite on your server

**Comment by kj79** [comment]
Hi,
Yes can access the url and see that English language has been selected but when I click on next I  get a blank page. I have checked  mod-Rewrite and it is activated

Mod_rewrite is activated!

Please advise how I van complete install

**Comment by kj79** [comment]
I think I have managed to get past the issue and I can see the database has been installed but when I enter the url factory2010.co.uk/cicool/ I get to the same page showing English language. I did notice that I had a strange page after entering DB details how do I check that the wizard is complete?

**Comment by kj79** [comment]
Ok so I cleared the tables created in the DB and ran the setup again and got a database connection error. Please see attached
![db connection error](https://user-images.githubusercontent.com/39707567/40836894-5cd9cd26-6590-11e8-8559-9d079e3aa15e.jpg)

**Comment by ridwanskaterock** [comment]
this message show because invalid database config,

you can try by fill hostname to localhost ?

2018-06-01 17:39 GMT+07:00 kj79 <notifications@github.com>:

**Comment by kj79** [comment]
Ok so now no matter what I put I get the following error

An Error Was Encountered
The action you have requested is not allowed.

This is taking too long to resolve. Can I get a refund?

**Comment by kj79** [comment]
I have checked the database setting with 1 & 1 support and there is nothing wrong with the connection.

**Comment by kj79** [comment]
Hi,
Firstly am disappointed as you did not reply. I finally managed to get the app working. I have created a form in form builder but how do I connect the form to the database?

**Comment by ridwanskaterock** [comment]
yes you can do that on controll module administrator / access

**Comment by kj79** [comment]
I am sorry I do not understand your response. I have also created a CRUD is it possible to do multiple entries or can I import from spreadsheet?

**Comment by ridwanskaterock** [comment]
for now you can custom custom to like that, because there is no feature for it 
thanks

**Comment by kj79** [comment]
Hi,
I had the system working fine but today I getting page not found error when I click on dashboard after logging in. Any thoughts on how I can clear this issue?

**Comment by kj79** [comment]
Hi I managed to clear the issue I had previously but now after creating a CRUD when I click on see I get the following error
Undefined property: stdClass::$order

How do I clear this error?

**Comment by ridwanskaterock** [comment]
can you share to me for error code ?

**Comment by kj79** [comment]
After creating the CRUD form when I click see I get

![image](https://user-images.githubusercontent.com/39707567/41794229-9c35890c-7656-11e8-8c0a-d302d56b4a12.png)

**Comment by ridwanskaterock** [comment]
hi Can you check this file and line 
![image](https://user-images.githubusercontent.com/9270445/41807527-0834d2ea-76fa-11e8-947f-d989df28ffae.png)

Thanks

**Comment by johnfelipe** [comment]
> Hi,
> Firstly am disappointed as you did not reply. I finally managed to get the app working. I have created a form in form builder but how do I connect the form to the database?

can u tell me your steps for install correctly i have nginx not apache

**Comment by cnngraphics** [comment]
Hi Felipe, if you create a form, it already generates the database table
for you to start pushing data...
Go to form list and you should see an icon to add record and view records

**Comment by johnfelipe** [comment]
@cnngraphics i cant installed yet

**Comment by jpapan** [comment]
How did you managed to install it? I keep on taking a "An Error Was Encountered
The action you have requested is not allowed." error when I press the button on the installation wizard after database credentials wizard page.

**Comment by mangesh-sutar** [comment]
@ridwanskaterock How can we integrate this Cicool tool with the existing Codeignitor project/application?
