### ISSUE TITLE
REST API LOGIN authentication - tm

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#183]
Hi, 
How can I login from rest API using POSTMAN or any HTTP request from an app?
What is the end point for login
What are the parameters ?
How do I login securely and get a session token?

Finally, how can I just use postMan to test API connections and endpoint
Please advise....

**Comment by ridwanskaterock** [comment]
for Get token you can read Web Documentation And API Documentation 

http://cicool.heriver.com/administrator/doc/web
http://cicool.heriver.com/administrator/doc/api
Thanks

**Comment by ridwanskaterock** [comment]
ENDPOINT ex : example.com/api/

for get token example.com/api//user/request_token

WIth body and headrs like documentation

**Comment by cnngraphics** [comment]
Thanks @ridwanskaterock 

I have been able to get a token. 
Hwever, when I decoede the token with jwt.io 
I do not see any user information. How Can I pass user data in the token so I know who is authenticated? OR
Do I call another API endpoint to get the user data? (Looks like it) ... Please advise!

**Comment by ridwanskaterock** [comment]
for example you can see api user profile for that 

![image](https://user-images.githubusercontent.com/9270445/40831684-ddc9a37a-65b3-11e8-9ca9-ec35494fb5c9.png)


@cnngraphics

**Comment by cnngraphics** [comment]
Awesome, thanks!
