### ISSUE TITLE
Lat and Long  from address field

### ISSUE THREAD

**Issue by dircobuddy** [ridwanskaterock/cicool#185]
Is it possible to get the lat and long from the address field when submitting in crud ?

**Comment by ridwanskaterock** [comment]
yes you can do it you can create field lat and lon and setup js address like demo 

https://github.com/bygiro/jQuery-AddressPicker-ByGiro

You can check demo by download that library and see demo folder

**Comment by dircobuddy** [comment]
Thank you how do i incorporate it into codeigniter ?

**Comment by ridwanskaterock** [comment]
you just edit on the crud results like blog_add.php and you can customize it like in the example demo
