### ISSUE TITLE
Change label to inputs

### ISSUE THREAD

**Issue by neutronixx** [ridwanskaterock/cicool#187]
Hello, how I can change the la bel to each input in crud generator?

Thanks

**Comment by ridwanskaterock** [comment]
Hii..
yes you can change label for each input, just click label and tping what you need 
![image](https://user-images.githubusercontent.com/9270445/41018721-779198a8-6985-11e8-94aa-bfd04664859d.png)

**Comment by neutronixx** [comment]
Ok, than  you very much.!

**Comment by ridwanskaterock** [comment]
fine, you're welcome

**Comment by neutronixx** [comment]
Hello, I have one more question:

How we can create a custom access to our cliente to see only Cruds that we
have created for their administration

We don't want that they see cruds and forms creator =)

Thanks!

**Comment by ridwanskaterock** [comment]
yes you can do that on controll module example.com/administrator/access

you can set group just only view edit and other

**Comment by neutronixx** [comment]
Thanks, how we can disable splash pahe and after login redirect to dashboard?
