### ISSUE TITLE
SAAS FUNCTIONALITY

### ISSUE THREAD

**Issue by indrabhusan** [ridwanskaterock/cicool#188]
CAN I PROVIDE SAAS FUNCTIONALITY TO MY SITE USERS WHERE THEY CAN CREATE ANY FORM AND USE THAT FORM IN THEIR SITE BY EMBEDDING OR VIA ANY OTHER MEANS. PLEASE LET ME KNOW ABOUT IT...

**Comment by ridwanskaterock** [comment]
yes it can create a form on the backend and you can set the permissions,
for the user can see only the form he himself must you custom with the
filter current user id

2018-06-08 13:25 GMT+07:00 indrabhusan <notifications@github.com>:
