### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by safalshrestha** [ridwanskaterock/cicool#189]
Hi,

Just some question regarding API. The API returns File URL in this format for me:

http:\/\/localhost:8888\/twsapp\/uploads\/charity_details\/

Is this a bug? Should it just be?

http://localhost:8888/twsapp/uploads/charity_details/

Another question is with regards to debugbar code that is generated with API in development mode. How can I remove that staying in development mode and not changing to production mode?

Thank you.

<img width="1086" alt="screen shot 2018-06-08 at 13 57 17" src="https://user-images.githubusercontent.com/1096260/41159280-e4aa816c-6b23-11e8-9e14-eb1d17fcc462.png">

**Comment by ridwanskaterock** [comment]
yes is a litle bug for development 

for now you can set profiler to false 

![image](https://user-images.githubusercontent.com/9270445/41163389-b88bf810-6b62-11e8-8d97-e16b6df66117.png)

on `application/core/My_Controller.php `

**Comment by ridwanskaterock** [comment]
i just replace code like that 
![image](https://user-images.githubusercontent.com/9270445/41163599-529e8332-6b63-11e8-82f9-4f954c6a4830.png)

```php
 if (ENVIRONMENT != 'production') {
               if ($this->uri->segment(1) == 'api') {
                    $this->output->enable_profiler(FALSE);
                } else {
                    $this->output->enable_profiler(TRUE);
                }
            } 
```
