### ISSUE TITLE
Invalid User

### ISSUE THREAD

**Issue by jay1davis** [ridwanskaterock/cicool#19]
Now when I hit NEXT on step 3 of the wizard, I immediately get "An Error Was Encountered - Invalid Username". The DB tables were created. I was never ask to login. Again this happens immediately after I hit NEXT. There is no login page or anything else.

**Comment by ridwanskaterock** [comment]
Sorry,

For this version no external libraries are needed in the fox to this problem might be for the next version I will fix this minor


My advice when you are asked to enter a username email to the email make sure it does not contain characters other than alphanumeric

examples of correct email **jay1davis@gmail.com**
examples of incorrect email **jay1_davis.01@gmail.com**

thanks

**Comment by jay1davis** [comment]
Ah ok that was it - I have a period in my email. Thanks

**Comment by ridwanskaterock** [comment]
OK thanks

I waited for the best reviews of your updates in the future :)
