### ISSUE TITLE
Signature verification failed","error"

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#190]
I am using postman to test cicool API
I successfully got a token
I make call to get all blogs API end point... then I get this error:

{"status":false,"message":"Signature verification failed","error":{"classname":"Firebase\\JWT\\SignatureInvalidException"}}

![image](https://user-images.githubusercontent.com/1514378/41222335-95ba4e58-6d34-11e8-9fbb-61261a3c6a44.png)

**Comment by ridwanskaterock** [comment]
is the token that you input is correct?
see the error occurred because of an invalid token
