### ISSUE TITLE
Custom Input Type

### ISSUE THREAD

**Issue by benzon** [ridwanskaterock/cicool#195]
Hi,

How to add custom input type? Timestamp is there but lacking unixtimestamp a hole lot i got to say.

**Comment by ridwanskaterock** [comment]
if you  have generate table with CRUD 
you will have file controller, you can change it ?

**Comment by benzon** [comment]
Okay what controller is all these types located in? if i may ask?

would be nice to know

**Comment by ridwanskaterock** [comment]
controller location in application/coontrollers/administrator
