### ISSUE TITLE
Question: can I use MDB?

### ISSUE THREAD

**Issue by lisaiceland** [ridwanskaterock/cicool#196]
Hi:
Can I use MDB w/ your product?
https://mdbootstrap.com

Plz LMK
Thnx
Lis

**Comment by ridwanskaterock** [comment]
Hi.

Yes you can make like that and you must custom or adjustment for that

Thanks

2018-06-20 22:21 GMT+07:00 Lisaiceland Inc. <notifications@github.com>:

**Comment by ridwanskaterock** [comment]
If you need to change theme you must custom for views or layout 
application\views\backend\standart\main_layout.php
and adjustment for all views and asset

**Comment by lisaiceland** [comment]
Muhamad hi.
Thnx o much for the response. Appreciate it always.

Ok got it. That sounds like more trouble than it's worth ;-)
Suggestion: can you update the tool to generate material design pages as we
develop them in the designer?
I really like the potential of your product. We're using ScriptCase 9 and
custom-coding PHP 5.6, 7 webapps using codeigniter as well and Node and
python apps for our AI and Blockchain.
I'd love to use your tool in a new project if you can integrate materialD
into it. Pl LMK if on your roadmap at all.
Appreciate all the hard work.

Thank You. Bless.
Lis

Regards,

Lisa Kristinardottir (Lis)
Product Owner
Lisaiceland Inc. <http://lisaiceland.com/> | *myai.expert
<http://lisaiceland.com/>* | ClinicalTrials360 <http://lisaiceland.com/>
<http://ClinicalTrials360.com>

   P
*Save a tree! *
*Please let's ALL consider our environmental responsibility *
*before printing. *
*Don't print this e-mail unless it's really necessary.*

*CONFIDENTIALITY NOTICE*

This e-mail is intended only for the addressee named above. It contains
information that is privileged, confidential or otherwise protected from
use and disclosure. If you are not the intended recipient, you are hereby
notified that any review, disclosure, copying, or dissemination of this
transmission or taking of any action in reliance on its contents, or other
use is strictly prohibited.

If you have received this transmission in error, please reply to the sender
listed above immediately and permanently delete this message from your
inbox. Thank You.
