### ISSUE TITLE
Login with username instead of email

### ISSUE THREAD

**Issue by axixu** [ridwanskaterock/cicool#197]
how to do that?

**Comment by ridwanskaterock** [comment]
Hi you can set to true on 

application/config/aauth.php

![image](https://user-images.githubusercontent.com/9270445/42037573-eebab7fe-7b12-11e8-8e40-2e6692eae961.png)

**Comment by axixu** [comment]
Hi the login page still ask email format.

![username_cc](https://user-images.githubusercontent.com/28151183/42067530-d895ad68-7b70-11e8-8f65-37c45ff7fde8.png)

**Comment by ridwanskaterock** [comment]
ohh,
you can change type input to text 
on view views\backend\standart\administrator\login.php
