### ISSUE TITLE
change default controller

### ISSUE THREAD

**Issue by axixu** [ridwanskaterock/cicool#198]
Hi

wanna ask again, I want to change my main domain directly goes to path administrator/login, is it possible? Thx

**Comment by ridwanskaterock** [comment]
Hi 

yes you can change redirect url on controller 
`application/controllers/administrator/Auth.php`
![image](https://user-images.githubusercontent.com/9270445/42131237-17203c5c-7d28-11e8-88bb-58b2c1626e59.png)

**Comment by axixu** [comment]
No, I mean homepage not url redirect after login. For native CI it can be
changed on routes->default controller.

**Comment by ridwanskaterock** [comment]
for it you can change on application/routes/route_landing.php
iam override this route because setting page on backend

**Comment by axixu** [comment]
Oke thx
