### ISSUE TITLE
mcrypt deprecated in 7.1

### ISSUE THREAD

**Issue by lisaiceland** [ridwanskaterock/cicool#199]
Hi:
I just learned from my host:
*****************************************
Since PHP 7.2 the mcrypt extension isn't released anymore since it was deprecated for 7.1

The composer.json file does allow it to be installed with PHP 7.2. An upgrade should be made to the library to move away from mcrypt.
*****************************************
Can you plz update your project to address this issue asa and give us a new update tot the project or tell us simply what changes we need to make to get the project to work in our host environment?

**Comment by cnngraphics** [comment]
Same issue for me

**Comment by ridwanskaterock** [comment]
on latest version required for myrypt but you can change some rule for that to make it's work 
./application/controllers/Wizzard.php
![gambar](https://user-images.githubusercontent.com/9270445/47599817-3b901480-d9e0-11e8-95ec-ac083562f88f.png)
