### ISSUE TITLE
do images have to go into the 'uploads' directory?

### ISSUE THREAD

**Issue by buckr** [ridwanskaterock/cicool#2]
I see that the CRUD builder wants to put all files in your uploads directory.

For example: http://localhost/cicool/uploads/webinv/9956-3.jpg

However, I have over 21,000 images in an existing website and I would prefer not to relocate them all to your uploads directory.

so, is it possible, when adding Input Type of File in CRUD Builder, it could be pointed to another location (like http://localhost/mysite/inventory-photos/9956-3.jpg )?

-buckr

**Comment by ridwanskaterock** [comment]
buckr sorry it was not possible to be moved into your old web of rules to the current version,
maybe in the next updated version will be a feature to set the storage location of files,
thanks

**Comment by ridwanskaterock** [comment]
but you can set it manually by changing the existing code, thanks

**Comment by buckr** [comment]
thanks.  I will consider changing existing code.

**Comment by ridwanskaterock** [comment]
cicool automatically generate API doc, you can access the documentation on the API  in web application that you created
http://localhost/cicool/apidoc
