### ISSUE TITLE
Page Preiview and Page link not working ..

### ISSUE THREAD

**Issue by puneetkhannaK** [ridwanskaterock/cicool#20]
HI 

Page view and page link not working . showing blank page .. 

![image](https://cloud.githubusercontent.com/assets/25583792/22645521/746e1afa-ec8d-11e6-9f3d-abb7ada21a0e.png)

![image](https://cloud.githubusercontent.com/assets/25583792/22645542/8df54eda-ec8d-11e6-9611-6ace31def4cc.png)

**Comment by ridwanskaterock** [comment]
Oh.

be sure to use page builder

on file
application/config/config.php

exactly on line **425**

global xss filtering with false values
`$config['global_xss_filtering'] = FALSE;`

thanks
