### ISSUE TITLE
Bisa Transfer?

### ISSUE THREAD

**Issue by Baju3D** [ridwanskaterock/cicool#200]
Saya ingin membeli Cicool tapi tidak punya kartu kredit dan uang dolar apakah bisa membeli dengan cara transfer uang?

**Comment by ridwanskaterock** [comment]
Halo mas
bisa mas bisa di transfer melalui bank BCA 5720869596 an Muhamad Ridwan dengan nominal IDR. 300.000 
Thanks

**Comment by Baju3D** [comment]
Ada alamat emailnya Mas?

**Comment by ridwanskaterock** [comment]
ridwanskaterocks@gmail.com mas

**Comment by Baju3D** [comment]
Alamat email saya zulfan_zubaidi@outlook.com
