### ISSUE TITLE
cara menghilangkan footer development enverionment dan penggunaan sendgrid

### ISSUE THREAD

**Issue by majid0875** [ridwanskaterock/cicool#201]
mau nanya bagaimana menghilangkan footer yg berisikan 
messages,exception, timeline yg ada dibawah?

apakah memungkinkan untuk dihubungkan dengan library sendgrid untuk pengiriman verifikasi via email?

terima kasih

**Comment by ridwanskaterock** [comment]
untuk menghilangkan footer message bisa dengan melakukan perubahan pada environtment ke index.php ke production 
untuk sendgrid bisa saja dengan mengkustom beberapa fungsi
