### ISSUE TITLE
mcrypy deprecated - plz adjust your code base

### ISSUE THREAD

**Issue by lisaiceland** [ridwanskaterock/cicool#202]
(1) 
- Hi. I just found out from my host: Since PHP 7.2 the mcrypt extension isn’t released anymore since it was deprecated for 7.1
- The composer.json file does allow it to be installed with PHP 7.2. An upgrade should be made to the library to move away from mcrypt.
- can you plz update this in your code to address this and give us an updated build we can download.
- I cannot downgrade as all my apps are on PHP 7.2.7
(2) 
Plz don't ask us we have to go back to PHP 5.6.x and NOT be on latest PHP 7.2.7. This is not a good coding practice and development.
here's the screenshot: https://cl.ly/1p1w2F461z2D

**Comment by ridwanskaterock** [comment]
can you change this value to true 

![image](https://user-images.githubusercontent.com/9270445/42258107-4e5e326a-7f84-11e8-8969-db69dcc22a3f.png)

on `./application/controllers/Wizzard.php`

for wizzard

**Comment by lisaiceland** [comment]
still got error:
see screenshots for code change and error
https://cl.ly/1w20450D3p0S
https://cl.ly/3o2Z0q0I312J

**Comment by lisaiceland** [comment]
what? don't understand what you're saying. Plz clarify.

Thank You. Bless.
Lis

Regards,

Lisa Kristinardottir (Lis)
Product Owner
Lisaiceland Inc. <https://lisaiceland.com/> | *myai.expert
<https://lisaiceland.com/>* | ClinicalTrials360 <https://lisaiceland.com/>
<http://ClinicalTrials360.com>

   P
*Save a tree! *
*Please let's ALL consider our environmental responsibility *
*before printing. *
*Don't print this e-mail unless it's really necessary.*

*CONFIDENTIALITY NOTICE*

This e-mail is intended only for the addressee named above. It contains
information that is privileged, confidential or otherwise protected from
use and disclosure. If you are not the intended recipient, you are hereby
notified that any review, disclosure, copying, or dissemination of this
transmission or taking of any action in reliance on its contents, or other
use is strictly prohibited.

If you have received this transmission in error, please reply to the sender
listed above immediately and permanently delete this message from your
inbox. Thank You.

**Comment by lisaiceland** [comment]
you mean change only to == TRUE

I did that. same error.

**Comment by ridwanskaterock** [comment]
only change like that 
![image](https://user-images.githubusercontent.com/9270445/42406904-a56758c6-81db-11e8-9ad5-669f5ab6d5d3.png) :)

**Comment by lisaiceland** [comment]
OK kool. Yes. This did the trick! TY ;-) Bless
