### ISSUE TITLE
cicool pagination issue

### ISSUE THREAD

**Issue by jasminmow** [ridwanskaterock/cicool#203]
Hello Guys,

I have purchased cicool and develop small application.

But I am facing an issue with pagination in cicool.

If anybody knows how to solve this please guide me.

Thanks,
Jasmin

**Comment by ridwanskaterock** [comment]
Hii

can you sdescribe your problem ? 
and you can give me screenshoot for that 

Thanks

**Comment by jasminmow** [comment]
Hi,

I mean if the list view is increased and if first page is full so it will go to second page.

And for second page if we click on '2' than it is not moving to the second page.

![image](https://user-images.githubusercontent.com/41192631/42690180-f2fd62e4-86c0-11e8-8c01-b2b1d727e493.png)

I have attached the screenshot for your reference.

Thanks

**Comment by ridwanskaterock** [comment]
realy i don't understand what do you mind, 

if you click page 2 page 2 not showing ? 

can you reproduce on http://cicool.heriver.com/ ? 

or you can give me an URL about your problem ? 

Thanks

**Comment by jasminmow** [comment]
yes if i click on page 2, page 2 not showing and also next button also not working. (in short page wise not moving based on page number click)

Please suggest.

Thanks

**Comment by jasminmow** [comment]
Hi,
I am using cicool version 2.3.0.

Thanks

**Comment by ridwanskaterock** [comment]
can you use latest version, 
current version is 2.6.8 

Thanks

**Comment by jasminmow** [comment]
but i have already developed the full application on version 2.3.0.
Could you please tell me how to upgrade with latest version, without affecting my existing application?

Thanks

**Comment by jasminmow** [comment]
Hi..Pls suggest me on this for upgradation

**Comment by ridwanskaterock** [comment]
ok for that can you 
follow this instruction 
https://github.com/ridwanskaterock/cicool/wiki/Upgrade-guide-to-latest-version

for other you can see wiki on 
https://github.com/ridwanskaterock/cicool/wiki

Thanks

**Comment by jasminmow** [comment]
Hi..Is this affect to  my existing developed software?

**Comment by ridwanskaterock** [comment]
if you not custom core controller model and other core function is ok 

you can test by copying your application for check

**Comment by jasminmow** [comment]
Hi..We have done custom coding in controller and model.
So if I replace only design files, is it ok to upgrade? and should it solve the pagination part.?

Thanks

**Comment by ridwanskaterock** [comment]
for design only maybe not solve for pagination, 
actually in version 2.3 I think pagination is not problematic
do you custom something?

you can upload to your server and give me ftp access for that

**Comment by jasminmow** [comment]
Hi..I have one question, i am uploading the files on server but some page does not show.
Could you please tell where the error logs are ? means where i can see the logs?

Thanks

**Comment by ridwanskaterock** [comment]
yes for logs you can change log_threshold to 1 value on config/config.php

**Comment by jasminmow** [comment]
Ok..where we can find the logs, means in which files logs are stored?

Thanks

**Comment by ridwanskaterock** [comment]
you  can find it on application/logs folder

**Comment by jasminmow** [comment]
ok thanks a lot

**Comment by jasminmow** [comment]
Hi..Can i upload the excel sheet data into the database using cicool ?

**Comment by jasminmow** [comment]
Is there any facility for this?

Thanks

**Comment by jasminmow** [comment]
Hi..Can i upload the excel sheet data into the database using cicool ? 

thanks

**Comment by jasminmow** [comment]
Hi,

Hope you are doing well.
Is there any facility or library available in cicool to crop image?

Thanks

**Comment by ridwanskaterock** [comment]
yes because cicool upload image library using fineuploader

**Comment by jasminmow** [comment]
Thanks

**Comment by jasonduerr** [comment]
Version 3.0.0
Confirming pagination (from anything in Form Builder) results in a 404 not found. 
Perhaps issue with Routes?
Anyone else experiencing this?

**Comment by ridwanskaterock** [comment]
can i see you URL please ?

**Comment by jasonduerr** [comment]
Yes, absolutely. 
If you could kindly bounce me a message here: jtd909@gmail.com, I have the screen shots ready to share. I do apologize for the extra step.
Thanks for the assistance.

**Comment by ridwanskaterock** [comment]
Just send your mail
