### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#206]
Mas Ridwan,

Sorry saya mau tanya donk sblm nambah support lagi nih.
Kok Cicool yg terakhir saya beli ketika mau dipake lagi ada error "DATABASE ERROR" pada saat pembuatan CRUD. database sample kan tabel BLOG.

![database error crud - cicool](https://user-images.githubusercontent.com/9460402/43182224-bb5ae2be-900a-11e8-9182-a6d5eba4d221.jpg)

**Comment by ridwanskaterock** [comment]
coma di lihat sourcenya mas ada error ? 

sebelumnya bisa di run di sql adminya 

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
