### ISSUE TITLE
Found a bug Trying to get property of non-object

### ISSUE THREAD

**Issue by benzon** [ridwanskaterock/cicool#207]
Trying to get property of non-object

If you link up a nother table to your CRUD view, and then try to view a entry you get this error.

http://nimb.ws/0aNTSO

The table reff causes issues when wanting the view an entry, delete, og change, so it breaks Cicool quite abit.

http://nimb.ws/cHp5IJ

When i push change, or view i get this error, if i push delete it says it's deleted but never is deleted, need this fixed azap.

**Comment by ridwanskaterock** [comment]
for error before you delete of crud of list ?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>
Sent
with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>

Pada tanggal Rab, 1 Agt 2018 pukul 18.23 Søren <notifications@github.com>
menulis:

**Comment by benzon** [comment]
This error is when you push view, or change, when viewing the data grid, delete dont show the error but just dos nothing.

**Comment by ridwanskaterock** [comment]
yes I am going to make improvements and in order to avoid error make sure envorontment on index.php is set to production

Thanks

**Comment by benzon** [comment]
The issue is if i set it to production i get 0 data when i click see or change, it's quite important we find a fix for this issue since it's holding us back right now

**Comment by ridwanskaterock** [comment]
ok if you want it can you share ftp access and describe the details with screencam i will reproduce errors and fix

Thanks
