### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Sunburst2810** [ridwanskaterock/cicool#208]
When I have just start installation cicool the error is showing i.e. attached.

Please resolve the issue as soon as possible I am very afraid after purchasing the software.

![cicool isuue](https://user-images.githubusercontent.com/32106717/43675627-d250efa6-9800-11e8-8c45-7e751ef5a5f9.png)

**Comment by Sunburst2810** [comment]
Please resolve the issues as soon as possible......

I have to start the website as soon as possible.....

**Comment by ridwanskaterock** [comment]
you can see error message for that 

this problem occour because server configuration 
please enabled allow_url_fopen on your server by modify php.ini
![image](https://user-images.githubusercontent.com/9270445/43695686-5ce6b47a-9964-11e8-82bb-84dd3e054ef2.png)

**Comment by Sunburst2810** [comment]
Hi Ridwan,

I have logged the Ticket to Hosting Support,

And they told me that we have already done the things which you are asking
to do.

i.e. - allow_url_fopen=On


And discuss with your Developer End for this Issue.


So Mr. Ridwan,

Please check from your end and gimme propper support,


And check it from yourself level and resolve this issue as soon as
possible, I am not able to work in your system, Even i had paid 15 days ago.


If you need my cPanel credentials then i can share it to you, Either gimme
your Whatsapp No. of Skype ID.

**Comment by Sunburst2810** [comment]
My URL - http://sunbeamitbusiness.com/

Check the error.

**Comment by ridwanskaterock** [comment]
yes seems file_get_contents not working perfect on your server 
while waiting you can remove this code

![image](https://user-images.githubusercontent.com/9270445/43728290-d3b03c74-99ce-11e8-8dcc-6716491867c6.png)
on application/helpers/app_helper.php

if problem not solved you can send me for ftp or cpanel access 

Thanks

**Comment by Sunburst2810** [comment]
After deleting this line

 I have run 2 steps but in 3rd step got the error

The scrn shot attached.

For more support my cPanel URL - http://103.93.17.39:2082

Login ID - sunburst

Password - PqJ45j1c7e


Please resolve the issue as soon as possible,

Or Refund the amount please...



[image: image.png]

**Comment by Sunburst2810** [comment]
Hi Mr. Ridwan,

I am expecting positive reply from you,

I am very fedup and facing the issues from last 4 Days,

But even not able to create my Website,

This is my business site and I  am facing very loss due to this i cant
build my portfolio which needed from my client..


Kindly reaolve the issue and update this website.


Soonest reply expecting....

**Comment by ridwanskaterock** [comment]
I have checked it and this is too much error and the server settings are
very limited from your hosting provider


[image: image.png]

https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings




‌
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>
Sent
with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>

Pada tanggal Sel, 7 Agt 2018 pukul 14.54 Sunburst2810 <
notifications@github.com> menulis:

**Comment by ridwanskaterock** [comment]
You can login on
http://sunbeamitbusiness.com
 u : admin@admin.com
p : admin123

Thanks




‌
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>
Sent
with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>

Pada tanggal Sel, 7 Agt 2018 pukul 15.02 Muhamad Ridwan <
ridwanskaterocks@gmail.com> menulis:

**Comment by ridwanskaterock** [comment]
actually I have repaid as much as I can, because there is too much support coming in via email skype github etc,
so I arranged for it, :)

**Comment by Sunburst2810** [comment]
How to i create the website and put into the Domain Home Page,

Please help...

**Comment by ridwanskaterock** [comment]
just upload cicool folder anda pointing your domain to your cicool folder ? just it ? 

if you use shared hosting you can copy cicool file to public_html
