### ISSUE TITLE
API 403 Error

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#209]
----Removed image.----

Will this API ever work ?

**Comment by ridwanskaterock** [comment]
you can see detail of response 
![image](https://user-images.githubusercontent.com/9270445/43687503-62eef88c-9900-11e8-8df0-11d62b515aa6.png)

Could it be because the input or API you entered was incorrect?

**Comment by cnngraphics** [comment]
Empty response because OPTIONS request happens always before the real request. In this case the app never gets to the real request. The API stops at OPTIONS.

![image](https://user-images.githubusercontent.com/1514378/43691248-c272b62c-98e7-11e8-9609-b47d45339f45.png)

**Comment by ridwanskaterock** [comment]
can you check for url ? 
![image](https://user-images.githubusercontent.com/9270445/43695566-aa71bdd0-9963-11e8-8a06-caf39c7db114.png)

**Comment by cnngraphics** [comment]
What should I check for? The help is not helping with those kind of short questions. Makes me wonder if you created this app or someone else did?

Not happy with the support here!
What should I check for!

**Comment by ridwanskaterock** [comment]
should you see from the url, if the URL you sent is incomplete?
in the screenshot you only enter the example.com/api/

sorry if it's too short because I have too much support I have to help on email github skype etc
