### ISSUE TITLE
CRUD to display at the front page

### ISSUE THREAD

**Issue by soto48** [ridwanskaterock/cicool#21]
how to display the crud data in the front page? thanks

**Comment by ridwanskaterock** [comment]
in fact it can be done, but no snippet / shortcode on this cicoool.

and you can do so by adding a code on the front page,

by adding a controller on the front page

for example

```php

$this->load->model('model_book');

$filter = $this->input->get('q');
$field     = $this->input->get('f');

$this->data['books'] = $this->model_book->get($filter, $field, 10, $offset);
$this->data['book_counts'] = $this->model_book->count_all($filter, $field);

$config = [
    'base_url'     => 'administrator/book/index/',
    'total_rows'   => $this->model_book->count_all($filter, $field),
    'per_page'     => $this->limit_page,
    'uri_segment'  => 4,
];

$this->data['pagination'] = $this->pagination($config);


```

**Comment by soto48** [comment]
Thanks for the code, however, can you elaborate more on step by step process for better integration with the application, for example,  do we need to create new file or we just insert in the existing file ?, etc. Thanks

**Comment by ridwanskaterock** [comment]
This has been resolved?

i will close this issue 

thanks
