### ISSUE TITLE
Change language and format of datapicker

### ISSUE THREAD

**Issue by ramzi76** [ridwanskaterock/cicool#210]
Hello Ridwan,

This question is about datapicker :
How can I change the language from english to french , date format (d/m/Y), ... ?

Thanks

**Comment by ridwanskaterock** [comment]
Hi, you can adjust on this file
Asset/js/custom.js



Pada tanggal Rab, 8 Agt 2018 22.00, ramzi76 <notifications@github.com>
menulis:
