### ISSUE TITLE
A big problem

### ISSUE THREAD

**Issue by goupold** [ridwanskaterock/cicool#211]
Hello dear,
I thank you for your great effort in this script  "Cicool".
In order to try  "Cicool"  before installing it on the server on the Internet,I installed it on a local server on my PC.
I installed "Cicool"  on PHP Version 7 , and I have my own script did not work on this release " 7" . And I downgrade to PHP Version 5.6 , and After installing the Cicool (on php 5.6 ) add extensions (disable builder and theme...)  . the Cicool script  did not work. This details:
-----------------------------

file | "C:\xampp\htdocs\cicool\cc-content\extensions\disable-builder\disable-builder.php"
-- | --
line | 113

-----------------------------
[error.txt](https://github.com/ridwanskaterock/cicool/files/2274906/error.txt)

**Comment by ridwanskaterock** [comment]
Hi.
can I see an error in PHP 7?
cc-content\extensions
cc-content\extensions\disable-builder

**Comment by goupold** [comment]
I also expect the same error message in php7.
Now, The problem is with the php5.6.
It is working well When I Delete the extension folder, and replace it with the original files.
But when I install the extensions  and activate again, the problem occurs.

**Comment by ridwanskaterock** [comment]
solved on latest version thanks
