### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by ofgueye** [ridwanskaterock/cicool#212]
Hello,
is it possible to create drop lists (select) under ajax, let me explain: I want to load a second unrolling list (select city) according to the selection of the first (select country)

**Comment by ridwanskaterock** [comment]
for chained examples not available in cicool
but you can customize the code that cicool has generated to make it chained with ajax

**Comment by ofgueye** [comment]
How is it going to be ??

**Comment by ridwanskaterock** [comment]
you can follow this 
https://www.youtube.com/watch?v=bxA6M9LYrPk
https://www.webslesson.info/2018/06/codeigniter-dynamic-dependent-select-box-using-ajax.html
