### ISSUE TITLE
template design

### ISSUE THREAD

**Issue by perfectwebtech** [ridwanskaterock/cicool#213]
hello

i need help 

1) how i can do template integration like pagination and form 

template or default theme how i can customize according to my need

2) there is defualt theme and blank theme which is way easy way for me to integration new theme for 

add update delete

3) similar thing how i can handle crud theme also i canchnage myself how 

or how i can make dynamic theme according to my theme help me plz 
or give tutorial how i can integration  theme for full of  crud form and pages

**Comment by ridwanskaterock** [comment]
for create new theme for frontend you can learn on avaiabel theme 

cc-content/theme/cicool 

you can copy this folder and you can modify like what you want 

and on cc-option table you can change value for active_theme

**Comment by perfectwebtech** [comment]
1) but how route and add menus in theme
2) example i have created forms and pages 

now i want to pages want to create as link for let say one of courier portal  add courirer  courier list courier company list   courier company add

3) how i can integration crud or forms or pages with other codigniter version or latest version what files i  should copy and it should be working with my theme ? 

4) what is easy way for my new created portal crud builder or form with page builder easy ? 

5) i do not want to admin code to my client server how i can do this with this ci-cool ? like

if i upload to my client server i want to only generated code only want to give to my client server

i do not want to give generator modules as administraotr to him how i can do it ?

**Comment by ridwanskaterock** [comment]
for modules generator will avaiable for next version thanks 
![gambar](https://user-images.githubusercontent.com/9270445/47599649-a9d2d800-d9dc-11e8-8340-ab6425a7bcd5.png)
