### ISSUE TITLE
Form - File Multiple option doesnt work

### ISSUE THREAD

**Issue by paulchicago74** [ridwanskaterock/cicool#214]
Hi. When I create a form and select a field to be "file multiple" it doesnt work. When I look at my form I have just a simple field. What is the fix for this problem?

**Comment by ridwanskaterock** [comment]
![image](https://user-images.githubusercontent.com/9270445/44310663-40df4a80-a404-11e8-8230-c2dc798de4d5.png)

![image](https://user-images.githubusercontent.com/9270445/44310673-5eacaf80-a404-11e8-95ea-7c1030feee66.png)

http://cicool.heriver.com/administrator/blog 
that's work, can you describe your problem ?

**Comment by qulez** [comment]
Hi this function doesn't work when we use it **through Form Builder**, but when we used CRUD Builder then it works nicely.

I can approve it doesn't work from your demo application. To test it, then from **From Builder** Add Form New, then we add **File Upload Component** and then change the option from **File** to **File Multiple**.
![file-multiple](https://user-images.githubusercontent.com/7066470/45105354-3fc94f80-b15e-11e8-9228-bfffece6343d.png)

 When we look into Preview Form it only appeared as simple input form.

![file-multiple-preview](https://user-images.githubusercontent.com/7066470/45105365-48ba2100-b15e-11e8-996a-85e4bf58de6b.png)

Do you have any plans to fix it? Or there is missing step? Thanks ...

**Comment by ridwanskaterock** [comment]
yes i will make fix for preview but on generate files multiple files is normally 
thanks

**Comment by PoleDigitalCMO** [comment]
Hi,

Sorry i have the same issue.
I don't see codes for "file_multiple" in following templates :
`
/application/views/core_template/form/form_preview.php
/application/views/core_template/form/form_submission.php
/application/views/core_template/form/form_update.php
/application/views/core_template/form/form_view.php
`

Regards,
