### ISSUE TITLE
Import Data button

### ISSUE THREAD

**Issue by paulchicago74** [ridwanskaterock/cicool#215]
Is it possible to include an import button on CRUD to import data from a csv file? I see that other Admin CRUD apps have this functionality but Cicool is missing it.

If I have a customer that is migrating from a different app there is no way he can import the data from the admin menu. In my opinion this is a "must have" function.

**Comment by ridwanskaterock** [comment]
for now on cicool is not yet available maybe I will make that feature come up 

Thanks

**Comment by ridwanskaterock** [comment]
you can try by following this tutorial https://www.bladephp.co/phpexcel-import-excel-to-mysql-in-codeigniter
