### ISSUE TITLE
API REST Configuration

### ISSUE THREAD

**Issue by Sysworld** [ridwanskaterock/cicool#217]
Hello there!
We bought your software three days ago and so far so good with the things that we were trying.
I have one question though, we are trying to create an API REST and we wanted to know if it's possible that, when the API get all the elements only bring from the database the records that belongs to the user that it's logged on. Is this possible?
Another thing that we wanted to know if we can do it, it's if the API can record in the table the user or the API key that's making the call every time that a new record is inserted.

Thanks in advance!

**Comment by ridwanskaterock** [comment]
Hi thanks for it

for enable logging every call API you can activate logs on 
![image](https://user-images.githubusercontent.com/9270445/45033173-f1dd1a80-b07d-11e8-8d01-101f574ebf52.png)

application/config/rest.php

yes for get information user you can call API login and you can store on session / cookie / local db 

Thanks

**Comment by Sysworld** [comment]
Thanks for your answer but my question is that the table in the database has a column that is "user", the thing that we want to acomplish is that when we do GET, shows or bring the records for the user that's logged on in the API.

Cheers!

**Comment by ridwanskaterock** [comment]
Hi,,
I don't understand your purpose?
do you mean loggin for users / activities?

Thanks

**Comment by Sysworld** [comment]
Sorry, I'm gonna try to be clearer.
Let's say that we have a user called "nicodd17" and it's logged in on a certain system, the thing that we want to know if it's possible, it's that when the user nicodd17 connects to the API to look for it's data on a certain table, the API only brings the information for the user nicodd17 and not the information of other users that can be with information on the same table.
Let me know if you ned more info, english it's not my mother tongue :)
Thanks!

**Comment by Sysworld** [comment]
Excellent!
Can you tell me a little bit what do I have to configure in the settings of the API to accomplish that please?

**Comment by ridwanskaterock** [comment]
Yes on this case i have book API 

and you can generate API and custom this code on controller 

![image](https://user-images.githubusercontent.com/9270445/45435865-a5c45280-b6db-11e8-92fe-52ac8f5b5fd1.png)
./application/controllers/api/Book.php 

and i have one data blog with author admin 
![image](https://user-images.githubusercontent.com/9270445/45436253-8b3ea900-b6dc-11e8-835a-a76aa0878240.png)

i try filtered with author = ridwan 

if admin 
result is exist 

![image](https://user-images.githubusercontent.com/9270445/45436346-cf31ae00-b6dc-11e8-9025-9c8be55b45e8.png)

I hope this helps 

result is null 
![image](https://user-images.githubusercontent.com/9270445/45436321-bb864780-b6dc-11e8-98c8-0e77a966fe38.png)

**Comment by Sysworld** [comment]
Thanks for that!
I'm gonna let you know if I can replicate that.
