### ISSUE TITLE
Can't install because beacuse mcrypt is deprecated

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#218]
Any solution to this issue?

![image](https://user-images.githubusercontent.com/1514378/45271082-15370980-b472-11e8-8689-0f392b436152.png)

**Comment by ridwanskaterock** [comment]
you just set it to true 

![image](https://user-images.githubusercontent.com/9270445/45272920-2a478300-b4da-11e8-81c4-510501731e8c.png)

on ./application/controllers/Wizzard.php 

Thanks
