### ISSUE TITLE
Tables with foreign key Crud

### ISSUE THREAD

**Issue by puneetkhannaK** [ridwanskaterock/cicool#22]
HI 

Tables with foreign key Crud . Add and Update working . But view not working .. 

Page displays ..
 is currently unable to handle this request.
HTTP ERROR 500

**Comment by puneetkhannaK** [comment]
HI 

seems Crud is seeing some issue .

![image](https://cloud.githubusercontent.com/assets/25583792/22734971/aab39176-ee1d-11e6-85ac-db804b79e3b1.png)

**Comment by ridwanskaterock** [comment]
can i see your db structure, and fails response 

thanks

**Comment by puneetkhannaK** [comment]
Hi 

sorry for delay .. I was able to solve that issue 

Db Table name was having space in Name .eg admin ID . changed it adminID. solved the problem .

But now it has started a new problem .. Not able to save data in CRUD table ..

Please find the required snapshots .. 

DB Stucture .

![image](https://cloud.githubusercontent.com/assets/25583792/22777687/0bf8ba12-eeda-11e6-834f-b46f75687957.png)


CRUD table 

![image](https://cloud.githubusercontent.com/assets/25583792/22777749/3c720ba8-eeda-11e6-99fd-982c13f0bd1a.png)


error

![image](https://cloud.githubusercontent.com/assets/25583792/22777774/55107ba4-eeda-11e6-9775-045b9549683d.png)

**Comment by ridwanskaterock** [comment]
hii Data not change because you did not make any changes when updates

**Comment by ridwanskaterock** [comment]
thanks for it, i will close this issue
