### ISSUE TITLE
Create modules for Cicool, is it possible? 

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#220]
Hello, is it possible to develop cicool modules to separate my new development from the original cicool code (to facilitate updates) or integrate hmvc modules by extending the cicool classes? 
To get a directory where to manage my code using git without creating conflicts with the cicool code?
Thank you

**Comment by ridwanskaterock** [comment]
yes you can customize it for modular but if new updates avaiable maybe you must really do a script update or even can't do it if there are a lot of changes / custom

**Comment by ridwanskaterock** [comment]
for modular version will avaiable on next version thanks 
![gambar](https://user-images.githubusercontent.com/9270445/47599629-51033f80-d9dc-11e8-93b6-a9d2ebc5805c.png)
