### ISSUE TITLE
Error loading. Crud-Api

### ISSUE THREAD

**Issue by wancode** [ridwanskaterock/cicool#221]
What is the problem?

![screenshot from 2018-09-26 21-06-05](https://user-images.githubusercontent.com/38166045/46099710-2bfa9180-c1d0-11e8-8644-08dad9e71a97.png)

**Comment by ridwanskaterock** [comment]
please ctrl + u for see the console 

and paste to this issue 

before if you run on version > 2.5 you can running by call URL 
yourdomain.com/web/set_full_group_sql

or you can running this script manually on PHP myadmin 

```sql
set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;

```

Thanks

**Comment by wancode** [comment]
Thank you.

**Comment by johnfelipe** [comment]
> web/set_full_group_sql

is bad syntaxys

this is correct

	set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
	set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
