### ISSUE TITLE
http://localhost/ci-lte-generator/asset/js/custom.js can't not be found

### ISSUE THREAD

**Issue by ytingchou** [ridwanskaterock/cicool#223]
Environment:
- OS: macOS 10.12.6
- Browser: Google Chrome version 70.0.3538.54

When trying to preview page on page builder, it would encounter the error on Google Chrome:
```
GET http://localhost/ci-lte-generator/asset/js/custom.js net::ERR_ABORTED 404 (Not Found)
```

After tracing the code, the problem is caused by the following code snippet on page_html_formater.php.

```php
<script src="http://localhost:80/ci-lte-generator/asset/js/custom.js"></script>
```
This issue can be reproduced on the demo website (http://cicool.heriver.com/administrator/login) as well.

**Comment by ridwanskaterock** [comment]
Thanks you for report i will check for that

**Comment by searchy2** [comment]
I'm having this issue as well. The page generator previews do not load because of this issue and mixed http/https content.
