### ISSUE TITLE
User permission

### ISSUE THREAD

**Issue by sergioalejanpro** [ridwanskaterock/cicool#224]
Hello...

Is it possible to assign specific permissions to a certain user ? I mean some permission that is not included on the user group... How can this be done ?

Thanks and congrats for such a great piece of software !!!

**Comment by ridwanskaterock** [comment]
Hi

yes it allows you to create a special group for that user and the group is assigned to a particular user.

because currently the user can have more than 1 group 

THanks

**Comment by sergioalejanpro** [comment]
Ok, Thanks !
