### ISSUE TITLE
/api/user/detail/ 

### ISSUE THREAD

**Issue by theokyra** [ridwanskaterock/cicool#225]
Trying to get user details from /api/user/detail/ 
i get this response:
{
    "status": false,
    "message": "Parameter id is required"
}

I do not know why because  /api/user/detail/ does not require ID
![image](https://user-images.githubusercontent.com/40278930/47573941-82143f00-d90c-11e8-957a-ed1466e6db22.png)

**Comment by theokyra** [comment]
OOps! I figured it out... not only I was calling the wrong API
but also, the returned token from login has the user ID when token is decoded

I should have called /user/detail

**Comment by ridwanskaterock** [comment]
Yes for get information user of login user you can call api/user/profile
without fill id
