### ISSUE TITLE
Default display translation if langguage item not exist 

### ISSUE THREAD

**Issue by ridwanskaterock** [ridwanskaterock/cicool#226]
for example the translation does not exist in web_lang, the system automatically takes the word in cc_lang ('....') but with all lowercase letters, so when changing language but the language is not available, we can immediately know and immediately add the word tab to the web_lang

**Comment by ridwanskaterock** [comment]
Hi if you can access by index.php url 
i think you modrewrite on your server configuration is disable 
you can enable modrewrite first

**Comment by inglesuniversal** [comment]
Hello again...

I am running php 7.1 on AWS Bitnami Server... according to the following LINK mod_rewrite is enable by default... The ONLY suggest to change the <Directory > to ... AllowOverride All and I did both and I get the same error... Any ideas?

Settings LINK

https://stackoverflow.com/questions/4047898/how-to-enable-mod-rewrtie-on-ubuntu-on-bitnami-machine-on-amazon

Here is the file I changed on my server...

 /opt/bitnami/apache2/conf/httpd.conf

**Comment by ridwanskaterock** [comment]
Hi sorry i can't access your site

[image: gambar.png]

actualy if mod rewrite is enable codeigniter will ignore for index.php

https://stackoverflow.com/questions/7337724/how-to-check-whether-mod-rewrite-is-enable-on-server

you can check


[image: gambar.png]

on phpinfo();


Thanks

**Comment by ridwanskaterock** [comment]
You can follow this issue https://github.com/ridwanskaterock/cicool/issues/218 thanks

**Comment by inglesuniversal** [comment]
it worked like a charm... Thanks
