### ISSUE TITLE
An Error Was Encountered during Wizzard

### ISSUE THREAD

**Issue by nicowebsite** [ridwanskaterock/cicool#23]
Hi,
Setp 1 & 2 are perfect.
I have this issue just after clicking on step 3 button (after Database & Site Configuration page).
I've tried several times, but still not going further.
MESSAGE: The action you have requested is not allowed.
I've seen this [post ](https://github.com/ridwanskaterock/cicool/issues/19) and change my email address, but still the same issue.
Please help me to finish install

**Comment by ridwanskaterock** [comment]
Please attach your screenshoot,  i don't see more for detail information, and server witch you use

**Comment by nicowebsite** [comment]
Hi,
You can see Wizzard process pictures here: [http://hpics.li/023d7dd](http://hpics.li/023d7dd)
When click last button, here the message: [http://hpics.li/f1587b9](http://hpics.li/f1587b9)
Yo're help will be very appreciated.
I'm looking forward to use your fantastic builder

**Comment by ridwanskaterock** [comment]
Hii, 

You can following this issue https://github.com/ridwanskaterock/cicool/issues/19

Maybe can help you
I always support until this app running smothly

I waiting good review from you thanks :)

**Comment by nicowebsite** [comment]
; (
See my first message where I wrote "I've seen this post (#19) and change my email address, but still the same issue."
I've already tried this.
Where does the email adress information is store during the wizzard ? in database or a file (which one) ? I might have a look.

**Comment by ridwanskaterock** [comment]
Okay sorry :D

You have been test with email admin@admin.com

Please type email in email input.

And if it's wrong, you can give me screenshoot about your error and page 3in wizzard

Thanks

**Comment by nicowebsite** [comment]
Page empty and blank

**Comment by nicowebsite** [comment]
Do you have an email for MP ?

**Comment by ridwanskaterock** [comment]
What the MV ? This is my email ridwanskaterocks@gmail.com

If response give the blank page you can change environtment to development
in constant

From file index.php

Thanks

Pada tanggal 13 Feb 2017 23.06, "nicowebsite" <notifications@github.com>
menulis:

Do you have an email for MP ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ridwanskaterock/cicool/issues/23#issuecomment-279436796>,
or mute the thread

**Comment by nicowebsite** [comment]
i've replied to you with MP.

**Comment by nicowebsite** [comment]
Hi,
I've send you an email and didn't have an answer. I'm so lookinf forward to use your CRUD builder that I wish you can tell me what's wrong to make it work. I've seen you've relaesed a new version yesterday. I downloaded it but still the same error message.
Please check  you email, I've send pictures.
Cheers

**Comment by ridwanskaterock** [comment]
can you please tell the server what you use and how php version you use, you are at the OS what? thanks

**Comment by ridwanskaterock** [comment]
hii actual PHP version you are using in support by our cicooll, what happened error what do you get?

you can send a screenshot to us

whether the apache / nginx are you using?
and os what you wear?

thanks

**Comment by nicowebsite** [comment]
I've send you the error by email in MP.

**Comment by ridwanskaterock** [comment]
i will close this issue 
thanks

**Comment by MediaMetz** [comment]
I have the same problem. 
I have my site on Plesk. With the local SQL-Server, I become the message:"An Error Was Encountered The action you have requested is not allowed.".
With the Amazon AWS SQL-Server is my last setup page blank.

What can I do.
