### ISSUE TITLE
file_get_contents(http://ipinfo.io/::1): failed to open stream: HTTP request failed!

### ISSUE THREAD

**Issue by teguhrazhar** [ridwanskaterock/cicool#231]
terjadi saat deploy aplikasi pertama kali

**Comment by ridwanskaterock** [comment]
![image](https://user-images.githubusercontent.com/9270445/50432002-9b803a00-0901-11e9-8ae6-73c6b1840910.png)
bisa coba di nonaktif dlu buat cek IP, 

di application/helpers/app_helper.php
