### ISSUE TITLE
Add New Database Error for CRUD, REST, and Forms

### ISSUE THREAD

**Issue by searchy2** [ridwanskaterock/cicool#235]
![maxthonsnap20190119211055](https://user-images.githubusercontent.com/19896174/51434839-8dd38100-1c2f-11e9-9e25-2934b9fe44f6.png)
![maxthonsnap20190119211049](https://user-images.githubusercontent.com/19896174/51434840-8f04ae00-1c2f-11e9-8fd6-c892c754a64b.png)
![maxthonsnap20190119211040](https://user-images.githubusercontent.com/19896174/51434841-9035db00-1c2f-11e9-8633-e16665e13e50.png)
My issue appears to be related to #140, #107, and #49. Unfortunately, I cannot use the fix as I do not have global access to the MySQL database. 
Can you provide an alternative? I look forward to your response.

**Comment by ridwanskaterock** [comment]
You can try by running this SQL 

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
 set session sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

**Comment by searchy2** [comment]
Comment out Line 85 `$this->db->group_by('validation_group');` in `Model_crud.php` `Model_form.php` `Model_rest.php` fixes this issue. 

What purpose does the `validation_group` serve?
