### ISSUE TITLE
Failed to load resource: the server responded with a status of 500

### ISSUE THREAD

**Issue by johnfelipe** [ridwanskaterock/cicool#238]
” //administrator/crud/add_save:1 Failed to load resource: the server responded with a status of 500 () “

https://drive.google.com/file/d/1grpMd-zf3UfduMmXl3qoNd80V6Sloavw/view?usp=drivesdk

This is my table https://drive.google.com/file/d/1sVwsVCUoI7Ee8r6JMDjdm8uWkqqK_hAX/view?usp=drivesdk

**Comment by ridwanskaterock** [comment]
DIscussion change to skype
