### ISSUE TITLE
Error in form wizzard just after install

### ISSUE THREAD

**Issue by RedKingPhuket** [ridwanskaterock/cicool#24]
Hello, 
I just buy your CMS today.
I install in Mac with MAMP and PHP 7.1

The install is OK but after when I go to this URL : 
http://localhost:8888/cicool/administrator/form

I have a fatal error: 
fatal error: Cannot use lexical variable $form as a parameter name in /Applications/MAMP/htdocs/cicool/application/views/backend/standart/administrator/form/form_list.php on line 94

Update : 
I have many error, every back-office page in fact

**API builder**
http://localhost:8888/cicool/administrator/rest
Fatal error: Cannot use lexical variable $rest as a parameter name in /Applications/MAMP/htdocs/cicool/application/views/backend/standart/administrator/rest/rest_list.php on line 93

**Page Builder**
http://localhost:8888/cicool/administrator/page
Fatal error: Cannot use lexical variable $page as a parameter name in /Applications/MAMP/htdocs/cicool/application/views/backend/standart/administrator/page/page_list.php on line 107

_A PHP Error was encountered
Severity: Compile Error
Message: Cannot use lexical variable $page as a parameter name
Filename: page/page_list.php
Line Number: 107
Backtrace:_

**CRUD Builder:**
Many warning and 1 fatal error 

Thanks for your help.

Yohann

**Comment by ridwanskaterock** [comment]
hii thanks bought this item,

Our test your previously in various kinds os, windows, linux and MAC and it goes well with PHP or nginx web server,

and we also test the PHP 5.5 to PHP version 7

what it might be due to use PHP PHP in version 7.1?

thanks

**Comment by RedKingPhuket** [comment]
I install with MAMP on Mac OS Sierra (10.12.3) : 
- Apache 
- PHP 7.1.1 
- MySQL 5.6.35

I just try with PHP 7.0.15  : 
=> no fatal error, 
=> OK for Page and API builder
=> many warning only in CRUD Builder.

_Priority : Warning_

_Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /Applications/MAMP/htdocs/cicool/application/controllers/administrator/Crud.php:2)

Filename: Session/Session.php

Line Number: 141

Backtrace:

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 116
Function: library

File: /Applications/MAMP/htdocs/cicool/application/libraries/Aauth.php
Line: 97
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 116
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 98
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Controller.php
Line: 26
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Controller.php
Line: 423
Function: __construct

File: /Applications/MAMP/htdocs/cicool/application/controllers/administrator/Crud.php
Line: 18
Function: __construct

File: /Applications/MAMP/htdocs/cicool/index.php
Line: 315
Function: require_once_

**Comment by ridwanskaterock** [comment]
for solve this problem 
_Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /Applications/MAMP/htdocs/cicool/application/controllers/administrator/Crud.php:2)

Filename: Session/Session.php
please restart your web server, maybe can help you thanks :)

**Comment by ridwanskaterock** [comment]
maybe this can help you for same issue https://github.com/ridwanskaterock/cicool/issues/25

thanks

**Comment by mtaraabi** [comment]
Hi Ridwan, 

I'm facing the same issue

I use MAMP on a mac

1. Apache
2. PHP 7.0.13
3. MySQL 5.6.35


In CRUD Builder I receive the below errors

` 
A PHP Error was encountered

Severity: Warning

Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /Applications/MAMP/htdocs/cicool/application/controllers/administrator/Crud.php:2)

Filename: Session/Session.php

Line Number: 141

Backtrace:

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 116
Function: library

File: /Applications/MAMP/htdocs/cicool/application/libraries/Aauth.php
Line: 97
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 116
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Loader.php
Line: 98
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Controller.php
Line: 26
Function: library

File: /Applications/MAMP/htdocs/cicool/application/core/My_Controller.php
Line: 423
Function: __construct

File: /Applications/MAMP/htdocs/cicool/application/controllers/administrator/Crud.php
Line: 18
Function: __construct

File: /Applications/MAMP/htdocs/cicool/index.php
Line: 315
Function: require_once `

I cant find the new form (table) when I try to add new CRUD also the per-exsiting blog and category is not accessible. I receive the below error message 

`warning!
×
Error getting data`  

Please provide me with a solution I just bought it and I can not wait to start playing with it.

Thanks in advance

**Comment by mtaraabi** [comment]
Should I put it in a new question ?

**Comment by ridwanskaterock** [comment]
![image](https://cloud.githubusercontent.com/assets/9270445/23090193/5e3f05b4-f5ca-11e6-9453-61ee9cc36d12.png)

hi,
I am happy to assist you,

you can try remove line 1 application/controllers/administrator/crud.php

maybe white space or line space is causing problems

**Comment by mtaraabi** [comment]
Yep, the white line solved the first issue. However, the second issue still exist. 

CURD is not picking up the new form that I created.

**Comment by mtaraabi** [comment]
I just checked that API Builder is picking up the form I have created but CURD is not.

**Comment by ridwanskaterock** [comment]
you mean when crud made and no changes to the database? you can create a new field appears on CRUD?

**Comment by ridwanskaterock** [comment]
yes if it is not able at this time :)

**Comment by mtaraabi** [comment]
Okey, then how to create table to show up in CRUD Builder?

**Comment by mtaraabi** [comment]
Thanks for your prompt response
