### ISSUE TITLE
Extend automatically created rest-api (class)

### ISSUE THREAD

**Issue by pascal-linux** [ridwanskaterock/cicool#242]
Hi,

how is it possible to extend a class created by your rest-api function (or crud function)
with for example a "post process" that writes the information into another table (or other things).

When I try to do that (just adding some code) it is overwritten each time the rest-api is recreated.
What is the "best practise" for that?

Thanks,
PAscal

**Comment by ridwanskaterock** [comment]
Hi yes, right if you make a custom and the code is updated again, the old custom will be overwritten, you should first back up your custom code
