### ISSUE TITLE
Extension Confusion???

### ISSUE THREAD

**Issue by brianrevie** [ridwanskaterock/cicool#246]
Please can you explain to me how the extensions are working??

When I click extensions in the menu, I see the list of extensions which I can activate/deactivate.

![screenshot 2019-02-20 at 08 21 31](https://user-images.githubusercontent.com/3092445/53076842-98ac5a80-34e8-11e9-834b-ae92d462f7de.png)

But when I click 'Add New Extension' I see only  4 extensions which seem to be populated dynamically from Github, that I cannot remove or edit.

I cannot add new extension from this page?? How Do I add my own?

How do I manage these extensions?

**Comment by brianrevie** [comment]
Anything on this?
Why is there Extentions being pulled from directory. But when click add new, extensions being pulled remotely?

**Comment by ridwanskaterock** [comment]
Sorry

for now the extension can only be extracted from the directory that is already on the github I am not created for global

but if you want to make extensions you can learn and read existing documentation (only a few)

You can see the extension on
cc-content/cc-extensions/

**Comment by ridwanskaterock** [comment]
![image](https://user-images.githubusercontent.com/9270445/54761393-9858c980-4c24-11e9-9069-b5a95d0ca6e8.png)


this documentasion is BETA 

https://cicoolbuilder.github.io/documentation/#/

not completed
