### ISSUE TITLE
Forgot Password Not Working

### ISSUE THREAD

**Issue by brianrevie** [ridwanskaterock/cicool#247]
I tested the forgot Password Form and it appears to not be working correctly?

I entered my Email Address (that I am already registered with), I then entered Human Challenge, and Submit. 

Then I get an Error "User already used"

The form wont send email as I am already registered which is not the correct logic.

![screenshot 2019-02-20 at 10 37 30](https://user-images.githubusercontent.com/3092445/53085894-d23a9100-34fb-11e9-91e8-a3115573b5f2.png)

It's this function that is not correct:
```
public function forgot_password()
	{
		$data = [];

		$this->form_validation->set_rules('email', 'Email', 'trim|required|valid_email|is_unique[aauth_users.email]');
		$this->form_validation->set_rules('captcha', 'Captcha', 'trim|required|callback_valid_captcha');

		$this->form_validation->set_message('is_unique', 'User already used');

		if ($this->form_validation->run()) {
			//custom your action
			$reset = $this->aauth->remind_password($this->input->post('email'));
			if ($reset) {
				set_message('Your password reset link send to your mail');
			} else {
				set_message('Failed to send password reminder', 'danger');
			}
			redirect('administrator/login', 'refresh');
		} else {
			$data['error'] = validation_errors();
		}

		$this->template->build('backend/standart/administrator/forgot_password', $data);
	}
```

**Comment by ridwanskaterock** [comment]
Actually for reset password is not fineshed, but you can remove this rule for it 

|is_unique[aauth_users.email]

/application/controllers/administrator/Auth.php

you can follow integration with aauth for it 

/application/libraries/Aauth.php


Thanks

http://prntscr.com/mnzp9k
