### ISSUE TITLE
Update Profile userwith error when I upload avatar file. 

### ISSUE THREAD

**Issue by robsongoncalves** [ridwanskaterock/cicool#248]
Hi. I'm trying to Update Profile user but have error when I upload avatar file. Can you help me ?

The folter already have 777 to upload folder but continue the error..
Hi.
1. Make sure the captcha folder has permissions that can be written,
2. to upload image can you see XHR response in browser.
and make sure also the uploads folder is in writeable mode

_Originally posted by @ridwanskaterock in https://github.com/ridwanskaterock/cicool/issues/174#issuecomment-390378360_

**Comment by ridwanskaterock** [comment]
also Make sure the uploads folder has permissions that can be written, 

Thanks

**Comment by robsongoncalves** [comment]
Hi,
   showing de user controller,  the upload_avatar_file need the "user_add"  permission. so when I give this permission the upload worked good.

thanks
