### ISSUE TITLE
What is the api endpoint for user login and user subscribe

### ISSUE THREAD

**Issue by cnngraphics** [ridwanskaterock/cicool#249]
What is the api endpoint for user login and user subscribe

**Comment by ridwanskaterock** [comment]
you can read the doc API for it 

for endpoint is example.com/api/user/login

with params 

username 
password

**Comment by cnngraphics** [comment]
no matter what I do I get this:

{
    "status": false,
    "message": "Invalid API key "
}

any help?

**Comment by ridwanskaterock** [comment]
Hi you can see this video for it https://www.youtube.com/watch?v=PI07LbPwEds
