### ISSUE TITLE
Errors/Warnings After install.

### ISSUE THREAD

**Issue by mwakem** [ridwanskaterock/cicool#25]
Love the product. But I downloaded it yesterday and am getting a bunch of errors. First: date_default_timezone_set(): Timezone ID ‘asia/jakarta’ is invalid After install. I resolved that easy enough.

Now when I login I get the following on the Crud Bulder Page: Message: session_start(): Cannot send session cache limiter – headers already sent (output started at /home/XXXXX/public_html/application/controllers/administrator/Crud.php:2)

Filename: Session/Session.php Line Number: 141

PageBuilder: Severity: Notice

Message: Undefined property: Page::$cc_html

Filename: page-form-builder/config.php

Line Number: 11

What is going on man? Can we expect a fix soon?

**Comment by ridwanskaterock** [comment]
haii thanks,

you try to add the following code to the file

$cc_core->load->library(‘cc_html’); on line 10 cc-content/extensions/page-form-builder/config.php

This occurs on multiple servers in use, can I know about the specs of your server?

thanks

**Comment by ridwanskaterock** [comment]
i will close this issue 
thanks
