### ISSUE TITLE
hi, support question about your script

### ISSUE THREAD

**Issue by inglesuniversal** [ridwanskaterock/cicool#250]
I created a MySQL database under php 5.6, so I want to know if your script would support opening and working with existing databases, so I can build APIs a get info and records listed in JSON with my current data?

Is that available of possible with CICOOL script?

Thanks

**Comment by ridwanskaterock** [comment]
Yes for cicool possible installed on existing data on database, but for core system need created selft database for make it work.

for API can return JSON data get from database

**Comment by inglesuniversal** [comment]
Ok, I think I got that right... Thanks!

I see your script has only 1 table as DEFAULT

How can I create my own Tables from scratch? What is the preferred route?

And at this point, how can I import my own tables from the same server (like I mentioned before), so they can also be used inside this project.

Thanks

**Comment by inglesuniversal** [comment]
Hi, besides the question I submitted above... I was able to create a New Form, for the URL I entered in the field I created is NOT saving it correctly because it has a %20 character code. How can I allow your script to store %20 (spaces web character code) and also to verify that the URL ends with .mp3

Here is the example of the last characters of the url

https://mydomain.com/audio/20190320%20TD%20MASTER%20SUBMIX%20CW%20FIX%20MIX.mp3

Please help

**Comment by ridwanskaterock** [comment]
follow this https://www.php.net/manual/en/function.urlencode.php

Thanks
