### ISSUE TITLE
Menu => Group Privilage

### ISSUE THREAD

**Issue by marlo1973** [ridwanskaterock/cicool#252]
If I create a menu entry I can select the group under "Goup Privilage". If I select the group Member for a menu entry, then the menu entry should not be displayed if I am not logged in as frontend user or?

**Comment by ridwanskaterock** [comment]
For user member or other group you can manage access on module access as admin you can access all features in backend system

**Comment by marlo1973** [comment]
You didn't read my question, did you? If I create a new menu item in the top menu and select a corresponding group under "Group Privilage", the menu item will still be displayed in the front end even though I am not logged in.

Unfortunately, the system does not work as promised.

**Comment by cnngraphics** [comment]
For 3 years I have been trying to get this cicool to work for me..  complete waste of time... I agree with this user...
The support person here does not seem to answer questions properly.

**Comment by marlo1973** [comment]
Hi cnngraphics, that sounds really bad too! - very sad.

**Comment by ridwanskaterock** [comment]
Ok sorry if I fail to understand it
yes, for the front page I haven't tried adding for permissions.

only on the backend that works on the menu permissions

you can add this code on 

cc-content\themes\cicool\views\navigation.php

http://prntscr.com/n3zy5q

```php
<?php foreach (get_menu('top-menu') as $menu): ?>
                    <?php if (app()->aauth->is_allowed('menu_'.$menu->label)): ?>
                        <li>
                            <a class="page-scroll" href="<?= site_url($menu->link); ?>"><?= $menu->label; ?></a>
                        </li>
                    <?php endif ?>
            	<?php endforeach; ?>
```

If support wants to be good and private and development assistance, please try to upgrade to an extends license  it will help our development :) @cnn
