### ISSUE TITLE
Blank page error in CRUD Builder

### ISSUE THREAD

**Issue by abhisekjaiswal** [ridwanskaterock/cicool#257]
I am not able to use the crud builder as it is showing an error can you please help us solve the issue so we can proceed further creating the CRUD and REST API's.

Thanks in advance.

Below is the screenshot attached.

<img width="1113" alt="Database_Error_and_Notes" src="https://user-images.githubusercontent.com/28065485/57869712-338ea980-7838-11e9-8f93-0f2946103757.png">

**Comment by ridwanskaterock** [comment]
Hi 


you can set it to full group by call url

yourdomain.com/web/set_full_group_sql

or run sql stmt on phpmyadmin

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
