### ISSUE TITLE
Missing param aauth->get_user_groups() => user profil in backofffice

### ISSUE THREAD

**Issue by Shakalu** [ridwanskaterock/cicool#258]
Hi,

File : /application/views/backend/standart/administrator/user/user_view.php
`<?php foreach($this->aauth->get_user_groups() as $row): ?>`
replace by
`<?php foreach($this->aauth->get_user_groups($user->id) as $row): ?>`

Without this param, the ID used by default is the current logged admin ID.
Issue : Every member show the same groups like the admin.

Regards.

**Comment by ridwanskaterock** [comment]
Hi 
ok thanks for report 
i will fix on the next version 

thanks you :)

**Comment by ridwanskaterock** [comment]
Fixed in v3.0.0

Thanks
