### ISSUE TITLE
issue after install

### ISSUE THREAD

**Issue by spham** [ridwanskaterock/cicool#259]
design issue after install and try to add crud . i miss something ?

<img width="1111" alt="Image 2019-05-30 at 2 17 59 PM" src="https://user-images.githubusercontent.com/1083631/58632623-6b8cf680-82e6-11e9-9047-70a198d8ad30.png">

**Comment by ridwanskaterock** [comment]
run this query first 

```sql
 set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
```
for activate fullgroup SQL
