### ISSUE TITLE
It would be possible this trick on function render()?

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#26]
Hello,

I am trying to open an iframe on javascript pop up, I can make but show all template data, the iframe contents a crud page from cicool, I believe than I want the Admin Classes to work fine.

I found in code this function:

public function render($view = '', $data = array(), $bool = FALSE)
    {
        $this->template->enable_parser(false);
        $this->template->set_partial('content', $view, $data);
        $this->template->build('backend/standart/main_layout', $data);
    }

Are there any possibility to make something same as:

public function render($view = '', $data = array(), $bool = FALSE)
    {
        if ($no_template_admin == '1')
        {
                 $this->template->enable_parser(false);
                 $this->template->set_partial('content', $view, $data);
                 $this->template->build('backend/standart/main_layout_no_template', $data);
         } 
         elseif ($no_template_admin == '0')
         {
                 $this->template->enable_parser(false);
                 $this->template->set_partial('content', $view, $data);
                 $this->template->build('backend/standart/main_layout', $data);
          }
          else
          {
            exit ('error in function render bad variable $no_template_admin defined on application / core / My_Controller.php estimated line around 440');
   
           }
    }

If isn't possible I want to find other possibilities, If this solution is good I continue with it creating file main_layout_no_template.php and next steps required.

Thanks a lot.

**Comment by ridwanskaterock** [comment]
yes it's better like that, making different layouts for each view in need, and do not remove some elements of the existing layout

it's a nice solution

**Comment by R3N3G** [comment]
Ok,

In that file was the correct file to put $no_template_admin variable. Do you believe?

Thank you.

**Comment by ridwanskaterock** [comment]
yes no admin template you can place it as a parameter to a function,

you want to change the overall layout for all modules?

**Comment by R3N3G** [comment]
At this moment, I only want crud and form modules

**Comment by R3N3G** [comment]
Can you give me the first step about do it? I have trouble choosing the exact moment for loading variable before render function, 

Sorry

Thank you

**Comment by R3N3G** [comment]
Hello?

**Comment by ridwanskaterock** [comment]
Sorry i forget for it :)

can you give me screenshoot about error ?

You can see the error response by showing the console on web browser, 

Thanks

**Comment by R3N3G** [comment]
No, I have not error, I don't know where put code, I want to create a new function, How Can I change $no_admin_template before use render, When Cicool loads headers?

Thanks a lot.

**Comment by ridwanskaterock** [comment]
in controller you can use this function 

`$this->render('backend/standart/dashboard', $data, false, 1);`
// 1 is no template 

and in My_controller in render function you can use this function 
```

public function render($view = '', $data = array(), $bool = FALSE, $no_admin_template = '')
    {
        
    }
```
if this is what you want, sorry if I do not understand the whole :)
