### ISSUE TITLE
After clean install at Page 3 of new install

### ISSUE THREAD

**Issue by iamadj63** [ridwanskaterock/cicool#263]
This is a screen shot which shows the page number Site Address
![screenshoterror](https://user-images.githubusercontent.com/32269282/58864640-4b42aa80-86df-11e9-8d9f-3f5ef8d4b9f7.png)
/sys_users/wizzard/setup/3

and in the main page 
An Error Was Encountered
The action you have requested is not allowed.

**Comment by ridwanskaterock** [comment]
Hi can you active debug mode dorst by change environtment on index.php to
development

And change csrf to false on application/config/config.php

Pada tanggal Sel, 4 Jun 2019 15.42, iamadj63 <notifications@github.com>
menulis:
