### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by arsenkrylov** [ridwanskaterock/cicool#264]
I've been using Cicool for a while, but now I cannot login with my credentials. Email and password are definitely correct. Forgot Password page doesn't send an email to reset the password. 
What shall I do to get to my admin panel?

**Comment by arsenkrylov** [comment]
Ok, I fixed it by generating a hash and inserting it into DB manually. But I would like to know how to fix it if it happens again in future in an easy way.

**Comment by ridwanskaterock** [comment]
Yes for forgot password currently not avaiable, but as admin you can change
user password on user management

Thanks

Pada tanggal Jum, 7 Jun 2019 21.13, arsenkrylov <notifications@github.com>
menulis:

**Comment by arsenkrylov** [comment]
Thanks, I am talking about the admin password has become invalid (though I did not change it). So I could not access the cicool at all.

**Comment by ridwanskaterock** [comment]
Ok i will consider this on next https://github.com/ridwanskaterock/cicool/issues/274
