### ISSUE TITLE
data table - admin side and user side

### ISSUE THREAD

**Issue by sheikhrehman** [ridwanskaterock/cicool#267]
First of all, I use the current user_id option to give access to users to their listings only. But after adding this option in table admin can't able to see all users data then I saw admin's comment 
`    public function filter_avaiable() {
        if (!$this->aauth->is_admin()) {
            $this->db->where('user_id', get_user_data('id'));
        }
        return $this;
    }
`
its fixed now. admin can able to see all users data but the problem is when admin try to edit or correct user listing and hit enter. The user_id of user removed and the user_id of admin replace that.
Now I want a solution for this
when admin edit user listing the user_id should not be changed.

**Comment by ridwanskaterock** [comment]
Even you create crud for this table you can uncheck this field on crud config on update data 

![image](https://user-images.githubusercontent.com/9270445/60405593-53591180-9bdb-11e9-8b4f-d9780a02aeac.png)
