### ISSUE TITLE
2 cruds have user_id

### ISSUE THREAD

**Issue by sheikhrehman** [ridwanskaterock/cicool#269]
my 2 cruds have user id

crud1: restaurant
crud2: foodmenu (food menu > 1 option linked to restaurant to select restaurant id)

and both tables have user_id table and current user_id selected

but facing this error in foodmenu crud when user_id = current_user_id

A Database Error Occurred
Error Number: 1052

Column 'user_id' in where clause is ambiguous

SELECT * FROM `foodmenu` LEFT JOIN `resturant` ON `resturant`.`id` = `foodmenu`.`res` WHERE `user_id` = '1' AND (`foodmenu`.`title` LIKE '%%' OR `foodmenu`.`res` LIKE '%%' OR `foodmenu`.`user_id` LIKE '%%' ) ORDER BY `foodmenu`.`id` DESC LIMIT 10

Filename: F:/wamp64/www/cicool/cicool/system/database/DB_driver.php

Line Number: 691

**Comment by ridwanskaterock** [comment]
Ok thanks i will create prefix on where condition on CRUD builder

**Comment by ridwanskaterock** [comment]
Fixed in v3.0.0
