### ISSUE TITLE
Crud page will not open correctly

### ISSUE THREAD

**Issue by iamadj63** [ridwanskaterock/cicool#270]
When I open the crud page it opens but see screenshot.

This is after a clean install from a new zip with a new database.
![crud-screenshot](https://user-images.githubusercontent.com/32269282/61200676-71129480-a70c-11e9-87be-d5fb78485022.png)

I printed this from the view source page. But this is a clean install;

<h1>A Database Error Occurred</h1>
--
  | <p>Error Number: 1055</p><p>Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'tssecuri_admintss.crud_input_type.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by</p><p>SELECT *
  | FROM `crud_input_type`
  | GROUP BY `validation_group`</p><p>Filename: models/Model_crud.php</p><p>Line Number: 85</p>	</div>

**Comment by ridwanskaterock** [comment]
Hi for this issue you can try access 

yoursite.com/web/set_full_group_sql

or direct running on sql admin 


```sql
 set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
 set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
```sql

thanks

**Comment by iamadj63** [comment]
Really don't understand where and what to do with that answer.
Where is that file

**Comment by ridwanskaterock** [comment]
access on your site like localhost/web/set_full_group_sql

or run this script on PHPmyadmin 

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
 set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
