### ISSUE TITLE
Foreign table  displays id from foreign table than displaying select list

### ISSUE THREAD

**Issue by sdeskapp** [ridwanskaterock/cicool#271]
HI Ridwan,

Facing an issue, I have a form with table student record and another table which has country table.

Now i have used select option and referring the foreign table to display the list.

Now i see the list in Add record - Input form
When i open the view record to see it show the ID and not the country like India and it show 34 - which is the reference id.
But when i click update record, Country drop down is visible to edit and show country and not number 

Please help

Example

Add record - Working
--------------
![image](https://user-images.githubusercontent.com/52919042/61214569-d9ba3b00-a725-11e9-870a-8e41f153c12a.png)

View record.   -Not Working
--------------

![image](https://user-images.githubusercontent.com/52919042/61214616-fbb3bd80-a725-11e9-8f77-09a62ab63e05.png)

Update record   - Works Fine
----------------
![image](https://user-images.githubusercontent.com/52919042/61214665-200f9a00-a726-11e9-8aba-d660b8aca198.png)

**Comment by ridwanskaterock** [comment]
for example you can setting  like that 

![image](https://user-images.githubusercontent.com/9270445/61350800-f32cc580-a892-11e9-9050-4141150e2c6b.png)


Thanks

**Comment by sdeskapp** [comment]
i think that is how its is correct me if i am wrong,

![image](https://user-images.githubusercontent.com/52919042/61352081-1606ac00-a88a-11e9-9dc1-e7ca3c45d41c.png)

**Comment by ridwanskaterock** [comment]
Yes that's correct i think, what the result ?

**Comment by sdeskapp** [comment]
Still the same it fetching the ID 

![image](https://user-images.githubusercontent.com/52919042/61436512-97c50b00-a958-11e9-9a83-a5b477086151.png)


Database - 
![image](https://user-images.githubusercontent.com/52919042/61436573-b4f9d980-a958-11e9-944d-03d44f418f3b.png)

Foreign table value.

![image](https://user-images.githubusercontent.com/52919042/61436636-dbb81000-a958-11e9-8450-d0ce19fa94f6.png)

**Comment by ridwanskaterock** [comment]
Fixed in v3.0.0

you can try use latest version in codecanyoun 

thanks
