### ISSUE TITLE
Crud

### ISSUE THREAD

**Issue by vdmgeh** [ridwanskaterock/cicool#272]
Hi Ridwan,
Great product.
Everything works as expected, but I am having a small issue with the crud builder.
1. I build a new form example: "Promotions"
2. When I go to the crud builder and try to load a new crud, I don't see the new table, all I see is "blog_category"

Am I doing something wrong?
Please assist.

**Comment by ridwanskaterock** [comment]
Hello 

if you create from form builder 

you can access for it on 

https://cicool.go-moment.com/administrator/form example 

![image](https://user-images.githubusercontent.com/9270445/61350988-9c73bb80-a893-11e9-88d8-c328a10c2b08.png)


on this page you can manage form user and input aan data 

Thanks
