### ISSUE TITLE
Have a problem creating field label/placeholder with non-latin text

### ISSUE THREAD

**Issue by everisk** [ridwanskaterock/cicool#28]
Hi

I cannot seem to be able to create field label or placeholder with non-latin text (specifically Thai). Step to replicate the problem and errors shown are here
https://drive.google.com/file/d/0BzMrA3XoMXZESHdDdnVaYkZtNzA/view?usp=sharing

**Comment by mtaraabi** [comment]
آHi there, 

It might be a database collation issue. I am a user just like you, try to use collation type that compatible with language. For example, I am using **utf8mb4_unicode_520_ci** to deal with Arabic language. Try this while you are waiting for the owner support. 

![screen shot 2017-02-22 at 3 32 30 pm](https://cloud.githubusercontent.com/assets/22406551/23211656/2f31a856-f914-11e6-8b92-2423f1b1c166.png)


Cheers

**Comment by mtaraabi** [comment]
try this **tis620_thai_ci**

**Comment by ridwanskaterock** [comment]
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

You can try add meta like that,

In application/views/backend/standart/main_layout.php


Pada tanggal 22 Feb 2017 19.48, "mtaraabi" <notifications@github.com>
menulis:

**Comment by ridwanskaterock** [comment]
this issue resolved ? i will close this issue :)
