### ISSUE TITLE
Join on tables for CRUD

### ISSUE THREAD

**Issue by vdmgeh** [ridwanskaterock/cicool#292]
Hi
I have version 2.8.0

There is an error in Crud list when including Select Multiple

In the list created the id is always 1.
I think the joined table id is being used.
Do you have a fix for this please, URGENT.

See Images attached from DB and List
<img width="1440" alt="Screenshot 2019-07-19 at 16 39 42" src="https://user-images.githubusercontent.com/52945389/61543504-e9968f80-aa43-11e9-87a3-1817b0d0c638.png">
<img width="1085" alt="Screenshot 2019-07-19 at 16 39 48" src="https://user-images.githubusercontent.com/52945389/61543521-f3b88e00-aa43-11e9-8851-ceaab365aaaa.png">

**Comment by vdmgeh** [comment]
<img width="1163" alt="Screenshot 2019-07-19 at 16 41 55" src="https://user-images.githubusercontent.com/52945389/61543614-26fb1d00-aa44-11e9-961c-020802da357c.png">

**Comment by vdmgeh** [comment]
Also you will see in images "Group: and "Area" is showing id in the list not description as in Database Table

**Comment by ridwanskaterock** [comment]
Yes for select can you make sure field reff select to primary key and field label select to your label for example 

![image](https://user-images.githubusercontent.com/9270445/61931585-34b42380-afab-11e9-8ca6-85a0b18789c2.png)

**Comment by ridwanskaterock** [comment]
In version 3 i have fixed for issue select and select multiple 

Thanks

**Comment by martonoskom** [comment]
![image](https://user-images.githubusercontent.com/25054846/62916572-2d6e8180-bdc3-11e9-9a38-e0b379876865.png)


Mas Bagaimana cara nya Join table, di saya tidak muncul field untuk foreignkey nya?

**Comment by martonoskom** [comment]
![image](https://user-images.githubusercontent.com/25054846/62930550-d8dcfd80-bde6-11e9-8b76-c8aa10f18e80.png)

Relasi join tabel nya tidak muncul mas?

**Comment by ridwanskaterock** [comment]
coba ke tab network terus liat response XHRnya mas 
![image](https://user-images.githubusercontent.com/9270445/62934933-0a0dfb80-bdf0-11e9-9632-9602bff5f139.png)

**Comment by martonoskom** [comment]
![image](https://user-images.githubusercontent.com/25054846/62935272-e26b6300-bdf0-11e9-9799-61e49cb1d372.png)

**Comment by ridwanskaterock** [comment]
coba mas sesuaikan code di bagian itu 

![image](https://user-images.githubusercontent.com/9270445/62936770-dda8ae00-bdf4-11e9-9cf8-3cfe869c795f.png)


![image](https://user-images.githubusercontent.com/9270445/62936790-e5685280-bdf4-11e9-83ba-33c95a6eb988.png)



itu udah di fix di versi 3.x
