### ISSUE TITLE
Bug version 3.0 module to ucfirst to lowercase 

### ISSUE THREAD

**Issue by ridwanskaterock** [ridwanskaterock/cicool#295]
![image](https://user-images.githubusercontent.com/9270445/62116185-f0df5800-b2e3-11e9-8ae3-fcc85777bb63.png)

change to strtolower on 

`modules/rest/controller/backend/Rest.php`

**Comment by searchy2** [comment]
Tried this fix but the rest tool is still broken. 
![MaxthonSnap20190731000011](https://user-images.githubusercontent.com/19896174/62185057-71bf4380-b326-11e9-9e3e-798d480f0433.png)

**Comment by ridwanskaterock** [comment]
Hi sorry for that can you follow for this https://github.com/ridwanskaterock/cicool/issues/293 

Thanks

**Comment by searchy2** [comment]
Any idea why this happens now? It seems Aauth cannot be loaded.
![MaxthonSnap20190731204518](https://user-images.githubusercontent.com/19896174/62259638-a38ee380-b3d4-11e9-99e6-95471f768f11.png)

**Comment by ridwanskaterock** [comment]
Hi can you try for replace to core/MY_Controller.php

Thanks

**Comment by searchy2** [comment]
What should I replace in that file?

**Comment by ridwanskaterock** [comment]
I think load this section

[image: image.png]

**Comment by searchy2** [comment]
Sorry, the image doesn't when you reply from your email. Thanks for looking into this!

**Comment by ridwanskaterock** [comment]
![image](https://user-images.githubusercontent.com/9270445/62264869-0a9baf00-b44c-11e9-8cb7-2ccf83ccc1a7.png)

sorry

**Comment by searchy2** [comment]
It's definitely set, that's what I don't understand.
![MaxthonSnap20190731230750](https://user-images.githubusercontent.com/19896174/62265022-28372d00-b3e8-11e9-998a-c4b344dd38f1.png)
 The autocomplete is interpreting the Aauth library as having an extra ' in front of it. Perhaps that points towards the problem?
![MaxthonSnap20190731230907](https://user-images.githubusercontent.com/19896174/62265067-4ac94600-b3e8-11e9-9fee-040c198910e0.png)

**Comment by searchy2** [comment]
Just reinstalled. Confirmed this is definitely an issue.

**Comment by ridwanskaterock** [comment]
Yes i am update for it in latest version in codecanyon, with update v 3.0.2

**Comment by searchy2** [comment]
Thank you, hope to see it soon!

**Comment by vin111** [comment]
I managed to get the token, when will you release the updated version?
![Cattura](https://user-images.githubusercontent.com/25017968/64065739-aa965500-cc11-11e9-9df6-5863b4e3f91d.JPG)
