### ISSUE TITLE
Not able to make Cicool work from long time

### ISSUE THREAD

**Issue by TruebodhLearning** [ridwanskaterock/cicool#296]
Hi Team,

I have been trying to create form, and crud based on the table. We have been facing couple of issues like below, every time we use it, it fails and takes long time to troubleshoot. Now i want it to be working. See what we are doing

1. We create groups, and add users to it. 
2. We create backyard pages (want to create admin dashboard)
3. We create menus based on backyard pages and also give permission to specific groups like (HR), IT etc.
4. We also create menus for Forms and also give permission to specific groups like (HR), IT etc.

We feel all this stuff should give us what we are looking for - Admin Panel for Internal operations. Most of the time only error we see is "Access Denied", the page is not being accessed after login. 

I am ready to share my login details, i wish you to demonstrate such configuration once, or find our what configuration setting is missing.

This is quite urgent, Please look into it.

**Comment by ridwanskaterock** [comment]
For that, have you set the access permissions for each group you choose?

You can set it in part administrator/access for it

Thanks 

![image](https://user-images.githubusercontent.com/9270445/62264982-8b5aab00-b44c-11e9-9029-92f1fc49e0f9.png)
