### ISSUE TITLE
Can't make blog Rest API!

### ISSUE THREAD

**Issue by vpndc** [ridwanskaterock/cicool#299]
I used the following method to get API, but it was unsuccessful. Please help me！
1、Add Rest New : Blog;
2、In Blog，Rest Get a Token;
3、Use admin@admin.com/admin123 ,get the X-Token;
4 、Back to Rest Blog-API ALL, fill in the X-Api-Key、X-Token ,Send , but："message": "Key may not be empty",
-
"error": {"classname": "InvalidArgumentException"
}
}

![image](https://user-images.githubusercontent.com/53701434/62590377-b33f8800-b8fe-11e9-9674-6cf4a142f292.png)

![image](https://user-images.githubusercontent.com/53701434/62590387-bdfa1d00-b8fe-11e9-91cc-ab10f79072f5.png)

The same error occurred when using the official demo website. Please help!

Thank you very much! Look forward your reply!

**Comment by dotcomcraftsmen** [comment]
yes same here , wanted to purchase this but seeing the error stopped can you help with what the issue is .

**Comment by ridwanskaterock** [comment]
Hi can you update or download to latest version for it ?

**Comment by ridwanskaterock** [comment]
Or tr make adjust this function 

![image](https://user-images.githubusercontent.com/9270445/62747666-b1510280-ba7f-11e9-843f-f361bf9c3faf.png)

application/core/My_Controller.php
```php
public function getHeader($key)
    {
        $headers = getallheaders();
        $headers = array_change_key_case($headers, CASE_LOWER);
        $key = strtolower($key);
        if (isset($headers[$key])) {
            return $headers[$key];
        }

        return false;
    }
```

**Comment by vpndc** [comment]
Hi
Thank you! Because I don't know how to upgrade, I just tried to reinstall the new version 3.0 (php 7.2), Get Token: 
Status: undefined OK. 
Please help me, Thanks!

**Comment by vpndc** [comment]
![image](https://user-images.githubusercontent.com/53701434/62748035-b31fc380-ba89-11e9-8404-e4a6964c4a3c.png)

**Comment by ridwanskaterock** [comment]
can you see XHR response for it ? 

![image](https://user-images.githubusercontent.com/9270445/62748382-a3e94780-ba82-11e9-9107-4e512be84147.png)

and following for this issue https://github.com/ridwanskaterock/cicool/issues/293 

just replace files downloaded latest version to old version for update

**Comment by vpndc** [comment]
![image](https://user-images.githubusercontent.com/53701434/62748751-583b9b80-ba8c-11e9-9848-dc64096d33a8.png)
Thank you. 
I saw this error. Please browse the picture.

**Comment by vpndc** [comment]
Hi
I have solved all the above problems, and the solution is to upgrade to the latest version. Now encounter a new problem, testing in the website is normal, I use POSTMAN test there is a problem, how to solve this problem? 
Thank you!

![image](https://user-images.githubusercontent.com/53701434/62764283-162c4d00-bac0-11e9-8563-e4f8ed5a05dc.png)

![image](https://user-images.githubusercontent.com/53701434/62764401-5ee40600-bac0-11e9-82f9-3695592fad8c.png)

**Comment by vpndc** [comment]
![image](https://user-images.githubusercontent.com/53701434/62770855-7a560d80-bace-11e9-9540-8cedf3951b70.png)
**GET request error in Postman, is it necessary to fill in the IP address in API KEY?**
![image](https://user-images.githubusercontent.com/53701434/62770894-92c62800-bace-11e9-8d10-1fbffb28293a.png)

**Comment by jannek09** [comment]
what can I do the key and everything works. But I can't get to the rest of the api externally.

![Bildschirm­foto 2023-02-22 um 18 01 09](https://user-images.githubusercontent.com/93222217/220702695-f0f63fa6-f3f8-466e-8fcf-62d9d04e9512.png)

![Bildschirm­foto 2023-02-22 um 18 02 57](https://user-images.githubusercontent.com/93222217/220702708-d6936879-ba59-46d1-8c4d-d00a7490199f.png)
