### ISSUE TITLE
Example of API Key in URL

### ISSUE THREAD

**Issue by buckr** [ridwanskaterock/cicool#3]
Sorry to bother you again, but could you please give an example of an the API Key in the URL?

Works fine in your API Builder.  I tried using "&api_key=" at the end of the URL and that didn't work.

Example:
 http://localhost/cicool/api/webinv/all&api_key=xxxxxxxxxxxxxxxxxxxxx

I looked through your documentation and video and could not find an example anywhere.

thanks,

buckr

**Comment by ridwanskaterock** [comment]
to rest key request is not placed in the get and post, but put in the request header,

param request header: X-Api-Key: xxxxxxxxxxxvvbvb

example in php scripts quoted http://stackoverflow.com/questions/8115683/php-curl-custom-headers

```
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'X-Api-Key: xxxxxxxxxxxvvbvb',
    'X-Token: tokenexample'
    ));
```


and an example to insert a header in jquery
http://stackoverflow.com/questions/3258645/pass-request-headers-in-a-jquery-ajax-get-call

```
$.ajax({
         url: "host/cicool/api/user/login",
         data: { username: 'name'},
         type: "GET",
         beforeSend: function(xhr){xhr.setRequestHeader('X-Api-Key', 'xxxxxxxxxxxvvbvb');},
         success: function() { alert('Success!' + authHeader); }
      });
```


hopefully understandable,

okay I are ready to support you anytime, please give rewiew in codecanyon friend :)

**Comment by ridwanskaterock** [comment]
cicool automatically generate API doc, you can access the documentation on the API in web application that you created
http://localhost/cicool/apidoc

**Comment by buckr** [comment]
Thanks.  The  ./all" curl works great.  

However, on the ./detail I tried passing parameters using CURLOPT_POSTFIELDS and it errored out with method not found.

$post_data = "inv_id=9998";
"curl_setopt($curl_handle,CURLOPT_POSTFIELDS, $post_data);", 

Should I be using something besides POSTFIELDS to pass parameters?

-buckr

**Comment by ridwanskaterock** [comment]
yes buckr for API bertype GET method, you must add this option on your curl,

curl_setopt ($ch, CURLOPT_POST, 0);


as an example I created curl

yes buck for API bertype GET method, you must add this option on your curl,

curl_setopt ($ch, CURLOPT_POST, 0);


as an example I created curl

$url = 'http://localhost:80/ci-lte-generator/api/blog/detail/?id=1';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'X-Api-Key: 193DD415DEB71B875F1C982788217E4E',
    'X-token: token'
    ));
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_POST, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$res = curl_exec($ch);
curl_close($ch);

echo "<pre>";
print_r(json_decode($res));

and result like this 

![image](https://cloud.githubusercontent.com/assets/9270445/21533557/537fadfe-cd8e-11e6-97e9-2c7eb99b31bb.png)


hopefully can help you

**Comment by buckr** [comment]
Thanks for the great example!  I see now that the url needs to be passed inside of the curl_init.  Once I did that it worked perfectly. 

A couple of enhancement requests for future releases:
1) On the CRUD screen, put the filter at the top (instead of the bottom) so that users can quickly drill down to the record they want to edit.

2)  The 38 tables that cicool added to my user database was a surprise.  I would have preferred that a separate database would have been created.  At minimum, at least allow for the cicool tables to be prefixed so that they can be easily identified and not mixed randomly with all my user tables.

thanks,

-buckr

**Comment by ridwanskaterock** [comment]
Okay buckr nice if everything goes smoothly and can be understood. 
thank you for your input and suggestions are given, and we will update it on the user experience that is easy to use application, we will consider further for positioning the filter and to prefix the name of the table we will soon update for an upcoming feature. thanks you
