### ISSUE TITLE
My issue is not fixed

### ISSUE THREAD

**Issue by drewnyc** [ridwanskaterock/cicool#30]
I have been waiting for help - it is not fixed - I cannot install it!  I will be requesting a refund - I am sure your product is great and I wish I could use it, but I can't which makes it worthless to me.  Unless you can help me to get it to work.  Thanks,

**Comment by R3N3G** [comment]
Hello,

Can you activate logging for php and apache how in this post?

https://github.com/ridwanskaterock/cicool/issues/4

You can post here the logfiles for analyze the problem,
