### ISSUE TITLE
The request API test in the website is normal, uses the POSTMAN remote request to display the error, what reason is caused excuse me? 

### ISSUE THREAD

**Issue by vpndc** [ridwanskaterock/cicool#302]
Hi
Waiting for four days, or did not reply to me, our project is very anxious, please help me thank you! 
The request API test in the website is normal, uses the POSTMAN remote request to display the error, what reason is caused excuse me? 
Thank you!

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by vpndc** [comment]
![image](https://user-images.githubusercontent.com/53701434/62842328-ee1d3380-bce3-11e9-9d55-39ae4a41ab8a.png)
![image](https://user-images.githubusercontent.com/53701434/62842332-fc6b4f80-bce3-11e9-8477-d9dee5d8ab8b.png)

**Comment by ridwanskaterock** [comment]
Hi please place this variable on HEADERS


[image: image.png]


not on param or body

Thanks

**Comment by vpndc** [comment]
Has been resolved, a little later to send you a need to customize the email, please check! Thank you!
