### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by martonoskom** [ridwanskaterock/cicool#304]
![image](https://user-images.githubusercontent.com/25054846/62940310-7b07e000-bdfd-11e9-9d5a-724f6cd46ecb.png)

**Comment by martonoskom** [comment]
Error mas ...? pas di klik see mas

![image](https://user-images.githubusercontent.com/25054846/62942053-b3a9b880-be01-11e9-9d0d-d3be4146ad7b.png)

**Comment by martonoskom** [comment]
sudah di fixing

Sebelum = <?php is_allowed('permission_update', function($permission) use($permission){?>
Sesudah = <?php is_allowed('permission_update', function() use($permission){?>

**Comment by ridwanskaterock** [comment]
oke mas itu pakai versi terakhir dan PHP versi berapa mas ?

**Comment by martonoskom** [comment]
Saya pakai php versi 7.1
