### ISSUE TITLE
Add Extension error

### ISSUE THREAD

**Issue by martonoskom** [ridwanskaterock/cicool#305]
![image](https://user-images.githubusercontent.com/25054846/62985349-2007d480-be61-11e9-93ee-6d00d7801788.png)

![image](https://user-images.githubusercontent.com/25054846/62985376-3d3ca300-be61-11e9-8382-44a3b9481c7c.png)

**Comment by ridwanskaterock** [comment]
coba ikuti issu eini mas 

https://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-failed-to-enable-crypto

bisa di tambah sertifikat di 

di file curl.cainfo 

atau verify di buat false 

![image](https://user-images.githubusercontent.com/9270445/62987706-50ed0700-be6b-11e9-8e2f-8b8b3390b418.png)

![image](https://user-images.githubusercontent.com/9270445/62987719-5e09f600-be6b-11e9-8cf5-e3e834a3571a.png)
