### ISSUE TITLE
Data views Where

### ISSUE THREAD

**Issue by martonoskom** [ridwanskaterock/cicool#306]
![image](https://user-images.githubusercontent.com/25054846/62990894-cb238880-be77-11e9-99d1-a594ec1cb429.png)

mas kalau mau nampilin data Is Print Material = 1 saja bagaimana ?

**Comment by ridwanskaterock** [comment]
bisa di tambah di filter avaiablenya di file modelnya mas 

![image](https://user-images.githubusercontent.com/9270445/62990977-10e05100-be78-11e9-8625-8f0ea93c629b.png)
