### ISSUE TITLE
Error pada saat install di server

### ISSUE THREAD

**Issue by sukirman** [ridwanskaterock/cicool#31]
Mas, saya coba install di server hosting , setelah selesai wizard ada error sbb :
- Message: date_default_timezone_set(): Timezone ID 'asia/jakarta' is invalid
 Filename: core/My_Controller.php 
 Line Number: 24

- A PHP Error was encountered
Severity: Warning
Message: session_start(): Cannot send session cookie - headers already sent by (output started at /home/contohsi/public_html/system/core/Exceptions.php:272)
Filename: Session/Session.php
Line Number: 141

saya sudah lakukan ini :
you try to add the following code to the file
$cc_core->load->library(‘cc_html’); on line 10 cc-content/extensions/page-form-builder/config.php

Tapi error masih muncul.

Mohon bantuannya
Terima Kasih

**Comment by ridwanskaterock** [comment]
Itu pakai PHP versi berapa mas kayanya itu masalah sama date_default_timezone_set 
Karna id asia jakarta mungkin ga terdaftar ?

**Comment by sukirman** [comment]
DH,

Makasih Mas Responnya,

 

Saya rem aja mas jadinya di baris itu.

 

Btw kalo saya ke Dashboard trus ke menu form ada error  massage sbb :

An Error Was Encountered

Unable to load the requested class: ‘cc_html’

 

Maklum baru pertama kali install jadi agak bingung.

 

 

 

Regads,

Sukirman

**Comment by ridwanskaterock** [comment]
untuk yang issue Unable to load the requested class: ‘cc_html’

itu terjadi di beberapa server, karna autoload yang ga berjalan, 

mas bisa ikutin issue ini https://github.com/ridwanskaterock/cicool/issues/25

trimakasih
