### ISSUE TITLE
Error 502 Bad Gateway nginx

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#315]
Hi, I installed the latest version of Cicool 3.00. Locally it works but on the production server
after installing it from now on the setting page (administrator/setting) returns error 502 bad gateway, and after some request I get the error 502 Bad Gateway
nginx on the whole site. I did various tests I also installed new server.
You can help me thanks
![bad502](https://user-images.githubusercontent.com/25017968/64108719-e1897980-cd7d-11e9-88c4-42f54fed3cd3.gif)

**Comment by ridwanskaterock** [comment]
Can you see erroe log on application/logs and log on web panel for that ?

Thanks

Pada tanggal Sen, 2 Sep 2019 17.37, vin111 <notifications@github.com>
menulis:

**Comment by vin111** [comment]
Hello, no log is generated.
By debugging I saw that the problem concerns the set_option() which generates duplicate records in the cc_options table in the database and therefore the function get_option() loops and generates error 502.
The mysql version is 5.5.60 (while in local it works is 10.x)
Plesk by default installs mysql 5.5.60
You can help me?
Thanks

![Cattura](https://user-images.githubusercontent.com/25017968/64128584-85dbe200-cdb7-11e9-88a2-93dc16eb67ce.JPG)

**Comment by vin111** [comment]
I updated the MariaDb database on the plesk server at 10.2 but I have the same problem

**Comment by vin111** [comment]
But finally I resolved my upstream problem not with changing the fastcgi settings but with changing it to exactly this settings:

Plesk > Subscriptions > domain.tld > Apache & Nginx Settings > Additional Nginx Directives.

proxy_buffering on;
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
