### ISSUE TITLE
Merubah Format Tanggal

### ISSUE THREAD

**Issue by rezadm** [ridwanskaterock/cicool#320]
Selamat malam mas saya pengguna baru cicool dan masih sangat pemula.

Saya membuat crud dengan menggunakan format tanggal. Pada saat saya add data, format tanggalnya dimulai dari yyyy-mm-dd. Bagaimana cara merubahnya? Saya udah coba baca2 baik dari forum tanya jawab di sini dan situs luar tapi blm menemukan solusi. Terima kasih sebelumnya

**Comment by ridwanskaterock** [comment]
Halo.

Untuk rubah format bisa melalui view

Coba follow isaue ini mas
https://github.com/ridwanskaterock/cicool/issues/317

Pada tanggal Sab, 21 Sep 2019 18.22, rezadm <notifications@github.com>
menulis:
