### ISSUE TITLE
Database Connection Error on Installation

### ISSUE THREAD

**Issue by murugapan** [ridwanskaterock/cicool#322]
I installed the cicool software. I get an error "Invalid username" when i tried to configure the database connection. I am using local server.

![dbconfig](https://user-images.githubusercontent.com/1711953/65647155-59bb2600-e030-11e9-908f-c604dc2c19bf.jpg)
![dbconfig error](https://user-images.githubusercontent.com/1711953/65647160-5f187080-e030-11e9-8265-e6496264fb6a.jpg)

**Comment by ridwanskaterock** [comment]
Hi
What your version fo cicool ?

**Comment by murugapan** [comment]
Hi,
I dont know what version it is. There is nowhere the download says that but name of the zip file i just downloaded is codecanyon-Vcj50zEI-cicool-page-form-rest-api-and-crud-generator.
My Purchase code: 4dc02fa1-6014-41db-a2e3-4622745dba49

Regards from, Murugappan Ramanathan 

    On Thursday, 26 September 2019, 7:46:25 am MYT, Muhamad Ridwan <notifications@github.com> wrote:  
 
 Hi
What your version fo cicool ?

**Comment by ridwanskaterock** [comment]
can you install latest version on codecanyon, or you can remove _ on email
use alphanumeric only

**Comment by murugapan** [comment]
Whatever version i download from Codecanyon, i still get the same error. Please help

Regards from, Murugappan Ramanathan 

    On Thursday, 26 September 2019, 2:23:33 pm MYT, Muhamad Ridwan <notifications@github.com> wrote:  
 
 can you install latest version on codecanyon, or you can remove _ on email
use alphanumeric only

**Comment by ridwanskaterock** [comment]
HI can you share access to your application on hosted ? 
I will help you for install, you can share on my email 

Thanks

**Comment by murugapan** [comment]
Sorry, we cannot allow that. I installed it on my local PC under XAMPP. 

Regards from, Murugappan Ramanathan 

    On Sunday, 29 September 2019, 11:09:49 pm MYT, Muhamad Ridwan <notifications@github.com> wrote:  
 
 
HI can you share access to your application on hosted ?
I will help you for install, you can share on my email

Thanks

**Comment by murugapan** [comment]
I decided to throw it away.
