### ISSUE TITLE
Duplicate records pada view table

### ISSUE THREAD

**Issue by zkenstein** [ridwanskaterock/cicool#326]
Gan,

Di table view saya records data kelihatan duplicate, tetapi kalau di check di DB datanya hanya satu, ini kejadian pada table list dari crud. Bagaimana cara perbaiki nya mas?

Makasih

**Comment by ridwanskaterock** [comment]
Bisa di kirim gan modelnya ke email saya ? 

Trimakasih

**Comment by zkenstein** [comment]
Udah solved gan, gan untuk buat link dengan filternya lebih dari satu field gmn gan?

Makasih untuk aplikasi yg luar biasa
