### ISSUE TITLE
Issue installing on my server 

### ISSUE THREAD

**Issue by activegear** [ridwanskaterock/cicool#33]
A PHP Error was encountered

Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 118

Backtrace:

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 98
Function: library

File: /home/actmain/public_html/leaderboard/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/actmain/public_html/leaderboard/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/actmain/public_html/leaderboard/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 568

Backtrace:
An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: /home/actmain/public_html/leaderboard/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 120

Backtrace:

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 98
Function: library

File: /home/actmain/public_html/leaderboard/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/actmain/public_html/leaderboard/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: fopen(f58a0d0b2fa4cea8303927fe17c8ae2a0c47957c): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 157

Backtrace:
A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct ()

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by ridwanskaterock** [comment]
it's issue from codeigniter system, 
maybe you can resolve by following this issue 
http://stackoverflow.com/questions/31042456/session-error-in-codeigniter

you can try, change the value of config, 

in file application/config/config.php 

`$config['sess_save_path'] = sys_get_temp_dir();`

thanks

**Comment by activegear** [comment]
Same issue 


A PHP Error was encountered

Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 118

Backtrace:

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 98
Function: library

File: /home/actmain/public_html/leaderboard/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/actmain/public_html/leaderboard/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/actmain/public_html/leaderboard/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 568

Backtrace:
An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: /home/actmain/public_html/leaderboard/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 120

Backtrace:

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 116
Function: library

File: /home/actmain/public_html/leaderboard/application/core/My_Loader.php
Line: 98
Function: library

File: /home/actmain/public_html/leaderboard/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/actmain/public_html/leaderboard/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: fopen(33937dc863a099b7442e1b14fd7c3712c147350e): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 157

Backtrace:
A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct ()

Filename: Unknown

Line Number: 0

Backtrace:
