### ISSUE TITLE
Api Buider Problem

### ISSUE THREAD

**Issue by feryield** [ridwanskaterock/cicool#338]
Hello,

I made an Api and this was generated as a crud on api folder.

![api_controler](https://user-images.githubusercontent.com/47767579/68918808-55a8ac00-0735-11ea-9f7f-8102ed7e8abf.jpg)
![api_test1](https://user-images.githubusercontent.com/47767579/68918922-c6e85f00-0735-11ea-8beb-58031fdc8b55.jpg)
![api_test2](https://user-images.githubusercontent.com/47767579/68918925-c8198c00-0735-11ea-9a4f-ac581b403dfc.jpg)
![api_test3](https://user-images.githubusercontent.com/47767579/68918928-c9e34f80-0735-11ea-9eed-abecf34b344b.jpg)

**Comment by ridwanskaterock** [comment]
Hello can you download for lates version for it ? 


Thanks

**Comment by ridwanskaterock** [comment]
Fixed on latest version Thanks
