### ISSUE TITLE
Unable to load the requested language file: language/id/web_lang.php

### ISSUE THREAD

**Issue by aanelzam93** [ridwanskaterock/cicool#344]
i have error like this, how to resolve ?

**Comment by ridwanskaterock** [comment]
Hi you changed language manually on code to id ? for indonesian language avaiable on language/indonesia/folder 

Thanks

**Comment by aanelzam93** [comment]
cicool belum support PHP 7.2/7.3 kah mas ?

Pada tanggal Rab, 29 Jan 2020 pukul 13.23 Muhamad Ridwan <
notifications@github.com> menulis:

**Comment by ridwanskaterock** [comment]
7.2 harusnya sudah mas 7.3 masih proses

**Comment by aanelzam93** [comment]
oke di tunggu untuk yang 7.3 mas

Pada tanggal Rab, 29 Jan 2020 pukul 13.31 Muhamad Ridwan <
notifications@github.com> menulis:

**Comment by aanelzam93** [comment]
malam mas kalau  apakah bisa cicool ini multiple database ?
