### ISSUE TITLE
form add rest API

### ISSUE THREAD

**Issue by martonoskom** [ridwanskaterock/cicool#348]
https://prnt.sc/qs5dxq
tidak bisa add rest API ?

**Comment by ridwanskaterock** [comment]
coba follow issue ini mas
https://github.com/ridwanskaterock/cicool/issues/270 / run sql query ini

set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
set session sql_mode=’STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION’;
