### ISSUE TITLE
When the next update will be released?

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#349]
When the next update will be released?

**Comment by ridwanskaterock** [comment]
Chain input type will releasebin a week,
Like si category

Tree input,
Country, state city Ajax

Thanks

Pada tanggal Rab, 29 Jan 2020 04.07, vin111 <notifications@github.com>
menulis:

**Comment by ridwanskaterock** [comment]
Chain input release in latest version, you can download it thanks
