### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jnachman123** [ridwanskaterock/cicool#35]
when i unzip and extract and browse to the cicool folder, it redirects to /cicool/wizzard/setup  
but it cannot be found?

**Comment by ridwanskaterock** [comment]
What if you access the URL
/cicool/wizard/setup/index.php
What it does not bring notfound
if not then you have to change your apache mod_rewrite settings

thanks

**Comment by jnachman123** [comment]
i am on shared hosting, do i change this in the .htaccess page?

**Comment by jnachman123** [comment]
Thank you please close i have configured - i have another error now. please check new post

**Comment by ridwanskaterock** [comment]
okay, i have been reply your issue, check it, 

thanks i will close this issue
