### ISSUE TITLE
No setup wizard installation

### ISSUE THREAD

**Issue by ivhokt** [ridwanskaterock/cicool#350]
I am using bluehost. have uploaded the files and run, but there is no wizard. Where did i do wrong?

Thank you

**Comment by ridwanskaterock** [comment]
Hi can you remove application/config/site.php file if exist

Thanks

Pada tanggal Sab, 1 Feb 2020 07.54, ivhokt <notifications@github.com>
menulis:

**Comment by ivhokt** [comment]
OK, I will try that. Thanks for the quick reply!!!

**Comment by ivhokt** [comment]
Hi, i have just tried - went through all 3 wizzard steps

Howe\ver it showed the error page
https://qlickmarketing.com/api/wizzard/setup/3api_

Can i solve this?

Thank you

**Comment by ivhokt** [comment]
A PHP Error was encountered
Severity: 8192

Message: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

Filename: libraries/Form_validation.php

Line Number: 1238

Backtrace:

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 218
Function: run

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 282

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent

Filename: Session/Session.php

Line Number: 294

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 304

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 314

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 315

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 316

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 317

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: Session/Session.php

Line Number: 375

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

Filename: drivers/Session_files_driver.php

Line Number: 108

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: session_set_save_handler(): Cannot change save handler when headers already sent

Filename: Session/Session.php

Line Number: 110

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: session_start(): Cannot start session when headers already sent

Filename: Session/Session.php

Line Number: 143

Backtrace:

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/libraries/Aauth.php
Line: 97
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home2/qlickmar/public_html/api/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 238
Function: library

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home2/qlickmar/public_html/api/system/core/Exceptions.php:271)

Filename: core/Input.php

Line Number: 408

Backtrace:

File: /home2/qlickmar/public_html/api/application/libraries/Cc_app.php
Line: 195
Function: set_cookie

File: /home2/qlickmar/public_html/api/application/libraries/Cc_app.php
Line: 131
Function: optionExists

File: /home2/qlickmar/public_html/api/application/helpers/app_helper.php
Line: 651
Function: addOption

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 251
Function: add_option

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home2/qlickmar/public_html/api/system/core/Exceptions.php:271)

Filename: helpers/url_helper.php

Line Number: 564

Backtrace:

File: /home2/qlickmar/public_html/api/modules/wizzard/controllers/Wizzard.php
Line: 256
Function: redirect

File: /home2/qlickmar/public_html/api/index.php
Line: 339
Function: require_once

**Comment by ivhokt** [comment]
hi, now the error is

502 Bad Gateway
nginx/1.17.6

**Comment by ridwanskaterock** [comment]
Hi what's your php version ?

Pada tanggal Sab, 1 Feb 2020 09.16, ivhokt <notifications@github.com>
menulis:

**Comment by ivhokt** [comment]
hello
PHP 7.2 (ea-php72)

**Comment by ridwanskaterock** [comment]
Can you try on php 7.1 ?

If still problem you can share ftp access and wrb access for it to
ridwanskaterocks@gmail.com

Pada tanggal Sab, 1 Feb 2020 10.49, ivhokt <notifications@github.com>
menulis:

**Comment by ivhokt** [comment]
ok, i will try now. Thanks

**Comment by ivhokt** [comment]
Hi, I tried but no change. I have just emailed u the login details. Hope you can help, Thank You
