### ISSUE TITLE
Latest Update gives me this error on fresh install Bitnami AWS LAMP 7.3.11

### ISSUE THREAD

**Issue by inglesuniversal** [ridwanskaterock/cicool#354]
Got this ERROR could not finish installation wizard.

A PHP Error was encountered
Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: /opt/bitnami/apache2/htdocs/cicool/application/third_party/MX/Router.php
Line: 239
Function: strpos

File: /opt/bitnami/apache2/htdocs/cicool/application/third_party/MX/Router.php
Line: 72
Function: set_class

File: /opt/bitnami/apache2/htdocs/cicool/application/third_party/MX/Router.php
Line: 329
Function: _parse_routes

File: /opt/bitnami/apache2/htdocs/cicool/index.php
Line: 339
Function: require_once

**Comment by ridwanskaterock** [comment]
Yes sorry currently not support for PHP version 7.3, your country install
on PHP version 7.1

Pada tanggal Sel, 11 Feb 2020 11.13, Hugo Barbosa <notifications@github.com>
menulis:

**Comment by inglesuniversal** [comment]
ok, thanks so now I just tried to install it on a different server I have with PHP 5.6 and got this error when trying to run the wizard:

Parse error: syntax error, unexpected '(' in /opt/bitnami/apache2/htdocs/cicool/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 246

Is this ERROR easier to fix than set up a 7.1 PHP server?

or would I have to downgrade my server 7.3 to 7.1 to make your script work?

Which route should I take?

Regards

**Comment by zkenstein** [comment]
> ok, thanks so now I just tried to install it on a different server I have with PHP 5.6 and got this error when trying to run the wizard:
> 
> Parse error: syntax error, unexpected '(' in /opt/bitnami/apache2/htdocs/cicool/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 246
> 
> Is this ERROR easier to fix than set up a 7.1 PHP server?
> 
> or would I have to downgrade my server 7.3 to 7.1 to make your script work?
> 
> Which route should I take?
> 
> Regards

Got this error to, but what I did is reinstall the php7.1 using apt-get install php7.1_intl solved my problem. Hope this helps

**Comment by ridwanskaterock** [comment]
Oke thank you i need update and ask for developer for some library 3d party

Thanks

Pada tanggal Sen, 17 Feb 2020 22.50, zkenstein <notifications@github.com>
menulis:

**Comment by inglesuniversal** [comment]
hello, any news about making Cicool script compatible with PHP version 7.3.11 ? All my work in on hold because of that. Thanks

**Comment by ridwanskaterock** [comment]
latest version support on version 7.3 you can download it thanks
