### ISSUE TITLE
Export PDF g bisa boz

### ISSUE THREAD

**Issue by zmutclik** [ridwanskaterock/cicool#355]
A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: _class/locale.class.php

Line Number: 68

Backtrace:

File: /var/www/html/application/libraries/htmlpdf/_class/locale.class.php
Line: 68
Function: _error_handler

File: /var/www/html/application/libraries/htmlpdf/html2pdf.class.php
Line: 141
Function: load

File: /var/www/html/application/libraries/HtmlPdf.php
Line: 26
Function: __construct

File: /var/www/html/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /var/www/html/application/core/My_Model.php
Line: 218
Function: library

File: /var/www/html/modules/blog_category/controllers/backend/Blog_category.php
Line: 289
Function: pdf

File: /var/www/html/index.php
Line: 339
Function: require_once

**Comment by ridwanskaterock** [comment]
Halo Mas bisa dicoba share itu environment nya pakai PHP versi berapa ya
terima kasih

Pada tanggal Kam, 13 Feb 2020 11.53, Fahrudin Hariadi <
notifications@github.com> menulis:

**Comment by zmutclik** [comment]
pakai PHP 7.4

**Comment by ridwanskaterock** [comment]
php 7.4 blm support, versi terakhir support di PHP 7.3
