### ISSUE TITLE
Blog Image dengan file path

### ISSUE THREAD

**Issue by zkenstein** [ridwanskaterock/cicool#359]
Halo gan,

Bagaimana cara membuat api response untuk gambar blog post dengan path image nya?

Untuk sekarang hanya keluar nama file nya saja di response image untuk post.

Thanks,

**Comment by ridwanskaterock** [comment]
halo untuk fieldnya pada api builder apa sudah di pilih jenis inputnya file gan ?

**Comment by zkenstein** [comment]
sudah gan

**Comment by zkenstein** [comment]
Mantap scriptnya

**Comment by ridwanskaterock** [comment]
siap gan 👍
