### ISSUE TITLE
Unable to Generate Table when using crud builder

### ISSUE THREAD

**Issue by jnachman123** [ridwanskaterock/cicool#36]
Hi there, i get the error on the blog table and my custom table 

![capture](https://cloud.githubusercontent.com/assets/19267779/23651039/1f029348-031c-11e7-94f9-5919f40fa0b8.PNG)

**Comment by ridwanskaterock** [comment]
please see the console of your browser and the information explosion here, I'll help you, see the response in the can and let me know    thanks

**Comment by jnachman123** [comment]
hi ridwn.. no information in the console?

**Comment by jnachman123** [comment]
other than this <h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  session_start(): Cannot send session cache limiter - headers already sent (output started at /homepages/31/d488456743/htdocs/cicool/application/controllers/administrator/Crud.php:2)</p>
<p>Filename: Session/Session.php</p>
<p>Line Number: 141</p>


	<p>Backtrace:</p>

**Comment by ridwanskaterock** [comment]
you can read the same issue https://github.com/ridwanskaterock/cicool/issues/24 

thanks i hove porblem resolved

**Comment by jnachman123** [comment]
thank you , case closed

**Comment by ridwanskaterock** [comment]
thanks ticked closed
