### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by fleogit** [ridwanskaterock/cicool#361]
Hi I cannot get past the DB install . all settings are correct all other wizzard pages worked fine 

An Error Was Encountered

The action you have requested is not allowed.

**Comment by ridwanskaterock** [comment]
Hi can you follow some related issue 
https://github.com/ridwanskaterock/cicool/issues/83

if not help you can send me detail access to my email ridwanskaterocks@gmail.com

Thanks

**Comment by ridwanskaterock** [comment]
try for point 1 
1. Disable the csrf check temporarily: edit cicool/application/views/core_template/config_template.txt. Find '$config['csrf_protection'] = TRUE;' and set it to '$config['csrf_protection'] = FALSE;'

**Comment by fleogit** [comment]
i solved it thank you
