### ISSUE TITLE
PHP Error showing up on top of Page

### ISSUE THREAD

**Issue by sudishs** [ridwanskaterock/cicool#362]
I am pretty new to the CRUD generators and their install and config. Am struggling a bit with about 4 error sets coming on top of the page.
Severity: 8192

Message: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

Filename: MX/Router.php

Line Number: 239

Backtrace:

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Router.php
Line: 239
Function: strpos

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Router.php
Line: 101
Function: _set_default_controller

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Router.php
Line: 333
Function: _set_default_controller

File: D:\xampp\htdocs\GarageIT\index.php
Line: 339
Function: require_once

Second Set:
A PHP Error was encountered
Severity: 8192

Message: Array and string offset access syntax with curly braces is deprecated

Filename: libraries/Profiler.php

Line Number: 118

Backtrace:

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: D:\xampp\htdocs\GarageIT\index.php
Line: 339
Function: require_once

3rd set:
A PHP Error was encountered
Severity: 8192

Message: Array and string offset access syntax with curly braces is deprecated

Filename: libraries/Profiler.php

Line Number: 146

Backtrace:

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: D:\xampp\htdocs\GarageIT\index.php
Line: 339
Function: require_once

4th set:
A PHP Error was encountered
Severity: 8192

Message: Array and string offset access syntax with curly braces is deprecated

Filename: libraries/Profiler.php

Line Number: 361

Backtrace:

File: D:\xampp\htdocs\GarageIT\application\third_party\MX\Loader.php
Line: 173
Function: _ci_load_library

File: D:\xampp\htdocs\GarageIT\index.php
Line: 339
Function: require_once

Below these errors, page loads fine.
I am sure its something silly, but the newbie in me will be glad to be guided. Thanks in advance.

**Comment by sudishs** [comment]
@ridwanskaterock - Could you please let me know how to proceed. I purchased this off Envato yesterday and am unable to get things working here. Please see attachment
[Issues Reported.pdf](https://github.com/ridwanskaterock/cicool/files/4312338/Issues.Reported.pdf)

**Comment by ridwanskaterock** [comment]
Please make sure your PHP version is 7.1 or 7.0 Thanks

**Comment by sudishs** [comment]
Thank You - works now. But are you suggesting that it will not work with the latest versions of PHP. Is there an update going to be available which will make it work on 7.4+?
On the summaries the listed version is 5.x+ - hence no hint that it would only work in the range of 5.x until 7.1.x

**Comment by ridwanskaterock** [comment]
Hi yes, actually for version 7.4 is on progress.

I will male update and notify to all member for updates

Thanks

Pada tanggal Rab, 11 Mar 2020 10.09, sudishs <notifications@github.com>
menulis:

**Comment by ridwanskaterock** [comment]
latest version support for PHP 7.3
