### ISSUE TITLE
Error pada saat edit crud

### ISSUE THREAD

**Issue by indrajatmiko** [ridwanskaterock/cicool#366]
Notice

Message: Undefined variable: configuration

Filename: models/Model_crud.php

Line Number: 140

Backtrace:

File: /home/x/cicool/modules/crud/models/Model_crud.php
Line: 140
Function: _error_handler

File: /home/x/cicool/modules/crud/controllers/backend/Crud.php
Line: 125
Function: get_crud_field_configuration

File: /home/x/cicool/index.php
Line: 339
Function: require_once

**Comment by ridwanskaterock** [comment]
bug, was fixed on next version 
modules/crud/controllers/backend/Crud.php
![image](https://user-images.githubusercontent.com/9270445/77294451-e4968800-6d16-11ea-9d5b-6622ac53c6c7.png)

**Comment by indrajatmiko** [comment]
versi terbaru sudah terselesaikan. terimakasih
