### ISSUE TITLE
Chained error

### ISSUE THREAD

**Issue by indrajatmiko** [ridwanskaterock/cicool#368]
saya coba chained, tapi malah error. ini yg versi PHP 7.3

A PHP Error was encountered

Severity: Notice
Message:  Undefined offset: 3
Filename: crud/crud_update.php
Line Number: 290

	Backtrace:
	
		
	
		
	
		
			
			File: /home/localhost/cicool/modules/crud/views/backend/standart/administrator/crud/crud_update.php
			Line: 290
			Function: _error_handler			

		
	
		
			
			File: /home/localhost/cicool/application/third_party/MX/Loader.php
			Line: 362
			Function: include			

		
	
		
			
			File: /home/localhost/cicool/application/third_party/MX/Loader.php
			Line: 304
			Function: _ci_load			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 751
			Function: view			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 712
			Function: _load_view			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 224
			Function: _find_view			

		
	
		
			
			File: /home/localhost/cicool/application/core/My_Controller.php
			Line: 485
			Function: build			

		
	
		
			
			File: /home/localhost/cicool/modules/crud/controllers/backend/Crud.php
			Line: 129
			Function: render			

		
	
		
	
		
			
			File: /home/localhost/cicool/index.php
			Line: 339
			Function: require_once			

		
	

A PHP Error was encountered

Severity: Notice
Message:  Trying to get property 'chain_field_eq' of non-object
Filename: crud/crud_update.php
Line Number: 290

	Backtrace:
	
		
	
		
	
		
			
			File: /home/localhost/cicool/modules/crud/views/backend/standart/administrator/crud/crud_update.php
			Line: 290
			Function: _error_handler			

		
	
		
			
			File: /home/localhost/cicool/application/third_party/MX/Loader.php
			Line: 362
			Function: include			

		
	
		
			
			File: /home/localhost/cicool/application/third_party/MX/Loader.php
			Line: 304
			Function: _ci_load			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 751
			Function: view			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 712
			Function: _load_view			

		
	
		
			
			File: /home/localhost/cicool/application/libraries/Template.php
			Line: 224
			Function: _find_view			

		
	
		
			
			File: /home/localhost/cicool/application/core/My_Controller.php
			Line: 485
			Function: build			

		
	
		
			
			File: /home/localhost/cicool/modules/crud/controllers/backend/Crud.php
			Line: 129
			Function: render			

		
	
		
	
		
			
			File: /home/localhost/cicool/index.php
			Line: 339
			Function: require_once			

		
	

                                         value="jawab_a"&gt;Jawab_a

**Comment by ridwanskaterock** [comment]
Sepertinya perlu migrasi ulang database ke versi terbaru
