### ISSUE TITLE
Great Product - Few Questions

### ISSUE THREAD

**Issue by jnachman123** [ridwanskaterock/cicool#37]
1 - How can i divert the user directly to login page 
2 - In the CRUD Builder how can i change labels
3 - How can i put custom PHP pages on the site 
4 - If i change a view, will i need to take a copy if i regenerate crud pages?
5 - Are there any examples of where you have added an action from the grid (i.e. from list open new page passing details from table?)

Thank you ,i look forward to your response.

**Comment by ridwanskaterock** [comment]
for question 1

you can change the code with 
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
*| --------------------------------------------------------------------------
*| Web Controller
*| --------------------------------------------------------------------------
*| For default controller
*|
*/
class Web extends Front
{
	
	public function __construct()
	{
		parent::__construct();
	}

	public function index()
	{
		if (installation_complete()) {
			redirect('administrator/login');
		} else {
			redirect('wizzard/setup','refresh');
		}
	}

	public function home() 
	{
		$this->template->build('home');
	}
}


/* End of file Web.php */
/* Location: ./application/controllers/Web.php */

on application/controllers/Web.php file 

2. for current version you cant't change the label name, it's possible if you change the field name on database, for form builder you can change the label  name

3. whether that is your intention to create a new page in this cicool?

4. to generate crud or update it you will lose the custom code that you apply to cicool crud, you can generate back by removing the crud first

5. whether you are looking to add an action on the data line?

thanks

**Comment by jnachman123** [comment]
Thank you for your reply.

3. i was wondering if i can create php files and call them from the menu ... i.e. /folder name/example.php

5. Add custom button to list view on row that will open up new window and pass a parameter (e.g. id)

Thanks

**Comment by jnachman123** [comment]
1. After changing this code, the i am in a loop in which i login and it redirects me to the login page again!

**Comment by ridwanskaterock** [comment]
2. yes to create a page / module you can make the application / controllers / example.php you can learn the system CodeIgniter

3. to be able to add a custom button you can create a button on a view,
for example, you create a custom button on the blog, you can open view

application/views/backend/standart/administrator/blog/blog_list.php

![image](https://cloud.githubusercontent.com/assets/9270445/23777016/6584f80c-0564-11e7-9620-255ba7f0062e.png)


you can add custom button by write this code 

<?php is_allowed('blog_custom', function($blog) use ($blog){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/blog/custom/' . $blog->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Custom Button</a>
                               <?php }) ?>

**Comment by ridwanskaterock** [comment]
and you can change the auth application/controllers/administrator/Auth.php controller method login with 
![image](https://cloud.githubusercontent.com/assets/9270445/23777088/e3327fae-0564-11e7-85d2-d21944f1d206.png)

`redirect('administrator/user/profile','refresh');`

thanks
