### ISSUE TITLE
Merubah date format

### ISSUE THREAD

**Issue by donaldr001** [ridwanskaterock/cicool#370]
Mohon bantuan untuk merubah format tanggal datepicker dari 

2020-04-13

menjadi 

13 Apr 2020

sebagai acuan di database input data bukan berformat date tetap menggunakan Varchar

**Comment by ridwanskaterock** [comment]
harusnya ga perlu di simpan di db dengan format seperti itu mas,
untuk format yang di simpan bisa seperti biasa tapi ketika tampil di view baru bisa di rubah sesuai format di atas

format bisa di sesuaikan pada view 

![image](https://user-images.githubusercontent.com/9270445/78328889-79687380-75aa-11ea-974a-d704fc5f4896.png)


untuk contoh di atas saya mempunyai module product

Trimakasih

**Comment by donaldr001** [comment]
bukan di tampilan mas tampilan nda masalah, tapi memang permintaan databasenya bukan type datetime tapi yang di simpan data itu dalam bentuk date 20. mar 2020 sebagai contoh nya

**Comment by ridwanskaterock** [comment]
tinggal di implementasikan sj pada controllernya 
![image](https://user-images.githubusercontent.com/9270445/78354193-a2522e00-75d5-11ea-9127-a4a659e3604e.png)
![image](https://user-images.githubusercontent.com/9270445/78354207-a7af7880-75d5-11ea-86f7-9f10b689ddfc.png)

**Comment by donaldr001** [comment]
Di tampilan untuk list nya sudah berubah Tapi untuk di database masih sama kayak ini mas 2020-04-21

2020-04-21 <<< seperti yang tertulis di kolom datepicker di form


list.php

  <?php foreach($form_register_clients as $form_register_client): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $form_register_client->id; ?>">
                           </td>
                           <td><?= _ent($form_register_client->nama); ?></td> 
                    
                           <td><?= (new Datetime($form_register_client->expire))->format('d M Y'); ?></td>
                           
                           <td width="200">
                              <?php is_allowed('form_register_client_view', function() use ($form_register_client){?>
                              <a href="<?= site_url('administrator/manage-form/form_register_client/view/' . $form_register_client->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('form_register_client_update', function() use ($form_register_client){?>
                              <a href="<?= site_url('administrator/manage-form/form_register_client/edit/' . $form_register_client->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('form_register_client_delete', function() use ($form_register_client){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/manage-form/form_register_client/delete/' . $form_register_client->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>


untuk controllernya masih binggung

**Comment by ridwanskaterock** [comment]
contohnya seperti ini mas 
![image](https://user-images.githubusercontent.com/9270445/78358750-e812f480-75dd-11ea-8207-0575914f5ee0.png)

**Comment by donaldr001** [comment]
Siappp... Sudah Solve yang penting sudah bisa di store dalam bentuk seperti yang di inginkan Thanks You ..... Nice Tools .... Recomended

**Comment by ridwanskaterock** [comment]
Siap mas, sama sama 👍

**Comment by cnngraphics** [comment]
What is the English translation?

**Comment by ridwanskaterock** [comment]
try https://translate.google.com/translate?sl=id&tl=en&u=https%3A%2F%2Fgithub.com%2Fridwanskaterock%2Fcicool%2Fissues%2F370%23issuecomment-608642117
