### ISSUE TITLE
Please help Installation error

### ISSUE THREAD

**Issue by kuntumseroja** [ridwanskaterock/cicool#373]
Hi Mas Ridwan
setelah aq upload dan jalanin index.php nya 
malah redirect ke wizzard language error

katanya ga ada filenya
please resolve ya thanks
![image](https://user-images.githubusercontent.com/33392858/78526335-ec205b80-7803-11ea-9c4c-17047771ba4c.png)

**Comment by ridwanskaterock** [comment]
Coba setelah ip di tambah /index.php/ mas jika tampil berarti mod
rewritenya perlu di aktifkan



Pada tanggal Sen, 6 Apr 2020 12.42, kuntumseroja <notifications@github.com>
menulis:

**Comment by kuntumseroja** [comment]
hello mas Ridwan

sy udah activate rewrite nya 
sudah sempet ngeluearin  page instalasi 
trus ada beberapa directory yg harus di ubah permission ke 066 (application/ uploads/ dan module)
saya udah change permission nya semua ke 0666
tapi malah keluar gini mas 
mohon petunjuknya
![image](https://user-images.githubusercontent.com/33392858/78536048-63131f80-7817-11ea-8f83-eee5e2216d85.png)

**Comment by ridwanskaterock** [comment]
Ini pakai versi terbaru apa gmna mas ?

Pada tanggal Sen, 6 Apr 2020 15.01, kuntumseroja <notifications@github.com>
menulis:

**Comment by kuntumseroja** [comment]
download versi yg terakhir dari envato, lihat versinya dari mana?
aku coba di ditectory lain ga bisa juga
Thanks

**Comment by ridwanskaterock** [comment]
Bisa di cek mas di application/config/ file database.php config.php ada ?
Dan di rubah juga permission foldernya

Pada tanggal Sen, 6 Apr 2020 18.50, kuntumseroja <notifications@github.com>
menulis:

**Comment by kuntumseroja** [comment]
eh udah bisa mas,

kelihatannya directory permissionnya doang
gw coba dulu ya
case closed

**Comment by kuntumseroja** [comment]
sama config.php saya ubah2 + nambahin .htacess
