### ISSUE TITLE
CRUD Buider, error 

### ISSUE THREAD

**Issue by kuntumseroja** [ridwanskaterock/cicool#374]
Hi Mas Ridwan
Saya berhasil create CRUD dari CRUD Builder , tapi pas mau lihat pencet see di action
dapat balikan 404 
apanya ya mas?
thanks
itu url suffix gpp kan ditambahin model gitu bukan .html?

![image](https://user-images.githubusercontent.com/33392858/78622043-4d046e00-78ae-11ea-9b79-e49724c1a730.png)

**Comment by ridwanskaterock** [comment]
harusnya gpp mas. 
bisa di lihat mas nama folder di modulenya lowercase atau gmna ?

**Comment by kuntumseroja** [comment]
lowercase semua sih , module maksudnya di MVC module itu ya ..hehe
waktu di list CRUD trus pencet see koq 404 harusnya preview kan ya?
boleh minta petunjuknya liat dimana?
atau masnya kalau ada waktu liatin instalasi gw nanti tak bayar waktunya :))
tp tong mahal2 nya

**Comment by ridwanskaterock** [comment]
coba dlu mas urlnya
[image: image.png]
nama modulenya lowercase semua

**Comment by kuntumseroja** [comment]
udah bisa sih , ternyata tablenya ga ada index..
kalau yg hasil crud builder bisa di embed ke page ga sih 

btw disable-builder itu buat apa ya

Thanks

**Comment by ridwanskaterock** [comment]
oh oke mas, kalo Crud builder sekarang ini belum bisa di embed ke page. 

disable builder buat nonaktifin fitur builder yang di pilih

**Comment by kuntumseroja** [comment]
use case nya apa ya mas, klau pakai disable builder. kenapa bisa dinonaktifkan?
