### ISSUE TITLE
Block on the home page

### ISSUE THREAD

**Issue by LenkaSoma** [ridwanskaterock/cicool#375]
I recently acquired the Cicool, however, when I wanted to change the name and description of the groups I was redirected to the homepage of the site and since then I can do nothing more (click on Dashboard or My Profile sends me back to the home page (I can only log out and log in again), an idea of ​​what I (badly) did? : x

PHP Version : 7.2

Thank you ;)

**Comment by ridwanskaterock** [comment]
Hello actually if you login super admin you can access all resource.
You can set permission in access menu under auth. For other group.
For ot you need required for profile and dashboard resource

Thank you

Pada tanggal Jum, 10 Apr 2020 04.55, LenkaSoma <notifications@github.com>
menulis:

**Comment by LenkaSoma** [comment]
Precisely, I am connected as a super administrator but I cannot access the dashboard or my profile, everything redirects me to the home page, my level group is indeed on 1 (super admin) but since I changed the name of the group I can no longer access the dashboard ..

**Comment by LenkaSoma** [comment]
https://prnt.sc/rwfm7h
https://prnt.sc/rwfmhc
https://prnt.sc/rwfmoi

Look, I have all the permissions, however, it is impossible for me to go to the dashboard or the profile, I am well connected and in superadmin with the permissions ... Since I changed the "name" of the group it makes its

**Comment by ridwanskaterock** [comment]
Weird. the administrator should be able to access anything.

If you try login, and access administrator/user direct . Will redirect to
homepage ?

Pada tanggal Jum, 10 Apr 2020 06.32, LenkaSoma <notifications@github.com>
menulis:

**Comment by LenkaSoma** [comment]
That's exactly it ... While I have all the permissions

**Comment by LenkaSoma** [comment]
J'ai réussi à régler le problème en obtenant les autorisations via la base de données pourtant j'ai une nouvelle erreur qui arrive et je ne sais pourquoi :( https://prnt.sc/rwp7xv

**Comment by ridwanskaterock** [comment]
If you setup from new. You have problem also ?

Can you share access web to ridwanskaterocks@gmail.com thanks

Pada tanggal Jum, 10 Apr 2020 18.12, LenkaSoma <notifications@github.com>
menulis:
