### ISSUE TITLE
Error on install - 

### ISSUE THREAD

**Issue by chesketh** [ridwanskaterock/cicool#38]
I get the following error when I try to run the installer (open_basedir restriction in effect), followed by header error.
Server: nginx, php 7.1, mysql 5.5

A PHP Error was encountered

Severity: Warning

Message: is_file(): open_basedir restriction in effect. File(/wizzard/config/routes.php) is not within the allowed path(s): (c:/users/username/wtserver)

Filename: core/My_Router.php

Line Number: 114

Backtrace:

File: C:\Users\username\WTServer\WWW\domainname\cilte\cicool\application\core\My_Router.php
Line: 114
Function: is_file

File: C:\Users\username\WTServer\WWW\domainname\cilte\cicool\application\core\My_Router.php
Line: 66
Function: __construct

File: C:\Users\username\WTServer\WWW\domainname\cilte\cicool\index.php
Line: 315
Function: require_once

**Comment by ridwanskaterock** [comment]
What server are you using?

you are on any OS can be explained,

usually it happens because when you create a file does not have write access to the folder application / config

thanks
