### ISSUE TITLE
harus menambahkan index.php

### ISSUE THREAD

**Issue by titukbnov** [ridwanskaterock/cicool#388]
Mohon pencerahan
instalasi semua berhasil.. tetapi di dalam dashboard untuk mengakses menu selalu url not found danharus menambahkan index.php/

**Comment by ridwanskaterock** [comment]
Coba aktifkan mod rewritenya di settingan apachenya mas

Pada tanggal Sen, 11 Mei 2020 03.30, titukbnov <notifications@github.com>
menulis:

**Comment by titukbnov** [comment]
saya menggunakan shared hosting mas, kayaknya providernya enggan untuk mengaktifkan mod_rewritenya.
apakah ada solusi

terima kasih responnya

**Comment by titukbnov** [comment]
Solved mas. sudah enable mod_rewrite
terima kasih
