### ISSUE TITLE
Can't go past home

### ISSUE THREAD

**Issue by pineappeal** [ridwanskaterock/cicool#39]
I installed the application and there are no errors.
I can access the login screen and my login email and password are correct but it goes no further.  
When I try to log in, it keeps redirecting me back to the home screen (see screenshot) 

<img width="1342" alt="screen shot 2017-03-17 at 15 44 16" src="https://cloud.githubusercontent.com/assets/2551480/24070394/4a835b7c-0bc5-11e7-94a7-729dd119bfe7.png">

**Comment by ridwanskaterock** [comment]
sorry for a long time to membelasnya, I was sick a few days :( I will help you as much as possible :)

before you are using PHP version number?
and MySQL version number? and OS do you use to run this application,

prior to debug try to open the file index.php


precisely in line 56 you will find a code like the following

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');

you like to change to be like this

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
to see what pops up error

then you try to run back,
what response in the can?

thanks

**Comment by pineappeal** [comment]
Thanks for the reply.
Here are the answers:

1.       It is already set to development mode and no error appears

2.       My environment is macOS Sierra 10.12.3, Apache 2.4, MySQL 5.7.17, PHP 7.1

**Comment by ridwanskaterock** [comment]
whether the session runs smoothly on your localhost?

**Comment by ridwanskaterock** [comment]
you can learn this issue http://stackoverflow.com/questions/5884916/codeigniter-sessions-wont-stick-on-localhost-mamp, maybe there are similarities problem session

**Comment by ridwanskaterock** [comment]
or you can try change value for log_threshold to 4 for seee all message error etc

![image](https://cloud.githubusercontent.com/assets/9270445/24081212/fa782b62-0ce1-11e7-836d-17644874fc80.png)

thanks
