### ISSUE TITLE
Rest API - missing PUT and DELETE methods

### ISSUE THREAD

**Issue by Fede72** [ridwanskaterock/cicool#390]
Hi,

I noticed that in the REST API generation there are not DELETE or PUT methods but only GET/POST.

Is there a way to change it?

Thanks

**Comment by ridwanskaterock** [comment]
hello you just change method on controller for make specific method 

![image](https://user-images.githubusercontent.com/9270445/82130632-5232d200-97f7-11ea-8fe7-728352d69aa7.png)


if you need try change method from delete_post to delete_delete

**Comment by ridwanskaterock** [comment]
you can find file on 
![image](https://user-images.githubusercontent.com/9270445/82130648-755d8180-97f7-11ea-96d0-96d321a9094c.png) for example

**Comment by Fede72** [comment]
Ok thanks.
So there is not a flag allowing to switch all the APIs to the 4 methods management without changing one-by-one?

**Comment by ridwanskaterock** [comment]
you mean you need change for all rest if build ? 
you can change on this template file 
![image](https://user-images.githubusercontent.com/9270445/82139237-a4541180-9850-11ea-909f-bbe69f87c2a3.png)

**Comment by Fede72** [comment]
Thanks!
