### ISSUE TITLE
Multiple Filter multiple category

### ISSUE THREAD

**Issue by zkenstein** [ridwanskaterock/cicool#399]
Gan, 

untuk menggunakan multiple filter API untuk multiple value bagaimana ya? udah nyoba yang ini  #382 hanya bisa untuk satu Category saja.

Thanks

**Comment by ridwanskaterock** [comment]
Untuk versi selanjutnya mau saya buat multi filter gan

**Comment by zkenstein** [comment]
Mantap Gan
