### ISSUE TITLE
Plesk Onyx Server issues

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#4]
Hello,

 I installed on my computer with WAMP and runs fine, but I am trying to install to my server with plesk onyx CentOS 6.x with apache 2.2 and php fastcgi 5.6.29 and brokes in step 3, I look at database and create datatables but broke and don’t work, If I go to home goes another time to wizzard script, The logs give this error:

PHP Fatal error: Call to a member function eventListen() on null in /var/www/vhosts/xxx/xxx.team/application/controllers/Not_found.php on line 21, referer: http://xxx.team/wizzard/setup/3

Where is the error for repair it?

I believe than the unique difference is than my domain extension is .team, in my home server i use dot com domain.

Can I do a manual installation? after creation of datatable to mysql database?

Many tables how as aauth_users are empty data, The version of Mysql is 5.0.11

The CodeIgniter error page show in Google Chrome:

*****
 
An Error Was Encountered

The action you have requested is not allowed.

*****

Thanks a lot.

**Comment by mjhcremer** [comment]
I have the same issue on my webserver!

**Comment by ridwanskaterock** [comment]
hello before I have tested this on ubuntu server and running normally, so I have been testing in Windows environments and it also seemed normal.

Sorry for the inconvenience.

when you try to change the installation following code

in application/config/config.php

precisely in line 441

`$config['csrf_protection'] = TRUE;`

into
`
$config['csrf_protection'] = FALSE;`

maybe it will help when you are trying to complete the installation in foxes as before.


thanks

**Comment by R3N3G** [comment]
SOLVED!!!! Stupid thing :(

I test many solutions including change of OS to Debian 8 with plesk onyx but he problem persist exactly….

After activate full logs of apache, php and study it, finally found an error same as:

ERROR – 04-01-2017 01:20:53 -> Severity: Notice -> Undefined property: Not_found::$cc_app /var/www/vhosts/xxx/httpdocs/application/controllers/Not_found.php 21 ERROR – 04-01-2017 01:20:53 -> Severity: Error -> Call to a member function eventListen() on null /var/www/vhosts/xxx/httpdocs/application/controllers/Not_found.php 21

Not_found.php line 21
$this->cc_app->eventListen(‘show_error_404’);

I comment it with this value // $this->cc_app->eventListen(‘show_error_404’);
Then… CodeIgniter gives me an error log about fopen() problems If the last apache problem was 403 forbidden and next fopen(), the problem is directory writeable issues.

Blablabla…

Solution *
Editing on file domain/application/config/config.php Line 373

$config[‘sess_save_path’] = NULL;

Change to writable directory absolute path, in my case tmp with chmod 751 *
$config[‘sess_save_path’] = ’/var/www/vhosts/xxx/httpdocs/tmp’;

And I can finish the INSTALLATION!!!!

My Server Configuration finally:

Versión Plesk Onyx v17.0.17_build1700161028.14 OS_Debian 8.6 Apache 2.4 FastCGI with ngix uninstalled and PHP 5.6.29 OS Vendor with Maria.DB ver.10.x No addons installed.

I believe than the problem always was Codeigniter config.php, then…. I believe than with the other OS Centos 6.5 and 7.2 tested the issue can repaired exactly with the same solution, I don’t test now because I broke my brain, but I other user want to test with Cent OS 6.x or 7.x. I Can help him.

P.D. Don’t forgive uncomment

Not_found.php line 21

// $this->cc_app->eventListen(‘show_error_404’);

My personal opinion with this issue repaired is really good job with this script, I will give 5 star rating, I follow next versions, this one is really save much much time of development, I believe than the following step is a version could create tables directly on the database server :)

Good Job!!!!!

**Comment by mjhcremer** [comment]
I did not work for me.

Met vriendelijke groet,
Mario Cremer

2017-01-04 2:09 GMT+01:00 Muhamad Ridwan <notifications@github.com>:

**Comment by ridwanskaterock** [comment]
hello R3N3G 

I am happy to see it running normally,
I will continue to help support as much as possible.

future there will be attractive and will feature in its consider any given if too many superfluous features that happened was confusing to users.

I tried to give my best in the future :)

thank you, I wait for the reviews and the best news of you, for future updates :)

**Comment by ridwanskaterock** [comment]
hello mjhcremer,

if you have made changes as I commanded over, maybe it could help :)

otherwise we recommend creating a separate ticket for this issue :)

we are waiting for good news from you,

thanks

**Comment by R3N3G** [comment]
hello mjhcremer,

I will look your ticket tomorrow and I try to help you,
If you can... Post http logs, php logs and codeigniter logs, if you don't know how do it I can give you steps.

Thanks a lot

**Comment by mjhcremer** [comment]
Please help me with those steps.

Met vriendelijke groet,
Mario Cremer

2017-01-04 2:54 GMT+01:00 R3N3G <notifications@github.com>:
