### ISSUE TITLE
404 after new CRUD

### ISSUE THREAD

**Issue by CarlisleCo** [ridwanskaterock/cicool#404]
Just purchased & installed: 08/02/2020

When I add a new CRUD I get a 404 when I try to view it... 
URL EXAMPLE: https://data.domain.com/data/administrator/Vendor

I see the CRUD controller (modules/crud/controllers/backend/CRUD.php) is set to:
	$config = [
			'base_url'     => 'administrator/crud/index/',

Please Advise - Thank You Kindly!!!
God Bless
- Daniel

**Comment by CarlisleCo** [comment]
Note: I have tried installing in the cicool directory as well, and it does the same thing. 
- Daniel

**Comment by CarlisleCo** [comment]
Note: It works fine with the products table that came with the install. I only get the 404 page with new tables…

**Comment by CarlisleCo** [comment]
404 SOLVED: Make sure all table names are lower case and separated by and underscore!

**Comment by CarlisleCo** [comment]
Need Support: When using the text editor and putting html in source, it is showing all the tags when it is saved so the view is not very clean. Can that be modified to not show tags at record view? Thanks!

**Comment by ridwanskaterock** [comment]
Hi, for it you can find view module_name_view.php and remove _ent function

Thanks

Pada tanggal Sen, 3 Agt 2020 02.36, CarlisleCo <notifications@github.com>
menulis:

**Comment by CarlisleCo** [comment]
Thank you!!!!
