### ISSUE TITLE
Error while requesting token

### ISSUE THREAD

**Issue by MeijerN** [ridwanskaterock/cicool#408]
Hello!

I just bought your application and i was learning to setup some crud and api. At the moment iam getting an error while trying to request a token. It was working just fine for a couple requests but now iam receiving a 500 internal server error. I did not tamper with any files. 

Another stange thing is if i click on 'User' under 'Auth' in the main navigation iam getting a 404 page not found error. Iam getting this error also after logging in, but it the autentication still works. What is the best way to resolve this?

Thanks in advance!

```
An uncaught Exception was encountered
Type: RuntimeException

Message: Unable to locate the model you have specified: Model_user

Filename: /home/niekmeij/public_html/cicool/system/core/Loader.php

Line Number: 348

Backtrace:

File: /home/niekmeij/public_html/cicool/application/third_party/MX/Loader.php
Line: 212
Function: model

File: /home/niekmeij/public_html/cicool/application/core/My_Controller.php
Line: 1048
Function: model

File: /home/niekmeij/public_html/cicool/modules/api/controllers/User.php
Line: 11
Function: __construct

File: /home/niekmeij/public_html/cicool/index.php
Line: 338
Function: require_once
```

**Comment by ridwanskaterock** [comment]
Hi can you check for modules user is exist and file like model and controller exist in this folder ? 

seems the folder erased
if erased you can copy for modules user to your project 

Thanks

**Comment by MeijerN** [comment]
Thank you for your quick response. I checked the files and the directory 'user' in 'cicool/modules' was missing. All the other files where still there. It works perfectly after copying the user directory back.

Thanks!
