### ISSUE TITLE
how to scale image?

### ISSUE THREAD

**Issue by mumtazhqq** [ridwanskaterock/cicool#41]
Hi.. 
How to scale the image while uploading, I've try to add scaling option in the javascript but its still not working, its keep say "The filetype you are attempting to upload is not allowed."

here my update code in the script, I just add the scalling option like in the fineUploader documentation 
`$('#ap_data_image_galery').fineUploader({
          template: 'qq-template-gallery',
          scaling: {
              sendOriginal: false,
              sizes: [
                  {name: "", maxSize: 300}
              ]
          }, ...`

or maybe there is a way to scale the image, 

Thank you.. very good product.. 👍

**Comment by ridwanskaterock** [comment]
scaling if you mean like this? https://docs.fineuploader.com/features/scaling.html

so there are two files are uploaded or just a single file that is uploaded and then scale the image changes,

why you do not do it on the server?

thanks

**Comment by mumtazhqq** [comment]
Well actually I just need to rezise the main image, I only need to upload a single file and then resize it.. 
can you give me a clue do rezise it on the server?
thanks
