### ISSUE TITLE
Error on view and update a CRUD when a column name of a table start with a number

### ISSUE THREAD

**Issue by psandoval2003** [ridwanskaterock/cicool#415]
![error_numero_columna](https://user-images.githubusercontent.com/71888180/94276730-01f31b80-ff1f-11ea-8cab-eb5930c5f4fa.PNG)
![error_numero_columna2](https://user-images.githubusercontent.com/71888180/94276732-028bb200-ff1f-11ea-959d-6d15ad0cdc2a.PNG)

**Comment by ridwanskaterock** [comment]
Hi yes sorry currently not avaiable for use field with numerical prefixes and spaces 
because is not good 

Thanks
