### ISSUE TITLE
Editting fields on CRUD view and not One by One.

### ISSUE THREAD

**Issue by psandoval2003** [ridwanskaterock/cicool#416]
I bought this script, thinking that editing a CRUD would be quick, but apparently it is only possible to edit one by one.

I need to be able to add selects, input, etc in the list of records of the view of a CRUD

Am I wrong and maybe I can't do it?

I have attached an image with what I need to do
![edit_directly_on_crud_view](https://user-images.githubusercontent.com/71888180/94284431-bba2ba00-ff28-11ea-9152-87126b3d4601.PNG)

**Comment by ridwanskaterock** [comment]
Hi yes if you need make like that possible for it 
i am avaiable for custom 

you can contact me for quote on ridwanskaterocks@gmail.com
