### ISSUE TITLE
When one Table have 150+ Columne

### ISSUE THREAD

**Issue by darshanvithani** [ridwanskaterock/cicool#417]
When Colume is exceed 60+ its not show reming colume 

https://d.pr/i/vs752R

i try to do many time this process but it not work 

its look there is limit .. can you fix

**Comment by ridwanskaterock** [comment]
Hi for it can you adjust the value 
maximum_execution_timen on php.ini

**Comment by darshanvithani** [comment]
display_errors = Off
max_execution_time = 1000
max_input_time = 1000
max_input_vars = 10000
memory_limit = 1024M
post_max_size = 100M
session.gc_maxlifetime = 14400
session.save_path = "/var/cpanel/php/sessions/ea-php71"
upload_max_filesize = 200M
zlib.output_compression = Off

**Comment by darshanvithani** [comment]
Still Not work

**Comment by darshanvithani** [comment]
This Setting it Work 

Thanks
