### ISSUE TITLE
Upgrade to 2.0

### ISSUE THREAD

**Issue by patpatoche** [ridwanskaterock/cicool#42]
Thanks for your reply, but when i download the 2.0 version and install it this version is still labeled 1.9.5!!!

**Comment by ridwanskaterock** [comment]
okay sorry to label :) I have to change it on the label, but that's just the look of it, the whole system has been upgraded to version 2 :)

thank you friend has informed :)

**Comment by patpatoche** [comment]
I try to test ciccol on a WAMP server. All required fonctions are validated during the installation but when i try to add a new crud or form please see what i get ???
![capture](https://cloud.githubusercontent.com/assets/26597126/24251224/b93166a0-0fd9-11e7-8278-1fb5e8bb3621.JPG)

**Comment by ridwanskaterock** [comment]
runnin gon URL cicoolurl.test/web/set_full_group_sql for activate full group sql thanks
