### ISSUE TITLE
Error Installation versi: 3.1.4

### ISSUE THREAD

**Issue by zkenstein** [ridwanskaterock/cicool#427]
Gan sewaktu install keluar error berikut:

```
Error Number: 1054

Unknown column 'version' in 'field list'

SELECT `version` FROM `migrations`

Filename: libraries/Migration.php

Line Number: 445
```

bisa di bantu kenapa gan?

Thanks

**Comment by ridwanskaterock** [comment]
Pakai versi berapa gan cicoolnya ? 
bisa di cek table migrations nya ada ?

**Comment by zkenstein** [comment]
Pakai versi 3.1.4 gan, di dbnya sih g ada gan. Btw kalau install untuk remote akses db bisa kan gan? Blm nyoba soalnya

**Comment by zkenstein** [comment]
Gan ane sudah install di localhost trs upload ke live server tapi masih refer ke installation page, apa yang perlu di ubah gan, agar aplikasi lsg ke halaman login?

**Comment by ridwanskaterock** [comment]
pastiin config/site.php di di upload juga gan

**Comment by zkenstein** [comment]
Mantap gan, sudah sukses. tapi setiap akses page keluar Module 'curl' already loaded, untuk ilanginnya gimana ya gan?
