### ISSUE TITLE
REST Api Question

### ISSUE THREAD

**Issue by ivan277** [ridwanskaterock/cicool#43]
Hi, How can i using the system that make a REST API joining more than 1 table ?

**Comment by ridwanskaterock** [comment]
yes you can join more than one table in a model that has been generated, you can set it up there, I'll help if you need thanks :)

**Comment by ivan277** [comment]
Hi


  How to do this ? Can you show me ?


Ivan
「Muhamad Ridwan <notifications@github.com>」在 2017年3月23日 週四，下午6:34 寫道：

**Comment by ridwanskaterock** [comment]
in this case I make API blog,
and I would like to join the blog by blog category

then I make the blog a fire through backend

and I add the following code to join the data
`
$this->db->join('blog_category', 'blog.category = blog_category.id', 'LEFT');`

```php

class Model_api_blog extends MY_Model {
    public function get($q = null, $field = null, $limit = 0, $offset = 0, $select_field = [])
	{
                ....
		$this->db->join('blog_category', 'blog.category = blog_category.id', 'LEFT');
                ....
		$query = $this->db->get($this->table_name);

		return $query->result();
	}
}
```

**_note: the model file automatically made when you make a Rest API builder_**

thanks

**Comment by ivan277** [comment]
Hi


  i want to know where can i type this command ?

  $this->db->join('blog_category', 'blog.category = blog_category.id',
'LEFT');

class Model_api_blog extends MY_Model {    public function get($q =
null, $field = null, $limit = 0, $offset = 0, $select_field = [])	{
            ....		$this->db->join('blog_category', 'blog.category =
blog_category.id', 'LEFT');                ....		$query =
$this->db->get($this->table_name);		return $query->result();	}}


You mention backend " then I make the blog a fire through backend", would
you mind tell me where ?



Ivan

**Comment by ivan277** [comment]
Hi



  Can someone answer my questions ?



Ivan

**Comment by ridwanskaterock** [comment]
you could be putting it on the model script

located in application/models

you can add the script on the method 

thanks

**Comment by kamakshi11** [comment]
how to test url of cicool api builder  on postmen

**Comment by kamakshi11** [comment]
how to test url of api builder cicool in postman
