### ISSUE TITLE
Issue after long time - when click on crud editor

### ISSUE THREAD

**Issue by darshanvithani** [ridwanskaterock/cicool#439]
![Screenshot 2020-12-24 at 3 15 30 PM](https://user-images.githubusercontent.com/5411758/103080097-28e2eb80-45fb-11eb-8dac-845b1634760c.png)

**Comment by darshanvithani** [comment]
form is work fine that did before

**Comment by ridwanskaterock** [comment]
Hi

can you enter ctrl + u / view source and copy to here 

Thanks

**Comment by darshanvithani** [comment]
| <link rel="stylesheet" type="text/css" href="asset/css/crud.css">
-- | --
  | <script src="asset//js/jquery.hotkeys.js"></script>
  | <script src="asset//float-thead/jquery.floatThead.min.js"></script>
  | <script type="text/javascript">
  | //This page is a result of an autogenerated content made by running test.html with firefox.
  | function domo(){
  |  
  | // Binding keys
  | $('*').bind('keydown', 'Ctrl+s', function assets() {
  | $('#btn_save').trigger('click');
  | return false;
  | });
  |  
  | $('*').bind('keydown', 'Ctrl+x', function assets() {
  | $('#btn_cancel').trigger('click');
  | return false;
  | });
  |  
  | $('*').bind('keydown', 'Ctrl+d', function assets() {
  | $('.btn_save_back').trigger('click');
  | return false;
  | });
  |  
  | }
  |  
  | jQuery(document).ready(domo);
  | </script>
  | 
  | <section class="content-header">
  | <h1>
  | Crud
  | <small>Updating Crud</small>
  | </h1>
  | <ol class="breadcrumb">
  | <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  | <li class=""><a  href="administrator/crud.html">Crud</a></li>
  | <li class="active">Updating </li>
  | </ol>
  | </section>
  | 
  | <section class="content">
  | <div class="row" >
  | <div class="col-md-12">
  | <div class="box box-warning">
  | <div class="box-body ">
  | 
  | <div class="box box-widget widget-user-2">
  | 
  | <div class="widget-user-header ">
  | <div class="widget-user-image">
  | <img class="img-circle" src="asset//img/add2.png" alt="Crud Avatar">
  | </div>
  | 
  | <h3 class="widget-user-username">Crud</h3>
  | <h5 class="widget-user-desc">Updating Crud</h5>
  | <hr>
  | </div>
  | <form action="administrator/crud/edit/4.html" name="form_crud" class="form-horizontal" id="form_crud" method="POST" accept-charset="utf-8">
  | <input type="hidden" name="__owkgk4oskcgkksksgwcgoogggk08wo4gc8o0wokk" value="edaf37ddcdb9e7640ea5638f99f84b1f" />
  |  
  | <input type="hidden" name="table_name" id="table_name" value="aio_all_data">
  | <input type="hidden" class="primary_key" name="primary_key"  id="primary_key" value="id" >
  |  
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Table Name </label>
  | <div class="col-sm-8">
  | <input type="text" readonly="" class="form-control" value="aio_all_data">
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Subject <i class="required">*</i></label>
  | <div class="col-sm-8">
  | <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="Aio All Data">
  | <small class="info help-block">The subject of crud.</small>
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Title </label>
  | <div class="col-sm-8">
  | <input type="text" class="form-control" name="title" id="title" placeholder="Title" value="Aio All Data">
  | <small class="info help-block">The title of crud.</small>
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Page</label>
  | <div class="col-sm-7">
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_create" type="checkbox" id="create" value="yes" name="create" > Make                          </label>
  | </div>
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_read" type="checkbox" id="read" value="yes" name="read" checked> Read
  | </label>
  | </div>
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_update" type="checkbox" id="update" value="yes" name="update" checked> Updating                           </label>
  | </div>
  | </div>
  | </div>
  |  
  | <hr>
  | <div class="wrapper-crud">
  | <table class="table table-responsive table table-bordered table-striped"  id="diagnosis_list">
  | <thead>
  | <tr>
  | <th width="20" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">No</th>
  | <th width="120" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Field</th>
  | <th width="80" colspan="4" style="text-align: center;">Show On</th>
  | <th width="100" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Input Type</th>
  | <th width="200" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Validation</th>
  | </tr>
  | <tr>
  | <th width="60" class="module-page-list column" style="vertical-align: middle; text-align: center;">Column</th>
  | <th width="60" class="module-page-add add_form" style="vertical-align: middle; text-align: center;">Additional Forms</th>
  | <th width="60" class="module-page-update update_form" style="vertical-align: middle; text-align: center;">Update Forms</th>
  | <th width="60" class="detail_page" style="vertical-align: middle; text-align: center;">Details page</th>
  | </tr>
  | </thead>
  | <tbody>
  |  
  | <tr >
  | <td  class="">
  | <i class="fa fa-bars dragable fa-lg text-muted"></i>
  | <input type="hidden" name="crud[1][id][sort]" class="priority" value="1" >
  | <input type="hidden" class="crud-id" id="crud-id" value="1" >
  | <input type="hidden" class="crud-name" id="crud-name" value="id" >
  |  
  | <div class="dropdown dropdown-config">
  | <a href="#"class="btn-flat btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
  | <i class="fa fa-cog"></i>
  | <span class="caret"></span>
  | </a>
  | <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  | <li><a href="#" class="btn-add-form-step">Add Form Step</a></li>
  | </ul>
  | </div>
  | </td>
  | <td>
  |  
  | <div style="margin-bottom: -10px;">
  |  
  | <span class="fa fa-trash text-danger btn-remove-field " style="margin-top:-20px; left:0px;  position:relative; cursor: pointer;"></span>
  | </div>
  | <input type="text" class="crud-input-initial" name="crud[1][id][label]" placeholder="id" value="id">
  |  
  | <div class="config-item-wrapper">
  | </div>
  |  
  | </td>
  | <td class="column">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_column]" value="yes">
  | </td>
  | <td class="add_form">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_add_form]" value="yes">
  | </td>
  | <td class="update_form">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_update_form]" value="yes">
  | </td>
  | <td class="detail_page">
  | <input class="flat-red check" type="checkbox" checked name="crud[1][id][show_in_detail_page]" value="yes">
  | </td>
  | <td>
  | <div class="col-md-12">
  | <div class="form-group ">
  | <select  class="form-control chosen chosen-select input_type" name="crud[1][id][input_type]" id="input_type" tabi-ndex="5" data-placeholder="Select Type" >
  | <option value="" class="<!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>Database Error</title>
  | <style type="text/css">
  |  
  | ::selection { background-color: #E13300; color: white; }
  | ::-moz-selection { background-color: #E13300; color: white; }
  |  
  | body {
  | background-color: #fff;
  | margin: 40px;
  | font: 13px/20px normal Helvetica, Arial, sans-serif;
  | color: #4F5155;
  | }
  |  
  | a {
  | color: #003399;
  | background-color: transparent;
  | font-weight: normal;
  | }
  |  
  | h1 {
  | color: #444;
  | background-color: transparent;
  | border-bottom: 1px solid #D0D0D0;
  | font-size: 19px;
  | font-weight: normal;
  | margin: 0 0 14px 0;
  | padding: 14px 15px 10px 15px;
  | }
  |  
  | code {
  | font-family: Consolas, Monaco, Courier New, Courier, monospace;
  | font-size: 12px;
  | background-color: #f9f9f9;
  | border: 1px solid #D0D0D0;
  | color: #002166;
  | display: block;
  | margin: 14px 0 14px 0;
  | padding: 12px 10px 12px 10px;
  | }
  |  
  | #container {
  | margin: 10px;
  | border: 1px solid #D0D0D0;
  | box-shadow: 0 0 8px #D0D0D0;
  | }
  |  
  | p {
  | margin: 12px 15px 12px 15px;
  | }
  | </style>
  | </head>
  | <body>
  | <div id="container">
  | <h1>A Database Error Occurred</h1>
  | <p>Error Number: 1055</p><p>Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'panel.crud_input_type.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by</p><p>SELECT *
  | FROM `crud_input_type`
  | GROUP BY `validation_group`</p><p>Filename: Model_crud.php</p><p>Line Number: 88</p>	</div>
  | </body>
  | </html>
  |  
  |

**Comment by darshanvithani** [comment]
`

  | <link rel="stylesheet" type="text/css" href="http://crd.purplesmarttv.com:80/asset/css/crud.css">
-- | --
  | <script src="http://crd.purplesmarttv.com:80/asset//js/jquery.hotkeys.js"></script>
  | <script src="http://crd.purplesmarttv.com:80/asset//float-thead/jquery.floatThead.min.js"></script>
  | <script type="text/javascript">
  | //This page is a result of an autogenerated content made by running test.html with firefox.
  | function domo(){
  |  
  | // Binding keys
  | $('*').bind('keydown', 'Ctrl+s', function assets() {
  | $('#btn_save').trigger('click');
  | return false;
  | });
  |  
  | $('*').bind('keydown', 'Ctrl+x', function assets() {
  | $('#btn_cancel').trigger('click');
  | return false;
  | });
  |  
  | $('*').bind('keydown', 'Ctrl+d', function assets() {
  | $('.btn_save_back').trigger('click');
  | return false;
  | });
  |  
  | }
  |  
  | jQuery(document).ready(domo);
  | </script>
  | 
  | <section class="content-header">
  | <h1>
  | Crud
  | <small>Updating Crud</small>
  | </h1>
  | <ol class="breadcrumb">
  | <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  | <li class=""><a  href="http://crd.purplesmarttv.com:80/administrator/crud.html">Crud</a></li>
  | <li class="active">Updating </li>
  | </ol>
  | </section>
  | 
  | <section class="content">
  | <div class="row" >
  | <div class="col-md-12">
  | <div class="box box-warning">
  | <div class="box-body ">
  | 
  | <div class="box box-widget widget-user-2">
  | 
  | <div class="widget-user-header ">
  | <div class="widget-user-image">
  | <img class="img-circle" src="http://crd.purplesmarttv.com:80/asset//img/add2.png" alt="Crud Avatar">
  | </div>
  | 
  | <h3 class="widget-user-username">Crud</h3>
  | <h5 class="widget-user-desc">Updating Crud</h5>
  | <hr>
  | </div>
  | <form action="http://crd.purplesmarttv.com:80/administrator/crud/edit/4.html" name="form_crud" class="form-horizontal" id="form_crud" method="POST" accept-charset="utf-8">
  | <input type="hidden" name="__owkgk4oskcgkksksgwcgoogggk08wo4gc8o0wokk" value="edaf37ddcdb9e7640ea5638f99f84b1f" />
  |  
  | <input type="hidden" name="table_name" id="table_name" value="aio_all_data">
  | <input type="hidden" class="primary_key" name="primary_key"  id="primary_key" value="id" >
  |  
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Table Name </label>
  | <div class="col-sm-8">
  | <input type="text" readonly="" class="form-control" value="aio_all_data">
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Subject <i class="required">*</i></label>
  | <div class="col-sm-8">
  | <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="Aio All Data">
  | <small class="info help-block">The subject of crud.</small>
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Title </label>
  | <div class="col-sm-8">
  | <input type="text" class="form-control" name="title" id="title" placeholder="Title" value="Aio All Data">
  | <small class="info help-block">The title of crud.</small>
  | </div>
  | </div>
  | <div class="form-group ">
  | <label for="label" class="col-sm-2 control-label">Page</label>
  | <div class="col-sm-7">
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_create" type="checkbox" id="create" value="yes" name="create" > Make                          </label>
  | </div>
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_read" type="checkbox" id="read" value="yes" name="read" checked> Read
  | </label>
  | </div>
  | <div class="col-xs-3">
  | <label>
  | <input class="flat-red check page_update" type="checkbox" id="update" value="yes" name="update" checked> Updating                           </label>
  | </div>
  | </div>
  | </div>
  |  
  | <hr>
  | <div class="wrapper-crud">
  | <table class="table table-responsive table table-bordered table-striped"  id="diagnosis_list">
  | <thead>
  | <tr>
  | <th width="20" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">No</th>
  | <th width="120" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Field</th>
  | <th width="80" colspan="4" style="text-align: center;">Show On</th>
  | <th width="100" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Input Type</th>
  | <th width="200" rowspan="2" valign="midle" style="vertical-align: middle; text-align: center;">Validation</th>
  | </tr>
  | <tr>
  | <th width="60" class="module-page-list column" style="vertical-align: middle; text-align: center;">Column</th>
  | <th width="60" class="module-page-add add_form" style="vertical-align: middle; text-align: center;">Additional Forms</th>
  | <th width="60" class="module-page-update update_form" style="vertical-align: middle; text-align: center;">Update Forms</th>
  | <th width="60" class="detail_page" style="vertical-align: middle; text-align: center;">Details page</th>
  | </tr>
  | </thead>
  | <tbody>
  |  
  | <tr >
  | <td  class="">
  | <i class="fa fa-bars dragable fa-lg text-muted"></i>
  | <input type="hidden" name="crud[1][id][sort]" class="priority" value="1" >
  | <input type="hidden" class="crud-id" id="crud-id" value="1" >
  | <input type="hidden" class="crud-name" id="crud-name" value="id" >
  |  
  | <div class="dropdown dropdown-config">
  | <a href="#"class="btn-flat btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
  | <i class="fa fa-cog"></i>
  | <span class="caret"></span>
  | </a>
  | <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  | <li><a href="#" class="btn-add-form-step">Add Form Step</a></li>
  | </ul>
  | </div>
  | </td>
  | <td>
  |  
  | <div style="margin-bottom: -10px;">
  |  
  | <span class="fa fa-trash text-danger btn-remove-field " style="margin-top:-20px; left:0px;  position:relative; cursor: pointer;"></span>
  | </div>
  | <input type="text" class="crud-input-initial" name="crud[1][id][label]" placeholder="id" value="id">
  |  
  | <div class="config-item-wrapper">
  | </div>
  |  
  | </td>
  | <td class="column">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_column]" value="yes">
  | </td>
  | <td class="add_form">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_add_form]" value="yes">
  | </td>
  | <td class="update_form">
  | <input class="flat-red check" type="checkbox"  name="crud[1][id][show_in_update_form]" value="yes">
  | </td>
  | <td class="detail_page">
  | <input class="flat-red check" type="checkbox" checked name="crud[1][id][show_in_detail_page]" value="yes">
  | </td>
  | <td>
  | <div class="col-md-12">
  | <div class="form-group ">
  | <select  class="form-control chosen chosen-select input_type" name="crud[1][id][input_type]" id="input_type" tabi-ndex="5" data-placeholder="Select Type" >
  | <option value="" class="<!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>Database Error</title>
  | <style type="text/css">
  |  
  | ::selection { background-color: #E13300; color: white; }
  | ::-moz-selection { background-color: #E13300; color: white; }
  |  
  | body {
  | background-color: #fff;
  | margin: 40px;
  | font: 13px/20px normal Helvetica, Arial, sans-serif;
  | color: #4F5155;
  | }
  |  
  | a {
  | color: #003399;
  | background-color: transparent;
  | font-weight: normal;
  | }
  |  
  | h1 {
  | color: #444;
  | background-color: transparent;
  | border-bottom: 1px solid #D0D0D0;
  | font-size: 19px;
  | font-weight: normal;
  | margin: 0 0 14px 0;
  | padding: 14px 15px 10px 15px;
  | }
  |  
  | code {
  | font-family: Consolas, Monaco, Courier New, Courier, monospace;
  | font-size: 12px;
  | background-color: #f9f9f9;
  | border: 1px solid #D0D0D0;
  | color: #002166;
  | display: block;
  | margin: 14px 0 14px 0;
  | padding: 12px 10px 12px 10px;
  | }
  |  
  | #container {
  | margin: 10px;
  | border: 1px solid #D0D0D0;
  | box-shadow: 0 0 8px #D0D0D0;
  | }
  |  
  | p {
  | margin: 12px 15px 12px 15px;
  | }
  | </style>
  | </head>
  | <body>
  | <div id="container">
  | <h1>A Database Error Occurred</h1>
  | <p>Error Number: 1055</p><p>Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'purplesm_panel.crud_input_type.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by</p><p>SELECT *
  | FROM `crud_input_type`
  | GROUP BY `validation_group`</p><p>Filename: /home/purplesmarttv/public_html/crd/modules/crud/models/Model_crud.php</p><p>Line Number: 88</p>	</div>
  | </body>
  | </html>
  |  
  |  

`

**Comment by ridwanskaterock** [comment]
can you visit yourdomain.com/web/set_full_group_sql  to enable full group ? 

what's your php version and cicool version thanks

**Comment by darshanvithani** [comment]
set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';


i already perform but not work 

3.0.3. CICOOL version

PHP 7.1

**Comment by darshanvithani** [comment]
i think it solve
