### ISSUE TITLE
I have a problem install Wizzard on Linux server

### ISSUE THREAD

**Issue by MediaMetz** [ridwanskaterock/cicool#44]
I have my site on Plesk. With the local SQL-Server, I become the message:"An Error Was Encountered The action you have requested is not allowed.".
With the Amazon AWS SQL-Server is my last setup page blank.

Local installation with AWS works.

What can I do.

**Comment by ridwanskaterock** [comment]
you can read the soame issue first 

https://github.com/ridwanskaterock/cicool/issues/5
https://github.com/ridwanskaterock/cicool/issues/4

thanks :)
