### ISSUE TITLE
Page display issue...

### ISSUE THREAD

**Issue by fxraider** [ridwanskaterock/cicool#441]
I noticed an oddity that affects all pages... if I visit the dashboard, for example then it looks correct:
![image](https://user-images.githubusercontent.com/47027100/104601921-bc479380-5672-11eb-80fe-19df2fb4c938.png)
If I then collapse the sidebar, everything still looks okay:
![image](https://user-images.githubusercontent.com/47027100/104602268-22ccb180-5673-11eb-8db3-26035d44f032.png)
...but if I then hover over the sidebar, the right margin shifts and distorts the page content:
![image](https://user-images.githubusercontent.com/47027100/104602497-60c9d580-5673-11eb-8907-5feb8c609ed2.png)

I assume it's just a CSS issue - hopefully you can post the fix quickly

** same issue in Edge, Chrome & FF

**Comment by fxraider** [comment]
Any thoughts on how to resolve this? It looks very unprofessional :(

**Comment by ridwanskaterock** [comment]
Hi you can try change this code like that 

![image](https://user-images.githubusercontent.com/9270445/105028775-09b56d80-5a84-11eb-84d3-27c3b58076d8.png)

asset/css/custom.css

**Comment by fxraider** [comment]
Yes - that worked :)
