### ISSUE TITLE
Wizzard was not found on this server

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#45]
Selamat Pagi Mas Ridwan,

Saya baru saja membeli Cicool.
Mohon bantuannya karena saya temukan error setelah folder cicool saya upload ke dalam folder www di WAMP Server

http://localhost:8080/cicool/wizzard/setup
![image](https://cloud.githubusercontent.com/assets/9460402/24736398/07205f28-1ab2-11e7-82dd-cb768b589102.png)

apakah ada settingan yang kurang ??

**Comment by ridwanskaterock** [comment]
halo mas apa mas instalnya di sub folder mugkin ? 

atau mod rewrite belum di aktifkan pada setingan server mas ? 

mas coba buka localhost:8080/cicool/index.php kalo tampil berarti mod_rewrite belum di aktifkan mas, 


trimakasih

**Comment by ogutsinyo** [comment]
Terima kasih atas feedbacknya mas ridwan.

mod_rewrite nya sdh aktif.
saya test buka localhost:8080/cicool/index.php yang muncul spt ini.
![image](https://cloud.githubusercontent.com/assets/9460402/24737415/a79df7ca-1ab8-11e7-951c-becdbc173293.png)

**Comment by ogutsinyo** [comment]
saya tidak instal di subfolder
![image](https://cloud.githubusercontent.com/assets/9460402/24737458/1746abee-1ab9-11e7-8dd7-cd68ed5315b2.png)
ini juga pic bahwa mod_rewrite ON
![image](https://cloud.githubusercontent.com/assets/9460402/24737473/343a5458-1ab9-11e7-818f-6abd7b7c9adb.png)

**Comment by ridwanskaterock** [comment]
oke mas sama sam, mas coba rubah 

di file application/config/config.php 

pada baris $config['index_page'] = ''; rubah ke $config['index_page'] = 'index.php';

dan buka pada 

application/views/bacend/core_template/config_template.txt

pada baris $config['index_page'] = ''; rubah ke $config['index_page'] = 'index.php';

**Comment by ogutsinyo** [comment]
terima kasih atas respon-nya mas.

saya sudah coba melakukannya dan berhasil.
![image](https://cloud.githubusercontent.com/assets/9460402/24738122/d806531c-1abd-11e7-83b2-20553856daba.png)
Pertanyaan saya 
apakah $config['index_page'] = 'index.php'; dan  $config['index_page'] = 'index.php'; pada application/view/backend/core_template/config_template.txt merupakan bagian dari setting awal yang harus dipenuhi sehingga wizzardnya tampil/dapat dijalankan ?

**Comment by ogutsinyo** [comment]
Step 2 nya error lagi ternyata mas ...
![image](https://cloud.githubusercontent.com/assets/9460402/24738203/568a3280-1abe-11e7-97a8-34020f305373.png)

**Comment by ridwanskaterock** [comment]
owh tampil ya ? 

engga mas seharunya itu ga perlu di config lagi, 

kalo htaccessnya kebaca / mod_rewrite sdh di aktifkan, 

baiknya cari solusi kenapa htaccess ga kebaca di server mas, 

mas sudah pernah coba pakai htaccess pada project lain di server mas  (local) ?

**Comment by ogutsinyo** [comment]
ok sepertinya itu masalah di htaccess
soalnya saya pernah rubah sedikit.

sekarang jadinya harus pake index.php dulu baru bisa lanjut. hahahahah .... terima kasih mas

**Comment by ridwanskaterock** [comment]
hehe iya mas oke sippp
