### ISSUE TITLE
Akses level berubah ketika saya ubah Nama Group Admin

### ISSUE THREAD

**Issue by jinbatsu** [ridwanskaterock/cicool#451]
Mohon infonya, apakah di coding dikunci dengan nama Admin? Bukan dengan ID Admin yaitu 1.
Saya ingin ubah untuk permission Admin yg full ini adalah group Developer misalnya.
Terimakasih

**Comment by jinbatsu** [comment]
Maksudnya ketika saya ubah nama group **Admin** menjadi yg lain misal Developer.
Maka login saya tidak bisa akses ke Dashboard.

**Comment by ridwanskaterock** [comment]
ya betul bawaan dari library menggunakan name dan jika ada perubahan harus di setel di sini

![image](https://user-images.githubusercontent.com/9270445/107525707-b00b1380-6be9-11eb-9c0e-0a1e2239aa69.png)


application/config/aauth.php
