### ISSUE TITLE
How to Regenerate Token from API?

### ISSUE THREAD

**Issue by jinbatsu** [ridwanskaterock/cicool#456]
Hi, how can we regenerate new token, because it can be expired, but it should not if the member is still active.
Or how actually work it is? Is is auto changed the expire date? if the user request api (get data of hotel for example) ?
Not needed new Token for expired Token?

So for example the Expire Token set is 7 days.
What I'm thinking is, if user login, then the Token save it to device. After that, user request API in the next day, day 6 still active. After 7 days, is Token still valid? How to I get new Token? Thanks.

---
Bahasa Indonesa: Saya ingin bertanya masalah API Token, kalau misalkan 7 hari expired, gimana cara user tetap login ketika di hari ke-7 nya itu padahal masih lagi aktif. Makasih.

**Comment by ridwanskaterock** [comment]
Hello - depends on how you want to use the application.

You could use localStorage / sessionStorage to keep the tokens.
You could populate the storage data using interceptors or events.


for refresh token for now not available on API 

yes you can increase for expired date and re-login after expired


also, you can modify  for an API request token 
![image](https://user-images.githubusercontent.com/9270445/111018644-93324d80-83ec-11eb-82b7-ee7bfac91627.png)

for a regenerate token by put token Payload

**Comment by jinbatsu** [comment]
> You could use localStorage / sessionStorage to keep the tokens.

Yes, token stored in the device consumer, the question is how to regerate new token from token request.
And the expire time is not the solution, because it will be direct logout after expired, even the user is active in the last day of expired if I'm not wrong, I'm not sure though how actually work here.

What I'm thinking is request a new token from active token, so that it will never expire as long as in the range of one week (for example, just like session in browser). After one week, thats OK token tobe expire and user can re-login.


> yes you can increase for expired date and re-login after expired
Yes, what I'm aware is because if the user is still in active request on application, suddently expired, not in the range of expired date, even if I set to one year for example.

**Comment by jinbatsu** [comment]
> Another question, is there any code for determine if the Rest API Request require a Token or not, outside from the CRUD API.

I found this.. it is on second parameter in is_allowed function.
```
$this->is_allowed('api_sample', false); // disable token
$this->is_allowed('api_sample'); // default true
```
