### ISSUE TITLE
show Eccomerce in front end

### ISSUE THREAD

**Issue by danielmdd** [ridwanskaterock/cicool#459]
I install Ecoomerce.
How to show the Ecommerce plugin on the frontend

**Comment by ridwanskaterock** [comment]
Hi In setting page set home page option to cicool-ecommerce

Pada tanggal Jum, 26 Mar 2021 18.07, danielmdd ***@***.***>
menulis:

**Comment by danielmdd** [comment]
Thaks for all.
Great work
