### ISSUE TITLE
Edit/Adding Page Builder

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#46]
Siang mas,

ada beberapa pertanyaan nih, semoga bisa dibantu 

1. jika di page builder ingin saya tambahkan ataupun diubah total bisa dan dimana saya bagian mana harus  saya lakukan ?
2. ada masalah atau tidak jika ditambahkan file pdf yang diembed ?
3. untuk grafik, apakah semua bentuk grafik sudah bisa langsung di jalankan ?

terima kasih,

**Comment by ridwanskaterock** [comment]
halo mas, 

untuk point no 

1. itu bisa di rubah pada application/views/backend/standart/administrator/page/page_add.php dan application/views/backend/standart/administrator/page/page_update.php
2. saya kira ga masalah mas jika menggunakan iframe
3. untuk grafik ya sudah bisa di custom, dan data yang di buat hanya dummy, untuk formatnya bisa di buat sesuai dengan format data grafiknya

**Comment by ogutsinyo** [comment]
Ok Thanks buat infonya

**Comment by ridwanskaterock** [comment]
oke mas sama sama
