### ISSUE TITLE
Add menu parent

### ISSUE THREAD

**Issue by martonoskom** [ridwanskaterock/cicool#478]
![image](https://user-images.githubusercontent.com/25054846/130440975-5b93551d-6e3a-422e-965a-1bdd3c622131.png)

mas mau nanya, gimana cara menambah menu parent di halaman header utama home, di navigation?

**Comment by martonoskom** [comment]
misal menu Blog, pas di klik muncul menu dropdown mas ?

**Comment by ridwanskaterock** [comment]
Yang frontend sepertinya blm bisa mas bisa di custom di
cc-content/themes/cicool/navigation.php



Pada tanggal Sen, 23 Agt 2021 18.39, martonoskom ***@***.***>
menulis:
