### ISSUE TITLE
JQuery and other librarys not loading When creating/Adding CRUD, FORM

### ISSUE THREAD

**Issue by Fazmin** [ridwanskaterock/cicool#48]
Here is a console log output. Everything else works fine. Adding pages works fine, Just the CRUD add and Forms Add does not work. here is a screenshot of the page I get.
![screenshot-065](https://cloud.githubusercontent.com/assets/1432117/24878085/b2833570-1dff-11e7-9d3b-36cf37b2e30c.jpg)

This the Chrome source file list.
![screenshot-064](https://cloud.githubusercontent.com/assets/1432117/24878008/5ae73dc0-1dff-11e7-90ef-bcaa4094affa.jpg)

[console_log_output.txt](https://github.com/ridwanskaterock/cicool/files/911163/console_log_output.txt)

**Comment by krecco** [comment]
Looks like we are having same problem #49

**Comment by ridwanskaterock** [comment]
please see the console browser about this 
thanks
