### ISSUE TITLE
The action you have requested is not allowed.

### ISSUE THREAD

**Issue by mjhcremer** [ridwanskaterock/cicool#5]
I have changed  $config['csrf_protection'] = TRUE; into $config['csrf_protection'] = FALSE;
But still the same error.

**Comment by ridwanskaterock** [comment]
whether your problem as this issue https://github.com/ridwanskaterock/cicool/issues/6 ?

**Comment by mjhcremer** [comment]
The change to development did not helped. I saw nothing different.
My PHP version = 7.0, mysql version = 10.0.27-MariaDB-cll-lve and my
webservers OS is Linux with Apache

Met vriendelijke groet,
Mario Cremer

2017-01-04 8:33 GMT+01:00 Muhamad Ridwan <notifications@github.com>:

**Comment by R3N3G** [comment]
Hello,

Can you activate php loggin with this guide?

https://support.managed.com/kb/a1937/how-to-enable-php-error-logging-in-plesk-11.aspx

With these, you will have a log file in the root of the domain.

Edit it and copy & paste here the last lines of logfile after you start the step one of wizard to break installation.

Second, 

In /application/config/config.php set 
$config['log_threshold'] = 4;
or use a higher number, depending on how much detail you want in your logs
Remember than every time you install the config file is overwrited and you need to change log_thresold value every time you get step 3.
Also paste logfile here please.

Thank you.

**Comment by R3N3G** [comment]
With codeigniter log only, can help you, i believe

**Comment by R3N3G** [comment]
Are you using nginx and nproxy, I disabled on my plesk onyx and I disabled php-fpm also

**Comment by mjhcremer** [comment]
I really do not know where you are talking about. I have an account with an
hosting provider. I only know some php. But I am really no programmer.

Met vriendelijke groet,
Mario Cremer

2017-01-05 22:06 GMT+01:00 R3N3G <notifications@github.com>:

**Comment by ridwanskaterock** [comment]
maybe the customer support hosting provider you use can help to counter this problem Mario Cremer,

to be able to see php error log, and we will help you as soon as possible for the next :)

hopefully can help, we are waiting for good news from you

thank you

**Comment by R3N3G** [comment]
I wait, if you can test it, step by step codeigniter log activation

Join hosting control panel or ftp
Go to codeigniter dir files, and 
join to application/config/ directory 
Edit config.php and search this line
$config['log_threshold'] = 0;
Change it to 4 and save it,
Start cicool installation to broke installation or get error,
Go to application/logs directory 
Copy and post here the content of file log. It's possible than the file have no extension or rare extension, edit with code editor of file manager or for ftp, also you can upload file directly here o send by email.

Thanks a lot.

**Comment by ridwanskaterock** [comment]
if we could see what happens to the error cicool your application,

if you please please send the error log / screenshot to us?

we could not make a similar error problem, we installed both windows and linux environtment

thank you

**Comment by mjhcremer** [comment]
The help from my hosting provider is very poor. But I resolved the issue. I followed the steps in wizzard.php for step 3. The file config/site.php was missing. I made it myself en filled it with the things that the program will do. There was no user created. I registerd an user through the interface. We can close the issue. If something else will occur, I will create an new ticket.

**Comment by ridwanskaterock** [comment]
good mjhcremer,

I'm glad you managed to finish it,

I will help support you in the future.

I wait for the best reviews of your thanks :)
