### ISSUE TITLE
/wizzard/setup was not found

### ISSUE THREAD

**Issue by TomsUsername** [ridwanskaterock/cicool#50]
i dont have the wizzard in my download 
![image](https://cloud.githubusercontent.com/assets/21271709/24959296/5f0abb9a-1f60-11e7-8b58-589272c1e0bf.png)

**Comment by ridwanskaterock** [comment]
wizard located at application/controllers/wizard.php
You can access it via localhost/cicool

thanks

**Comment by TomsUsername** [comment]
was my fault tho I did have issue #4 as well it is also resolved
