### ISSUE TITLE
API - Multiple filtering and Sorting/Ordering

### ISSUE THREAD

**Issue by Fazmin** [ridwanskaterock/cicool#51]
I know its possible to use filter one field, limit and give a starting index as follows.
/api/<crud>/all/?filter=<fieldVal>&field=<feild>&limit=10

However is it possible to give MULTIPLE filtering fields and sort or ORDER by ASC or DESC by field value directly using the API?

**Comment by Fazmin** [comment]
Is it possible to increase token to NOT expire. it expires now in 7200 seconds.

**Comment by ridwanskaterock** [comment]
sorry multi filter currently not available I would consider for the next update, :)

for token expires you can change config on your backend 


![image](https://cloud.githubusercontent.com/assets/9270445/24995196/138380b4-2058-11e7-920a-529c9d7b8b44.png)


thanks

**Comment by Fazmin** [comment]
I figured out the token expiration settings. Looking forward to your next update. thank you.

**Comment by ridwanskaterock** [comment]
yes for now token expired same of session expired thanks for feedback 

i will add a feature on next update  :)

**Comment by zkenstein** [comment]
> sorry multi filter currently not available I would consider for the next update, :)
> 
> for token expires you can change config on your backend
> 
> ![image](https://cloud.githubusercontent.com/assets/9270445/24995196/138380b4-2058-11e7-920a-529c9d7b8b44.png)
> 
> thanks

gan yang ini udah ada fiturnya? biar lebih mudah jg gan, drpd edit module api nya satu2

Nice Script, thanks
