### ISSUE TITLE
CRUD acak2an hasilnya 

### ISSUE THREAD

**Issue by jawaradigital** [ridwanskaterock/cicool#513]
![Screenshot_63](https://user-images.githubusercontent.com/108110479/176854151-70119014-3f46-446d-a7eb-594e4ab11880.png)

Mohon bantuannya om kenapa ya jadi ga sejajar gini,,,

**Comment by ridwanskaterock** [comment]
ok trimakasih sudah di updated di versi terbaru @axixu
