### ISSUE TITLE
Install WARNING on setup cannot proceed

### ISSUE THREAD

**Issue by 101suchtm101** [ridwanskaterock/cicool#515]
Hey everyone I commence the install and get a warning on the first page and when I do next it loops to the start and does not allow DB setup.  Everyting else is GREEN.  Any ideas how to move forward?

![image](https://user-images.githubusercontent.com/110167308/181483370-7a2f0fb0-7178-4b7f-940c-a5b925ffb48d.png)

**Comment by ridwanskaterock** [comment]
Hi for now support on php 7.3 i think you use php 7.4

**Comment by 101suchtm101** [comment]
> Hi for now support on php 7.3 i think you use php 7.4

Oh okay I will setup and account running 7.3 so I can use this.
