### ISSUE TITLE
use the crud from the blog table in the FrontEnd page / blog

### ISSUE THREAD

**Issue by jantonymal** [ridwanskaterock/cicool#52]
This Very complete I only have a doubt ... ???
How can I use the crud from the blog table in the FrontEnd page / blog to display the data from the blog table. Can you give me an example? Thank you.

**Comment by ridwanskaterock** [comment]
for display row database on frontend you can 
open file `cc-content/themes/cicool/views/home.php`

and you can display the database by write code 

like 
```


<?php 
foreach ($this->model_blog->get() as $blog) {
    echo $blog->name;
}
```


thanks
