### ISSUE TITLE
French localization

### ISSUE THREAD

**Issue by gaudrick** [ridwanskaterock/cicool#54]
Hi

cannot find the localisation for french. have error : unable to load the requested language file: language/french/form_validation_lang.php

**Comment by ridwanskaterock** [comment]
for form validation lang you can download the file 

https://github.com/bcit-ci/codeigniter3-translations/archive/master.zip


and install 
on yourappp/application/

thanks

**Comment by gaudrick** [comment]
yes sorry for confusion but even if CI3 language files deployed the admin interface backend still in english. Config.php is setup for french... I need front end and backend if french nobody speak english here

**Comment by ridwanskaterock** [comment]
Yes for the backend like menu for other berbahasi / multilanguage is being prepared for the next update,
thanks,
Hopefully you can help this development I wait for a good review from you very thanks :)
