### ISSUE TITLE
Cicool Icon tidak tampil

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#55]
Siang mas,

setelah beberap kali testing aplikasi cicool lbh sering tidak menampilkan icon yang ada malah lebih sering bentuk icon kotak dengan warna.

bagaimana cara memperbaikinya ya?
![cicool - icon tidak muncul](https://cloud.githubusercontent.com/assets/9460402/25323147/a3860bc2-28e7-11e7-88d9-a0e694d745fa.PNG)

**Comment by ridwanskaterock** [comment]
sebelumnya pada saat test apa PC mas terkoneksi dengan internet, 

itu fontawesomenya mas, dan di ambil dari CDN https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css

trimakasih

**Comment by ogutsinyo** [comment]
PC tidak terkoneksi dengan internet mas.
Jadi icon itu link dan aktif saat terkoneksi ke internet saja ya?

**Comment by ridwanskaterock** [comment]
iya mas saat terkoneksi dengan internet bila tidak terkoneksi dengan internet mas bisa mendownload 

fontawesome untuk versi offlinenya 

dan di load pada aplikasi
