### ISSUE TITLE
Page builder not working

### ISSUE THREAD

**Issue by imamimam113** [ridwanskaterock/cicool#551]
just bought it recently in code canyon, i have the license key, i have a problem, the page builder not working, it doesn't show the preview

**Comment by ridwanskaterock** [comment]
Hi when you move to preview tab, can you see xhr reponse in browser network
tab , and see response is ok or not ?

Thanks

Pada tanggal Sel, 5 Sep 2023 18:11, imamimam113 ***@***.***>
menulis:

**Comment by imamimam113** [comment]
![Admin _ onewb _ Page Update - Google Chrome 9_6_2023 12_23_42 AM](https://github.com/ridwanskaterock/cicool/assets/143862420/ffbed083-629c-4ded-a6e5-2f6b7cdf4aa3)

**Comment by imamimam113** [comment]
sudah ketemu masalahnya, kirain udah bisa di php 8.1 ternyata belum
