### ISSUE TITLE
Create Blog

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#56]
Siang Mas,

Saya berencana untuk membuat fasilitas untuk memudahkan user dalam hal menambahkan BLOG.
Jadi semua member dapat membuat blog yang ditampung ke dalam database kemudian setelah di approve maka blog tersebut dapat ditampilkan ke dalam website.

Masalahnya, saya mencoba membuat blog : crud builder, page, menu, tools blog namun informasi-nya tidak dapat di link ke dalam menu blog.

![crud baru sdh dibuat](https://cloud.githubusercontent.com/assets/9460402/25323290/83cb2942-28e8-11e7-8a69-6c2024a2f330.PNG)
CRUD untuk blognya

![page juga sudah dibuat](https://cloud.githubusercontent.com/assets/9460402/25323309/9a6b9a42-28e8-11e7-9a24-76d35b390d59.PNG)
PAGE untuk blognya

![menu juga sudah saya buat](https://cloud.githubusercontent.com/assets/9460402/25323321/a781fb54-28e8-11e7-87d8-a1a46b48012b.PNG)
MENU untuk blognya

![blog menu juga sudah aktif](https://cloud.githubusercontent.com/assets/9460402/25323335/bcaf0abc-28e8-11e7-9e6b-0a95961de3c9.PNG)
Ini BLOG MENU nya

![ini info blog yang seharusnya ditampilkan](https://cloud.githubusercontent.com/assets/9460402/25323452/93827fce-28e9-11e7-98da-e2f33700978a.PNG)
Informasi yang harus ditampilkan di  front-end website pada menu BLOG adalah informasi ini

Mohon solusinya

**Comment by ridwanskaterock** [comment]
Untuk Blog sudah tersedia di versi terakhir https://www.youtube.com/watch?v=GgOA_tcDL9I thanks
