### ISSUE TITLE
DASHBOARD tidak menampilkan data yang sesungguhnya

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#57]
![crud page builder dashboard tidak menampilkan jumlah crud dan page yang sudah dibuat](https://cloud.githubusercontent.com/assets/9460402/25323519/eaf32efc-28e9-11e7-8c5e-f17e98392aeb.PNG)
Untuk CRUD sudah bertambah datanya dan page juga sudah, namun pada dashboard nilainya masih kosong (seperti terlihat pada gambar)

Kenapa begitu ya mas?

![bisakah data tersebut diambil dari tabel dan ditampilkan sesuai bentuk grafik yang kita mau](https://cloud.githubusercontent.com/assets/9460402/25323546/204dfd5c-28ea-11e7-832f-f654a3b34c18.PNG)
Bisakah datanya dari grafik diambil dari tabel dan grafiknya disesuaikan dengan pilihan kita sendiri ?

**Comment by adadion** [comment]
bantu jawab, itu cuma sample mas.
chart bisa dibikin sendiri.
itu pakai template adminLTE

**Comment by ogutsinyo** [comment]
maaf mas dion,

saya tau itu template dibuat pake adminLTE.
saya tau juga kl grafiknya itu sample.

pertanyaannya adalah saat saya menambahkan kenapa data CRUD yg saya buat tidak ter-update di dashboard? apa tidak terkoneksi secara langsung? seharusnya kan dashboard terkoneksi dengan data yang kita masukan.

**Comment by adadion** [comment]
Ya soalnya mas sinyo belum buat chart sebelumnya, jadi chart ga terupdate. Chart yang tampil di dashboard saat ini (bawaan cicool) itu sample data aja, bukan hasil otomatis dari crud, murni bikin sendiri. Karena emang ga ada fitur chart builder mas setagu saya.

**Comment by ridwanskaterock** [comment]
yupp betul chart di dashboard hanya example saja mas, itu bisa di custom dengan menyesuaikan datanya aja
