### ISSUE TITLE
Drag n Drop tidak berfungsi

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#58]
Siang mas,

Menu drag n drop nya tidak berfungsi dengan sewajarnya.
Padahal belum ada yang saya ubah setting2nya.
Mohon pencerahannya

**Comment by ridwanskaterock** [comment]
maksudnya ini menu drag and drop apa mas ? 

module menu ? 

bisa lihat console di browsernya mas ?

**Comment by ogutsinyo** [comment]
saat kita membuat CRUD Builder, dimana field2 yang ada dapat di drag n drop dari atas ke bawah sesuai keinginan kita. tapi hal itu tidak dapat saya lakukan.

seperti contoh di video : https://www.youtube.com/watch?v=wSnQkgMjyFk

Mohon solusinya

**Comment by ridwanskaterock** [comment]
bisa coba tekan tompol F12 terus klik tab console mas, nanti ss ke saya ya 

thanks

**Comment by ogutsinyo** [comment]
Selamat malam mas,

Berikut tampilan F12 - Tab Console Google Chrome
![f12-console tab](https://cloud.githubusercontent.com/assets/9460402/25336826/6f9893ca-2923-11e7-8983-c78df8697747.PNG)

saat Anda minta SS di atas, saya test lagi malah bisa dilakukan namun saat di drag tidak jelas mana yang di drag tapi tiba-tiba pindah ke atas. tapi bisa di drag kok sampai saat ini.

nanti saya coba kirim keanehannya seperti apa pakai snagit.

thanks,

**Comment by ridwanskaterock** [comment]
itu di chroome apa di firefox mas ?

**Comment by ogutsinyo** [comment]
Di chrome mas
