### ISSUE TITLE
Where i could download v2 of Cicool

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#59]
Mas,

dimana saya bisa download Cicool v2 nya?

**Comment by ridwanskaterock** [comment]
mas sebelumnya purchase cicool pada codecanyon ? 

itu yang di download sudah versi terakhir mas / v2

**Comment by ogutsinyo** [comment]
Iya saya download lewat codecanyon.
Oh Ok, tapi di tampilannya masih versi lama/v1.9.5 ya

**Comment by ridwanskaterock** [comment]
iya mas maaf labelnya belum saya rubah :-) 

trimakasih mas atas feedbacknya, di tunggu rating terbaiknya :)
