### ISSUE TITLE
connecting with other databases ?

### ISSUE THREAD

**Issue by ogutsinyo** [ridwanskaterock/cicool#60]
Siang mas,

Apakah dabatase buatan sendiri dapat digabungkan dengan databse cicool pada saat cicool pertama kali diinstall?

![cicool - dikoneksikan dengan database berbeda tidak ada tampilan apapa](https://cloud.githubusercontent.com/assets/9460402/25324776/df544114-28f1-11e7-8362-e5367e38e459.PNG)

**Comment by ridwanskaterock** [comment]
bisa mas asalkan tidak ada nama table yang sama thanks

**Comment by ogutsinyo** [comment]
Ok mas.
artinya lebih aman kl tablenya dipindah ke database cicool saja ya.

**Comment by ridwanskaterock** [comment]
iya mas lebih baik begitu mas hehe
