### ISSUE TITLE
The cicool installer stop after step 3

### ISSUE THREAD

**Issue by xemmex** [ridwanskaterock/cicool#61]
Hi,

The installer stop after step 3 … I did provide all the right informations and all test are green… but cannot install it

All files that need to be writable are in chmode777.
This is my server profile : http://boisdechauffage.gq/phpinfo.php

I have no time to lose with this, so if you can you just provide the default DB so I can work with it, that would be appreciated!

Thanks!

**Comment by xemmex** [comment]
**This is what I hit after step 3 in development mode :**

A PHP Error was encountered

Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 118

Backtrace:

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 116
Function: library

File: /home/boisdechauffage/public_html/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 116
Function: library

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 98
Function: library

File: /home/boisdechauffage/public_html/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/boisdechauffage/public_html/index.php
Line: 316
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/boisdechauffage/public_html/system/core/Exceptions.php:272)

Filename: core/Common.php

Line Number: 568

Backtrace:

An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: /home/boisdechauffage/public_html/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 120

Backtrace:

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 116
Function: library

File: /home/boisdechauffage/public_html/application/libraries/Aauth.php
Line: 97
Function: library

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 116
Function: library

File: /home/boisdechauffage/public_html/application/core/My_Loader.php
Line: 98
Function: library

File: /home/boisdechauffage/public_html/application/controllers/Wizzard.php
Line: 177
Function: library

File: /home/boisdechauffage/public_html/index.php
Line: 316
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: fopen(b0f513aec1f9e0a48189d59c6a097f10686b24d4): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 157

Backtrace:

A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct ()

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by ridwanskaterock** [comment]
Actually i am from saturday - this monday has red date (weekend) in my country, so sorry if slow response :)

**Comment by ridwanskaterock** [comment]
you can try and learn for same issue in codeigniter with your server 

http://stackoverflow.com/questions/31042456/session-error-in-codeigniter

thanks

**Comment by xemmex** [comment]
Still not working even after replacing $config['sess_save_path'] = NULL; for $config['sess_save_path'] = sys_get_temp_dir();

**Comment by xemmex** [comment]
Please just send me an empty DB formated along with an admin user and password.
I cannot wait until your installer works!!!!

**Comment by ridwanskaterock** [comment]
It's a problem not because the installer, it's a problem because the session can not save to the tmp file, you can see where the tmp file is located and you can set $ config ['sess_save_path'] = ''; With the location of the tmp folder on your server

thanks

**Comment by ridwanskaterock** [comment]
database structure attached 

https://www.dropbox.com/s/7smeevucaruie0e/cicool.zip?dl=0

thanks

**Comment by xemmex** [comment]
Hi,

Even if I set the temp path with the right folder, the wizard still stop at the step 3!
$config['sess_save_path'] = '/home/boisdechauffage/tmp';

There is something wrong with your installer!

I have upload the database but the installer still considered uninstalled and bring me to the wizard again and again ... :(

**Comment by ridwanskaterock** [comment]
What kind of problem can I see a screenshot?
I've tested it from various environtment, and it's running smothly :)
Do you use MAC, Linux / windows?

thanks

**Comment by xemmex** [comment]
It is on Linux... I have already write the error that I got... and even if I add manually the right tmp realpath it is not working. $config['sess_save_path'] = '/home/boisdechauffage/tmp';

Do you have a version that do not use your installer ? Really it would be easier for all of us! I mean a version with all the file allready created such as home controler etc...

Because now I am losing precious time on this project!

Thanks!

**Comment by ridwanskaterock** [comment]
For inactive installer you can set db manually on

Application/config/database.php

And you can make application/confog/site.php for inactive installer

And next you can dump sql file

Thanks

**Comment by xemmex** [comment]
There is no site.php in application/config/ folder

**Comment by xemmex** [comment]
Can you provide the site.php file ?

**Comment by ridwanskaterock** [comment]
Because the site.php is made by the system make sure the application / config folder can be to write

**Comment by ridwanskaterock** [comment]
simple content for site.php

<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| Your site name,
|
*/
$config['site_name'] = 'cicool';

thanks

**Comment by xemmex** [comment]
Thanks! It works now! :)

When I create a crud using the crud builder, will it works if I have some foreign keys with fiew other tables ?
