### ISSUE TITLE
Howto Spanish datetimepicker and...

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#62]
Hello,

I'm trying to change the datetimepicker to spanish, but searching on documentation I view than have a spanish translation now, How Can I use with cicool?

I want to add 30 minutes steps also on datetimepicker, at this moment, I can choose 1:00,2:00,3:00, but I want to add steps as 1:00, 1:30, 2:00, 2:30, 3:00, 3:30...

Are there an easy solution, Where files I want to change it fast?

Thanks a lot.

**Comment by ridwanskaterock** [comment]
hiii you can custom datetimepicker config on 

asset/js/custom.js

for datetimepicker function :) 

thanks

**Comment by R3N3G** [comment]
thank you!!
