### ISSUE TITLE
The requested URL /administrator/login was not found on this server.

### ISSUE THREAD

**Issue by adadion** [ridwanskaterock/cicool#63]
Mas Ridwan, I finished on my local server, then I upload to remote server in subdomain level.

**subdomain**.domain.com

I have already configure the database. (Change db username, db password, and db name).

I have already change the BASE_URL in application/config.php to 'http://subdomain.domain.com/' , but still didn't work.

Front end nya mau muncul, but when i clicked on login or dashboard, it won't work.

> The requested URL /administrator/login was not found on this server.

Mohon pencerahannya mas.

**Comment by ridwanskaterock** [comment]
jik akses http://subdomain.domain.com/index.php/administrator/login bagaimana mas ? apa masih notfound

**Comment by adadion** [comment]
Bisa mas, haha. Berarti saya harus gimana?

**Comment by ridwanskaterock** [comment]
itu di server Apache / Nginx sepertinya blm di aktifin mas mod rewritenya, 

http://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2

thanks

**Comment by adadion** [comment]
mod rewrite sudah aktif tu mas. atau .htaccessnya perlu modifikasi?
soalnya `$config['index_page'] = '';` --> sudah saya setting kosongan.

**Comment by ridwanskaterock** [comment]
ini mas pakai apache / nginx mas ?

**Comment by ridwanskaterock** [comment]
tapi kalo bukan subdomain bisa ya ?

**Comment by adadion** [comment]
apache mas. kalo cuma domain belum coba mas, ga ada domain nganggur. 
saya coba setting `$config['index_page'] = 'index.php';` udah bisa mas.

masalahnya, sepertinya controller ga mau jalan.
saya coba rubah deskripsi dsb di menu setting, pas save error.
trus coba lihat access list dari menu Auth juga error, ga ada list nya sama sekali.

**Comment by adadion** [comment]
sudah bisa mas. 
.htaccess nya saya tambahin -->     `RewriteBase /`

referensi dari jawaban http://stackoverflow.com/a/5758551/5262697.

list access sudah bisa, simpan setting juga bisa.
semoga lancar. haha.

Trims mas, sukses selalu.
