### ISSUE TITLE
Chain Select Field

### ISSUE THREAD

**Issue by pututik** [ridwanskaterock/cicool#64]
Hi Mas Ridwan,

Maybe you can add this feature for the next update, i think this good for others too.
I could add using ajax or jquery to change or display one form _selection field_ from another _selection field_ . But if it available on form builder or crud already it would be easy.

For example:
Select Brand <master selection>
Select Type  <will filter shown select value after brand selected>
Select Color <will filter shown select value after type selected>
and so on. 

Or how we can in controller for global chain select option?

**Comment by ridwanskaterock** [comment]
Hii for now

Chained input type not available for current version.

I will make this for next version

For now you can custom code for make chained input type

Thanks for feedback :)
