### ISSUE TITLE
Page Builder error while try to save

### ISSUE THREAD

**Issue by spideyrex** [ridwanskaterock/cicool#65]
warning! ×  Error save data

RUjuk gambar dibawah

![errorsavee](https://cloud.githubusercontent.com/assets/7654292/25672789/af866d40-3067-11e7-91bd-2d3c84c61413.JPG)

**Comment by ridwanskaterock** [comment]
hii thanks for purchase

before you can open console and click table network and you can see error on XHR response 

thanks

**Comment by spideyrex** [comment]
what do you mean by that. Can you explain maybe in picture

**Comment by spideyrex** [comment]
could you guide me to fix this

**Comment by spideyrex** [comment]
hi i need answer for this

**Comment by ridwanskaterock** [comment]
Hii excuse me many issues that are not monitored, in mozilla you can press f12 / right click inspect element.

Then you click the network tab there you can see the response when the page is saved

Sorry for the delay 😓

**Comment by ridwanskaterock** [comment]
see the picture 
![8hbvg](https://cloud.githubusercontent.com/assets/9270445/26496268/ff36f90e-4250-11e7-93c6-9e1720569f4c.png)
