### ISSUE TITLE
Installation problem!!!

### ISSUE THREAD

**Issue by wadaeko** [ridwanskaterock/cicool#66]
I have just bought Cicool and during the process of installation, after completing step 3 of the wizard it refresh for a empty page. There is not any FINISH button and even repeating or restarting the installation process, it keeps doing the same.

I am in hurry with a project and I need a help to solve it.

thanks in advance
regards, 

Wada

**Comment by wadaeko** [comment]
Just to complement, I tried all the procedures at issue #61 which reported exact the same problem. 
- Changed the config.PHP file at CONFIG folder to add
$config['sess_save_path'] = BASEPATH . 'yourfoldername/cache/';
- verified the database.php fle at CONFIG folder to set database connection manually (it was filled with data from step 3)
- added the file site.php with the sample code at the #61 
- dumped my database and created again the necessary tables using the SQL file from #61 

Reloaded the application... and nothing!

Can you tell me how to solve it?

TIA

Wada

**Comment by wadaeko** [comment]
Corrected a path for $config['sess_save_path'] = BASEPATH . 'yourfoldername/cache/'; and worked now!
This issue must be solved to save other people to face the same problem.
Best
Wada

**Comment by ridwanskaterock** [comment]
Yes because the tmp folder on this framework is set to standard, root / tmp I'm glad to see this running thanks
