### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by icreas** [ridwanskaterock/cicool#68]
Hello, I have bought this software is impossible to install - neither locally on MAMP PRO nor on the web - I start to regret having it buy !!!!!!! Is there a clear solution and thank you for your reply cordially

**Comment by ridwanskaterock** [comment]
Hii you can give me detail problem for it and give me screenshoot for debugging thanks for purchasing

Regards

**Comment by icreas** [comment]
Good evening, the problem is the follow-up
I installed according to your instructions? I connect to the administrator part with the form and I click on dashboard I return d office to the login page impossible to connect to the dashboard. Here is difficult to make a copy to you!

Waiting to read you thanks

**Comment by icreas** [comment]
Good evening, the problem is the follow-up
I installed according to your instructions? I connect to the administrator part with the form and I click on dashboard I return d office to the login page impossible to connect to the dashboard. Here is difficult to make a copy to you!

Waiting to read you thanks

**Comment by icreas** [comment]
Hello 

ERROR
when removing crud builder here l error ????? Can correct you and upload a version that works without error thanks

**Comment by ridwanskaterock** [comment]
I did not find the same error with your problem, can you give me a screenshoot? Or more videos  i will help you for it, or you can give me access backend :)

Thanks

**Comment by icreas** [comment]
screenshot  follow

**Comment by ridwanskaterock** [comment]
resolved by email, thanks
