### ISSUE TITLE
Custom contents in Page Builder

### ISSUE THREAD

**Issue by yuriwf** [ridwanskaterock/cicool#69]
Hello!

In first time, congratulations! This system is great!

I want to create a new contents to PageBuilder, like a new contact forms and new headers. Can you explain me how to do this? You use a plugin for the builder?

Thanks!

**Comment by ridwanskaterock** [comment]
hiii

thanks for purchasing 

you can see video for make page builder https://www.youtube.com/watch?v=O9-vFtFciEM
and next you can make form https://www.youtube.com/watch?v=7nQwLjpOtnE

and you can embed form on page https://www.youtube.com/watch?v=OoK8XeHcErc

thanks
