### ISSUE TITLE
Mass user import from csv to database direct

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#7]
Hello,

I want to join more than 2000 users, I have it with excel spreadsheet, I can modify to CSV or related.

What are the step for made it correctly? I never used oauth addon.

Are there some script related to do this?

I want to create a clients member group and add all userlist to it.

I also want to create a new datatable with special info rows related to user datatable.

Thanks a lot.

**Comment by ridwanskaterock** [comment]
hii, we use aauth to make user management :)

you can read more about this library https://github.com/emreakay/CodeIgniter-Aauth

to add a new user you can menginsert with the following functions

```php

$id_user = $this->aauth->create_user('email', 'password', 'username');

//and for adding a user to a group

$this->aauth->add_member($id_user, $id_group);
```

to view the list of groups you can see on the list in the following table

aauth_groups


thanks

**Comment by R3N3G** [comment]
Hello,

I've created a php file controller, model and view of user.php modified to user_import.php with this lines on controller created with name User_import.php same as:

<?php
defined('BASEPATH') OR exit('No direct script access allowed');


/**
*| --------------------------------------------------------------------------
*| User Controller
*| --------------------------------------------------------------------------
*| user site
*|
*/
class User_import extends Admin	
{
	
	public function __construct()
	{
		parent::__construct();

		$this->load->model('model_user_import');
	}


	/**
	* Add New users
	*
	* @return JSON
	*/
	public function add_save_import()
	{
		
			
	if ( $this->aauth->create_user('xxxx4@hotmail.com','682404','xxxxxd22') ){echo 'OK. Succesful register';} else {echo 'Please fix the issues below';echo $this->aauth->print_errors();};echo'<br>';
if ( $this->aauth->create_user('xxx@hotmail.com','810140','xxxx22') ){echo 'OK. Succesful register';} else {echo 'Please fix the issues below';echo $this->aauth->print_errors();};echo'<br>';
.................
.................
.................
?>

I created with excel a php file with more than 2000 user imports and works fine!!!! All joined to default group, but with all data into database I can change all without problems

Thanks a lot!!

🥇

**Comment by ridwanskaterock** [comment]
okey man, I am glad to see your code works well,
good job,

I wait for the best review from you :)

thanks

**Comment by carlosanpardo** [comment]
This informnation too is useful. http://codeigniter-aauth-test.readthedocs.io/en/latest/functions/users.html
