### ISSUE TITLE
Custom views / controller

### ISSUE THREAD

**Issue by djbeynon** [ridwanskaterock/cicool#70]
Hello, 

i am trying to do a custom view for one of the cruds i have built but if i make changes to crud and save it overwrites the view files and therefore removes my custom changes.

Is there way for myself to create custom views that do not get overwritten or stop the system from overwriting the views?

Thanks

**Comment by ridwanskaterock** [comment]
Actually like a generator in general if there is a change of field rules etc, it will overwrite the old file, so if you have made crud builder in suggest that you do not make changes through the backend interface when it is custom code.

Thanks
