### ISSUE TITLE
custom php code

### ISSUE THREAD

**Issue by dali44** [ridwanskaterock/cicool#71]
Hi, 
All is working fine for now, i built fews pages with page builder but i cant put custom php code or external javascript libraries so can you please tell me how to do that ?
Best Regards

**Comment by ridwanskaterock** [comment]
Oh sorry i just got back to your question, i am sick. :)

for custom code only avaiable for js or css exteranl not PHP
![image](https://cloud.githubusercontent.com/assets/9270445/26133291/3626dff2-3ad0-11e7-87e0-3951ababe31f.png)

you can click sourcec on your element 

thanks

**Comment by dali44** [comment]
Hi, Get well and get back soon

so any way to embed to backend a page with my custom php code ? as i need to intereger to my application fews pages or popup like printing invoice and receipt, sending sms etc .. 

Best Regards

**Comment by ridwanskaterock** [comment]
For that you can make CRUD, page can not be inserted PHP code,
You can create CRUD and customize the controller, view and model files for it

thanks
