### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jiridusek** [ridwanskaterock/cicool#73]
Hi,
i just bought cicool few days ago and I have a problem with install an app. After copy whole application on server I can see this error on following page:  http://www.bluris.cz/cicool/
here is phpinfo: http://www.bluris.cz/cicool/info.php

Can you help me please?
BR,
Jiri

**Comment by ridwanskaterock** [comment]
hiii what file application/core/My_Controller.php is exsit on your application 

thanks

**Comment by jiridusek** [comment]
Hi,
sorry I missed notify email.. here is file included in folder as you want.. 
[My_Controller.php.zip](https://github.com/ridwanskaterock/cicool/files/1009426/My_Controller.php.zip)

**Comment by ridwanskaterock** [comment]
can you rename class name MY_Controller to My_Controller

![image](https://cloud.githubusercontent.com/assets/9270445/26181852/b3e3216c-3b9d-11e7-9f78-6cf5e15e2318.png)

running smothly ? 

if problem you can give me access FTP for debbuging 

thanks

**Comment by jiridusek** [comment]
Hi,
Still the same error only with new class name.

FTP:
server: m19321.svethostingu-multi.cz
port: 21
username: cicool.bluris.cz
pass: CilooAuthor10

In case any problem, just let me know.

Thanks for your support.
BR,
Jiri

S pozdravem,
Ing. Jiří Dušek


+420 777 930 944
dusek@xdent.cz
www.xdent.cz

Infinity Energy, s.r.o.
Masarykova 633
400 01 Ústí nad Labem

IČO:   273 37 871
DIČ: CZ 273 37 871

**Comment by ridwanskaterock** [comment]
i just set My_Controller to Ci_Controller on rest library 

usually this problem cause autoloading on your server 

you can access wizzard http://www.bluris.cz/cicool

thanks

**Comment by jiridusek** [comment]
Great,
Thanks a lot, perfect support!

Now it's time for cicool :)


Jiri

**Comment by ridwanskaterock** [comment]
I'm happy to see things go well,
I wait for the best review in codecanyon from you :) thanks
