### ISSUE TITLE
Blank Screen after Site Name Change

### ISSUE THREAD

**Issue by MurkleMan** [ridwanskaterock/cicool#74]
HI, i recently changed the name of the site and now it appears to be a blank scree, i did however change the site name to include bold tags.

I now have change the name manually back using phpmyadmin but the site still does not load at all.

Please assist.

**Comment by MurkleMan** [comment]
I have solved this issue, it seems that the session save url reset to NULL.
$config['sess_save_path'] = NULL;
Changed this to my home directory where i manually created a tmp folder.

**Comment by ridwanskaterock** [comment]
souds good!, thanks
