### ISSUE TITLE
Error Load Data with Page Widgets

### ISSUE THREAD

**Issue by MurkleMan** [ridwanskaterock/cicool#75]
When i open the page builder and drop one of the components i seem to get an error message "error load data".

Any help would be appreciated.

Image attached

![screen shot 2017-05-26 at 20 51 42](https://cloud.githubusercontent.com/assets/28985860/26511560/79d12ee2-425a-11e7-8831-9794e1b622a9.png)

**Comment by ridwanskaterock** [comment]
can you see XHR response for this ? 

thanks :)

**Comment by ridwanskaterock** [comment]
maybe error from server ?

**Comment by lisaiceland** [comment]
I'm getting same error:
https://cl.ly/0Z3w3L0d1G2h

Can you plz assist?

**Comment by ridwanskaterock** [comment]
Hi.

can you share ftp access to me

i will help you and check your configuration

Thanks




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>
Sent
with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality2&>

Pada tanggal Min, 8 Jul 2018 pukul 02.28 Lisaiceland Inc. <
notifications@github.com> menulis:

**Comment by GuillermoGuevara** [comment]
Hi, i got this error to, can you help me please! thanks in advance.

![captura de pantalla 2018-09-11 a la s 9 16 44 p m](https://user-images.githubusercontent.com/17258085/45397994-113cf000-b608-11e8-9c39-1f2f6021e184.png)

**Comment by ridwanskaterock** [comment]
hi can you tr call this url on your rowser 
![image](https://user-images.githubusercontent.com/9270445/45406594-31fd5800-b691-11e8-8584-2b33e1cf062f.png)
![image](https://user-images.githubusercontent.com/9270445/45406630-4a6d7280-b691-11e8-8d6c-912546920a57.png)

and make sure global xss filtering set to false on application/config/config.php

![image](https://user-images.githubusercontent.com/9270445/45406747-a7692880-b691-11e8-8abf-afa786f8b8df.png)

**Comment by GuillermoGuevara** [comment]
Hi again! Global xss its set false an when i call the url the response is:
{"success":false,"message":"Url is required"}

**Comment by ridwanskaterock** [comment]
so if you do on page builder not direct url, same getting an error ? 

Thanks

**Comment by GuillermoGuevara** [comment]
yes i got the same error, when i try to save a new page, i got a warning "The Page Content field is required." 

<img width="1429" alt="captura de pantalla 2018-09-12 a la s 10 09 43" src="https://user-images.githubusercontent.com/17258085/45434654-8ba35980-b674-11e8-90b8-7e9f2f535d45.png">


so when i try to put some element in the Page Designer section, i got the error 501

<img width="1439" alt="captura de pantalla 2018-09-12 a la s 10 13 20" src="https://user-images.githubusercontent.com/17258085/45434721-b42b5380-b674-11e8-873e-82fea7d349e1.png">

**Comment by ridwanskaterock** [comment]
can you share FTP access for it, and you can also ask to webmaster for this error 501 not implemented 
and you can see error log on your server 
Thanks

**Comment by ridwanskaterock** [comment]
this is my email : ridwanskaterocks@gmail.com

**Comment by GuillermoGuevara** [comment]
Ok, I already sent it.
