### ISSUE TITLE
Error with page builder

### ISSUE THREAD

**Issue by carlosanpardo** [ridwanskaterock/cicool#76]
Hello! Congratulations for your script. Is very useful!

I have an issue with the "Page Buillder": Later of create a page the content appears empty. I reviewed the console of the browser and appears a wrong link URL .

Please check the next screenshoots that shows all process:

1) Details of the page: https://snag.gy/X2vxZq.jpg
2) Content of the Page: https://snag.gy/mqhT5S.jpg
3) Save Page Success: https://snag.gy/qyuCwb.jpg
4) List of Pages: https://snag.gy/lgqD5k.jpg
5) Empty Page (The Error): https://snag.gy/Ph3x2Y.jpg
6) Error in console: https://snag.gy/oletDU.jpg

I request your help to verify the cause of this issue. Thank you!

**Comment by ridwanskaterock** [comment]
prior to debug try to open the file index.php

precisely in line 56 you will find a code like the following

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');

you like to change to be like this

define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
to see what pops up error

then you try to run back,
what response in the can?

thanks

**Comment by ridwanskaterock** [comment]
on` application/config/config.php `
global xss filtering is false ? 
`$config['global_xss_filtering'] = FALSE;`

thanks

**Comment by carlosanpardo** [comment]
Hi! Thank you for your response. The enviroment was setted to "development" but I do not received an error.

I made your second step, I changed the "global_xss_filtering" to "false" and now is working.

How I can use the global_xss_filtering and use the page builder?

**Comment by ridwanskaterock** [comment]
For global xss filtering does not allow scripts and html tags to go into the database, so that's what causes the problem on codeigniter :)

Sounds good if everything works, I'm waiting for the best review from you here https://codecanyon.net/item/cicool-page-form-rest-api-and-crud-generator/reviews/19207897 :) thanks
