### ISSUE TITLE
My Form Only allow 75 Fields

### ISSUE THREAD

**Issue by carlosanpardo** [ridwanskaterock/cicool#77]
Hello! I'm using the Form Builder and the form only receive 75 Fields. I changed the type of fiel (Options, Checkbox, Inputs) and the form is not receiving more fields.

I building a survey of a Human Resources area and the survey have more of 120 questions.

Can you explain me if the form builder have a limit?

I appreciate your help-

**Comment by ridwanskaterock** [comment]
But did you succeed in generating form all fields that fit your save error appears?

Can i see a screenshoot?

Thanks, previous form no limit :)

**Comment by carlosanpardo** [comment]
Hi! yes, is an error of the View, I changed manually the code to solve the issue but later of add more of 75 fields the form can't save the new fields,
