### ISSUE TITLE
Error: Sorry you do not have permission to access

### ISSUE THREAD

**Issue by emakundi** [ridwanskaterock/cicool#78]
Hello

As i explained earlier i am facing a slowness and i am getting a mesage saying "Sorry you do not have permission to access"

I have installed the script on two different server but i am still getting the same message and the same reaction

1. Server is a shared host environment 
shilawadu.co.tz/api 
username: info@shilawadu.co.tz
p: shilawadu

2. Server is a dedicated droplet 
app.shilawadu.co.tz/api
same username and password. 
 
Attached is the screenshot as well
<img width="1280" alt="screen shot 2017-06-06 at 08 59 51" src="https://cloud.githubusercontent.com/assets/3756040/26815942/e1c7b2a6-4a97-11e7-830c-ed41fa1b2b95.png">

**Comment by ridwanskaterock** [comment]
Does it happen when you install?
It seems the user does not have a role,
Can you give me access PHPMyAdmin?

thanks

**Comment by emakundi** [comment]
Can i have your email this is a production server i wont be confy sharing the credentials here or write to me at emakundi@gmail.com

**Comment by ridwanskaterock** [comment]
i just set you mail 

thanks
