### ISSUE TITLE
How Add permissions to the public form?

### ISSUE THREAD

**Issue by carlosanpardo** [ridwanskaterock/cicool#79]
Hi! I created a form but I need set permissions over the public form generated.

Can you explain me please? thank you

**Comment by ridwanskaterock** [comment]
you need all user to submit form ? not login required ? 

if yes you can embed form on page builder, see tutorial 
https://www.youtube.com/watch?v=O9-vFtFciEM
https://www.youtube.com/watch?v=OoK8XeHcErc

**Comment by carlosanpardo** [comment]
Hi! I embed the form in a page created with page builder but is public for all:
http://bit.ly/2rTzQ7G

I need that the user login to send the form.

Any ideas?

**Comment by ridwanskaterock** [comment]
really you build form in page builder ? it's so pretty view. 

for login required you can modify controller submission form on 

application/controllers/form/your_form.php

and modify submit function like this 

```
public function submit()
	{

		if (!$this->aauth->is_loggedin()) {
			
			return $this->response([
				'success' => false,
				'message' => 'You must loggin for submit form',
			]);

		}

.....
.....
.....
```

**Comment by carlosanpardo** [comment]
Yes I use the Form Builder and later I edit the code manually.

I understand the code if the user submit the form but I need a restriction to view the form. If the user is not logged into the website the user cant view the form.

Please give me a clue!

**Comment by ridwanskaterock** [comment]
amazing form layout!

yes you can modify on view like this function 

```
<?php if ($this->aauth->is_loggedin()): ?>
< your form html >
<?php else : ?>
< notif : you must login for submitting form >
<?php endif; ?>
```

**Comment by carlosanpardo** [comment]
Thank you Muhamad, the view now is working with a restriction. 

Can you give me indications to hide the button in the top menu? Is the part that I can't understand. 
https://snag.gy/m64Njb.jpg

I set the permissions to "members" but the button is visible for all users:

https://snag.gy/GXpIld.jpg

Check the frontend of the website:

https://snag.gy/Sb0HwZ.jpg


I appreciate the time that you expect with my case. I'm sure that other users will be use this informations too

**Comment by ridwanskaterock** [comment]
sorry for your case, 

for menu permission on current version only work on administrator menu :) 

if you need to custom you can modify this file 
`cc-content/themes/cicool/views/navigation.php`


thanks

**Comment by carlosanpardo** [comment]
Thank you for your help!

I move the <li> for the menu and now the menú only appear to the logged users:
`            <ul class="nav navbar-nav navbar-right">
            	<?php foreach (get_menu('top-menu') as $menu):?>
            	<?php endforeach; ?>
                <?php if (!app()->aauth->is_loggedin()): ?>
                <li>
                    <a class="page-scroll" href="<?= site_url('administrator/login'); ?>"><i class="fa fa-sign-in"></i> Login</a>
                </li>
                <?php else: ?>
                <li>
                    <a class="page-scroll" href="<?= site_url($menu->link); ?>"><?= $menu->label; ?></a>
                </li> 
                <li>
                    <a class="page-scroll" href="<?= site_url('administrator/auth/logout'); ?>"><i class="fa fa-sign-out"></i> Logout</a></li>   
                <li>
                    <a class="page-scroll dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                        <img src="<?= BASE_URL.'uploads/user/'.(!empty(get_user_data('avatar')) ? get_user_data('avatar') :'default.png'); ?>" class="img-circle img-user" alt="User Image"> 
                        <?= get_user_data('full_name'); ?>
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="<?= site_url('administrator/user/profile'); ?>">My Profile</a>
                        <a class="dropdown-item" href="<?= site_url('administrator/dashboard'); ?>">Dashboard</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?= site_url('administrator/auth/logout'); ?>"><i class="fa fa-sign-out"></i> Logout</a>
                    </div>
                </li>
                <?php endif; ?>
            </ul>`
