### ISSUE TITLE
Upgrade Procedures

### ISSUE THREAD

**Issue by buckr** [ridwanskaterock/cicool#8]
What's the procedure to upgrade from 1.8.1 to 1.9.5?  I tried a straight copy of the new cicool directory over top the old and it didn't work.

Thanks!

buckr

**Comment by ridwanskaterock** [comment]
hi bucker,

what problems arise when you copy the old folder into the new folder?
we can not be sure whether the problem was related to the configuration or the other :)

can be shared / screenshot problems more detail :)

thanks

**Comment by ridwanskaterock** [comment]
following this step 

https://github.com/ridwanskaterock/cicool/wiki/Upgrade-Guides-to-Version-1.9.5

**Comment by buckr** [comment]
Followed the steps in the Upgrade Guide and it worked perfectly.

Thanks!

buckr
