### ISSUE TITLE
Error Getting data and Header issue

### ISSUE THREAD

**Issue by paolosiligoni** [ridwanskaterock/cicool#80]
Hi,

i had two issues : 

1) The header have some code than i want remove 

2) when i try to list a table with some date i received an error "Error getting data"

please see the printscreen with the 2 issues 

![image](https://user-images.githubusercontent.com/24591576/26927648-09b9ef74-4c53-11e7-82b3-d70c5300c7bc.png)

**Comment by ridwanskaterock** [comment]
What is the response of XHR in the browser console? Can you send us a screenshoot?

thanks
