### ISSUE TITLE
Cicool/wizzard/setup/3 returned "The action you have requested is not allowed."

### ISSUE THREAD

**Issue by kunilkuda** [ridwanskaterock/cicool#83]
Hello,

Just bought the code. I need some help with the installation. The wizzard stopped after the database info (db name, username, password, site name, site admin, site password) inserted (after clicking 'Next' on htttp://mywebsite/cicool/wizzard/setup/3)

All files (database.php, config.php, migrations/001_cicool.php) are www-data writeable (the apache is running with www-data group), and htttp://mywebsite/cicool/wizzard/setup/1 shows all green status.

I've tried to enable the log in cicool/application/config/config.php, but nothing is there at application/log.

Let me know if there's some other permission that needs to be set. 

Thanks

**Comment by kunilkuda** [comment]
The problem seems like coming from csrf check.

The solution is:
1) Disable the csrf check temporarily: edit cicool/application/views/core_template/config_template.txt. Find '$config['csrf_protection'] = TRUE;' and set it to '$config['csrf_protection'] = FALSE;'

2) Enable the session directory: edit cicool/application/views/core_template/config_template.txt. Find '$config['sess_save_path'] = NULL' and set it to '$config['sess_save_path'] = APPPATH . 'cache/''

3) Set APPPATH.'cache/' (or cicool/application/cache) to writeable. 'sudo chmod ug+w cicool/application/cache

4) Set APPPATH.'config/' to writeable. 'sudo chmod ug+w cicool/application/config'.

Now I can login to the admin / dashboard panel

**Comment by kunilkuda** [comment]
Additional info, the CRUD generator required these directories to be writeable:
$APPPATH . 'controller/administrator/', $APPPATH . 'model/', and $APPPATH . 'view/backend'.

(chmod ug+w -R cicool/application/controller/administrator/ cicool/application/model cicool/application/view/backend)

Otherwise it will generate error after saving the CRUD

**Comment by acxeltechpr** [comment]
Set APPPATH.'cache/' (or cicool/application/cache) to writeable. 'sudo chmod ug+w cicool/application/cache

Set APPPATH.'config/' to writeable. 'sudo chmod ug+w cicool/application/config'.

?
