### ISSUE TITLE
Menu permissions, I'm doing bad?

### ISSUE THREAD

**Issue by R3N3G** [ridwanskaterock/cicool#87]
Hello,

I create a menu than I want to view admin and other group name, I can view the label menu, but I can't view on admin or user group.

I analyze and the group permissions won't show, I try to change group permission and give me error no save.

I can show dashboard link on user group but I can't my own menu adds.

Why dashboard is ok but my own menu link won't show.

What I'm doing wrong? I analyze database and the perms are ok...

I don't understand how it works.

menu items...
![image](https://user-images.githubusercontent.com/20468345/27688343-8b822b10-5cda-11e7-8a47-5fc4e2630ca7.png)

auth access

![image](https://user-images.githubusercontent.com/20468345/27688421-d6f7710e-5cda-11e7-8d44-44b52697ae47.png)

I want all links on access permissions, if I can put one element good on menu with good perms I can make all changes. I don't understand the problem exactly.

Menu of new usergroup

![image](https://user-images.githubusercontent.com/20468345/27688514-1a83e10a-5cdb-11e7-9ed0-5e7c859533fc.png)

aauth_perms ----> menu id = 129
                               label id = 130

![image](https://user-images.githubusercontent.com/20468345/27688644-955e54c8-5cdb-11e7-9751-e6e813b8565c.png)

usergroup id = 5

All in database it's ok, and code believe also, Why won't show my own menu added to standard admin menu? Only view operadores.

Sorry for my english.

Thanks.

**Comment by R3N3G** [comment]
Maybe the error?

![image](https://user-images.githubusercontent.com/20468345/27734801-e43307ee-5d9c-11e7-945a-f8201b0e0a39.png)

I can't change privileges

**Comment by R3N3G** [comment]
Hello,

Nobody happens this issue??? What is the correct way for give permissions to usergroup for view the menu items?

Thanks

**Comment by R3N3G** [comment]
Hello,

Sorry for the inconvience, I understanding the menu add buttons, Is not possible add a link into a label menu, it's only for separate sections. 

Sorry, thans a lot.

**Comment by ridwanskaterock** [comment]
hi you can't add sub menu on label @R3N3G, Sorry for the delay I just started to work

**Comment by parth8866651442** [comment]
![Uploading set link.JPG…]()
