### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by soeranto** [ridwanskaterock/cicool#88]
Saya pakai iis win 10
 
Pada saat setup pertama muncul : 

Warning!

there are some files can not be read by the system, make sure the file in write mode 0666.
Directory & Permissions	Status
../application/config/database.php is writeable	warning
../application/config/config.php is writeable	warning
../application/migrations/001_cicool.php is writeable	warning

Click Next muncul : 

http://localhost/cicool/wizzard/setup/2 

HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Please Help

Trimakasih

**Comment by carlosanpardo** [comment]
Hi! Check that the .htaccess file is inside the CI folder. Greetings

**Comment by ridwanskaterock** [comment]
thanks for help answer some question
