### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by soeranto** [ridwanskaterock/cicool#89]
Saya pakai iis win 10
 
Pada saat setup pertama muncul : 

Warning!

there are some files can not be read by the system, make sure the file in write mode 0666.
Directory & Permissions	Status
../application/config/database.php is writeable	warning
../application/config/config.php is writeable	warning
../application/migrations/001_cicool.php is writeable	warning

Click Next muncul : 

http://localhost/cicool/wizzard/setup/2 

HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Please Help

Trimakasih

**Comment by ridwanskaterock** [comment]
itu kalo di tambah index.php bisa muncul mas ? 

http://localhost/cicool/index.php/wizzard/setup/2

**Comment by soeranto** [comment]
Hi mas ridwan,

Mau muncul, setelah diisi  keluarnya blank screen

http://localhost/cicool/index.php/wizzard/setup/3

gimana lanjutannya mas?

thanks

**Comment by ridwanskaterock** [comment]
kalo bisa di akses dengan index.php berarti setingan mod_rewrite pada
servernya blm di aktifkan mas.

nanti bisa di rubah juga environtmennya di index.php

jadi development biar bisa tau errornya apa

2017-07-03 9:16 GMT+07:00 soeranto <notifications@github.com>:

**Comment by soeranto** [comment]
saya udah download urlrewrite untuk iis, tapi ga ngerti settingnya mas

**Comment by ridwanskaterock** [comment]
ini mungkin bisa bantu mas 
https://stackoverflow.com/questions/9965124/how-to-rewrite-the-index-php-of-codeigniter-on-windows-azure

**Comment by soeranto** [comment]
udah saya tambah rulenya, masih ga mau : 

http://localhost/cicool/index.php/wizzard/setup/3
tampil setingan database, setelah click next

http://localhost/cicool/index.php/wizzard/setup/3

tampilan blank

**Comment by soeranto** [comment]
saya coba tambah webconfig :

<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Security Rule" stopProcessing="true">
          <match url="^(.*)$" ignoreCase="false" />
          <conditions logicalGrouping="MatchAny">
            <add input="{QUERY_STRING}" pattern="mosConfig_[a-zA-Z_]{1,21}(=|\%3D)" ignoreCase="false" />
            <add input="{QUERY_STRING}" pattern="base64_encode.*\(.*\)" ignoreCase="false" />
            <add input="{QUERY_STRING}" pattern="(\&lt;|%3C).*script.*(\>|%3E)" />
            <add input="{QUERY_STRING}" pattern="GLOBALS(=|\[|\%[0-9A-Z]{0,2})" ignoreCase="false" />
            <add input="{QUERY_STRING}" pattern="_REQUEST(=|\[|\%[0-9A-Z]{0,2})" ignoreCase="false" />
          </conditions>
          <action type="CustomResponse" url="index.php" statusCode="403" statusReason="Forbidden" statusDescription="Forbidden" />
        </rule>
        <rule name="SEO Rule">
          <match url="(.*)" ignoreCase="false" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" pattern="" ignoreCase="false" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" pattern="" ignoreCase="false" />
            <add input="{URL}" negate="true" pattern="^/index.php" ignoreCase="false" />
            <add input="{URL}" pattern="(/|\.php|\.html|\.htm|\.feed|\.pdf|\.raw|/[^.]*)$" />
          </conditions>
          <action type="Rewrite" url="index.php" />
        </rule>
      </rules>
    </rewrite>
 </system.webServer>
</configuration>

dari : https://stackoverflow.com/questions/13814768/how-can-i-enable-mod-rewrite-on-iis-server

masih belum mau

**Comment by soeranto** [comment]
hallo mas ridwan,

supaya bisa jalan gimana mas?  ga usah pakai install / wizard dulu deh.
apa saja yang perlu disetting?

trims

**Comment by ridwanskaterock** [comment]
tapi database sudah masuk apa belum mas ? 

kalo udah masuk bisa di konfigurasi settingan databasenya

dan buat file site.php pada application/config/

**Comment by soeranto** [comment]
database sudah masuk, dan kalo dibuka file site.php isinya :
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| Your site name,
|
*/
$config['site_name'] = 'Cicool';

terus gimana mas?

**Comment by ridwanskaterock** [comment]
terus bisa akses dashboard mas ? 
harusnya kalo udah masuk dan site.php sudah terbuat bisa mas

**Comment by soeranto** [comment]
ga bisa mas file site.php masih kosong isinya

**Comment by carlosanpardo** [comment]
Hi! Check the ,htaccess file inside the public_html folder  or equivalent ;)
