### ISSUE TITLE
Page builder HTTP ERROR 500

### ISSUE THREAD

**Issue by vin111** [ridwanskaterock/cicool#9]
I just installed cicool but I noticed that the page builder does not function and goes into error http error 500

PHP Fatal error:  Call to a member function registerScriptFile() on null in /home/********/project/cicool/cicool/cc-content/extensions/page-form-builder/config.php on line 11,

**Comment by ridwanskaterock** [comment]
hiii, 

if you could be running a login function, making crud builder and the other with normal?

whether the **application/config/site.php** in your application?

thanks

**Comment by vin111** [comment]
hi,
does everything except page builder
![cattura](https://cloud.githubusercontent.com/assets/25017968/21788310/42a94a6e-d6ce-11e6-9f67-c36ab5ed6583.JPG)

![cattura1](https://cloud.githubusercontent.com/assets/25017968/21788428/e7e184ce-d6ce-11e6-8f56-e93e86044592.JPG)

![cattura3](https://cloud.githubusercontent.com/assets/25017968/21788454/1a7223e4-d6cf-11e6-93f4-3fc2f646333a.JPG)


![cattura2](https://cloud.githubusercontent.com/assets/25017968/21788423/e0a58b74-d6ce-11e6-9e55-7fc50440925c.JPG)

**Comment by ridwanskaterock** [comment]
sorry this error does not occur on the installation we have attempted on several neighborhoods

you try to add the following code on

$this->load->library(['aauth', 'cc_html', 'cc_page_element', 'cc_app']);

application/controllers/administrator/page.php

exactly on line 19

under the function

$this->load->model( 'model_page');


thanks

**Comment by vin111** [comment]
I followed the instructions but still does not work, but I solved it by adding this line:
$ Cc_core-> load-> library ('cc_html');
in /cicool/cc-contents/extensions/page-form-builder/config.php file to the line 10
for now it seems to work but I have to test well
![5](https://cloud.githubusercontent.com/assets/25017968/21802603/b2ef2a52-d726-11e6-8a9c-6ec28fd406fa.JPG)

**Comment by ridwanskaterock** [comment]
OK it looks like it's running smoothly,

I am glad to see everything is running normally,

we are waiting for the best review from you :)

thanks
