### ISSUE TITLE
is posible to create another filter in the auth? 

### ISSUE THREAD

**Issue by alejf** [ridwanskaterock/cicool#90]
Hello, if i want to filter  contents for a varibles or another table in bd is possible?

**Comment by ridwanskaterock** [comment]
yes is possible you can custom this on views and models

**Comment by ridwanskaterock** [comment]
Yes it's possible, you can add another field wil yku searching, add to
model on variable field search

Thanks

Pada tanggal 8 Jul 2017 7:51 AM, "alejf" <notifications@github.com> menulis:
