### ISSUE TITLE
Set user permission so that one user can only see their records

### ISSUE THREAD

**Issue by smila05** [ridwanskaterock/cicool#92]
Can I set permission so that one user can only see in CRUD the entries that he added himself, and not those by other people? The permissions are only for groups but I want to limit a user to their own records created or a record created for them by the admin.

Kinda like a Landlord and Tenant group. I want Tenants to only see their own filled CRUD or Form application but Landlord sees all the applications.

Below shows other crud builders with what am talking about.

![screen shot 2017-07-26 at 4 31 54 am](https://user-images.githubusercontent.com/30464093/28616659-28f79a5e-71c3-11e7-8e81-dd8ee5a25bff.png)

1. Can you show me how to implement this if possible with an example where to add the code or file.
2. Is this a feature we can expect in the next update?

Thanks

**Comment by ridwanskaterock** [comment]
for current version not support for user can see only current user created data or save data, 

but you can add field user_id on table and on crus builder you can select input type "current_user_id" and you can add database filter on model like 

$this->db->where('user_id', get_user_data('id')); and you will get data only user created 

thanks

**Comment by smila05** [comment]
That worked but now the admin cant see those records. How can I set it so an admin or a user group can see all the saved data.

Also is there a way to add the export as PDF or XLS options in access so I can uncheck it to remove it for regular users.

Thanks

**Comment by sottey** [comment]
This is a big help. I added it to the model gen code so that even when I make a change to the crud it is there.

My problem is that I can't find where the select code is generated. This means that, when I use a select in a form, the select has everyone's values.

Where is the code that generates the control on a form?

Thanks

**Comment by sottey** [comment]
Finally found it.

Changing file:
.../cicool\application\helpers\app_helper.php

update the db_get_all_data function to look like this:

`if(!function_exists('db_get_all_data')) {
	function db_get_all_data($table_name = null, $where = false) {
		$ci =& get_instance();
		if ($where) {
			$ci->db->where($where)->where('owner', get_user_data('id'));
		}
		else
		{
		    $ci->db->where('owner', get_user_data('id'));
		}
	  	$query = $ci->db->get($table_name);

	    return $query->result();
	}
}`

**Comment by ridwanskaterock** [comment]
nice good job for that 

i will close this issue 

thanks

**Comment by hlmyhlm** [comment]
Hi, I have tried this mod but admin cannot view data? only owner can view and edit. How to enable if admin can view all data (example for review and giving approval to post)  and user can only view its own 
 data he entered?
