### ISSUE TITLE
Setup (English)

### ISSUE THREAD

**Issue by rrainier3** [ridwanskaterock/cicool#93]
Hi, I installed and went through the setup with db & web admin user.  When I logged in it takes me to the demo CMS page with the header menu - Home, About, Get Started, Dashboard, Login pages. Clicking on About, Get Started gives "404 Page Not Found" which is ok perhaps they're not created yet. But clicking on the Dashboard - brings me back to Login page!  The same as clicking on Login on the menu.  How do I get around this? or what is the issue??

thank you
purchased user - riverridgeconsulting

**Comment by ridwanskaterock** [comment]
can you give me the screenshoot ? 

you can has been finished the installation wizzard ? 
thanks

**Comment by rrainier3** [comment]
I have found that the lexical variable error is a bug in php 7.1+ so the workaround is to downgrade the version.  Now it is so far working as you described in the docs and video. FYI
