### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bahsaa** [ridwanskaterock/cicool#96]
hello

I Can't Install CICOOL in my hosting.
Error Text : 
An Error Was Encountered

The action you have requested is not allowed.

Plaese Help me

**Comment by ridwanskaterock** [comment]
What is your server ?

Can you change environtment production to development for showing all
errors ?
You can change the environtment on index.php

Thanks

Pada tanggal 5 Agt 2017 8:16 PM, "iMan Farhadi" <notifications@github.com>
menulis:
