### ISSUE TITLE
Session issue

### ISSUE THREAD

**Issue by Sunrise91** [ridwanskaterock/cicool#97]
Hello

First i apperciate this great work offered by you.. really gr8 product
I have an issue... when redirecting from User controller to administrator/login with flashdata in session ,, the session is being lost.. why ?

```
public function lock($id) {

		$object = AR\User::find($id);

			$object->banned = "1";
			$object->save();

			$this->aauth->logout();

			$this->session->set_flashdata("f_message", "Account is now locked");
			redirect('administrator/login');
	}
```

**Comment by ridwanskaterock** [comment]
hii sorry for long time forr support, 
what you user the library for model ? 
you custome for it ? 

before can you set environtment to development for see the error ?
and you can set log thereshold to 4 on `application/config/config.php`

maybe this error cause session save path, 
can you check the valid session path on your server and you can change the path on `application/config/config.php`

thanks verry sorry for long time for response,
