### ISSUE TITLE
Issues with 2017-08-10 release

### ISSUE THREAD

**Issue by sottey** [ridwanskaterock/cicool#98]
I have had a couple of issues with installing the new version.

1) I don't see how to turn off demo mode. it is currently stating that the DB will be reset every 60 minutes. How do I turn that off?

2) The install was failing during the DB creation step. The following line in ...application/migrations/001_cicool.php was causing an exception:
`                $this->db->query(" 
                    set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
                 ");`

I commented it out and the install went fine.

Thank you for a great product!
Sean

**Comment by ridwanskaterock** [comment]
For demo mode you can deleting cc content/cc-extension/demo-mode
Thanks

Pada tanggal 10 Agt 2017 23:04, "Sean Ottey" <notifications@github.com>
menulis:

**Comment by sottey** [comment]
Thanks for the update!

I didn't necessarily want to get rid of the demo mode, so I created a fix allowing me to toggle it in the DB. It is listed on my blog [here](http://seanottey.com/2017/08/05/cicool-builder-crud-and-more-my-findings-so-far/)

**Comment by ridwanskaterock** [comment]
Thanks for that :)
